### ISSUE TITLE
test hmmsearch/pfam fail 

### ISSUE THREAD

**Issue by mldillon-LBL** [Ecogenomics/GTDBTk#107]
Hello,

I'm getting a test fail that might have to do with hmmsearch:

gtdbtk test --out_dir gtdbtk_test_out/
[2019-03-25 08:31:14] INFO: GTDB-Tk v0.2.2
[2019-03-25 08:31:14] INFO: gtdbtk test --out_dir gtdbtk_test_out/
[2019-03-25 08:31:14] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
Command:
gtdbtk classify_wf --genome_dir gtdbtk_test_out/genomes --out_dir gtdbtk_test_out/output --cpus 1
[2019-03-25 08:31:15] INFO: GTDB-Tk v0.2.2
[2019-03-25 08:31:15] INFO: gtdbtk classify_wf --genome_dir gtdbtk_test_out/genomes --out_dir gtdbtk_test_out/output --cpus 1
[2019-03-25 08:31:15] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2019-03-25 08:31:15] INFO: Identifying markers in 3 genomes with 1 threads.
[2019-03-25 08:31:15] INFO: Running Prodigal to identify genes.
==> Finished processing 3 of 3 (100.0%) genomes.
[2019-03-25 08:31:39] INFO: Identifying TIGRFAM protein families.
Incorrect number of command line arguments.

But I after listing hmmsearch -h, I get:

==> Finished processing 3 of 3 (100.0%) genomes.
[2019-03-25 08:31:39] INFO: Identifying Pfam protein families.
Process Process-6:
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/pfam_search.py", line 131, in _workerThread
    raise error
CalledProcessError: Command 'hmmsearch --notextw --cpu 1 --cut_ga /media/mk/My Passport/Meta_Perma_Meta/gtdbtk/release86/markers/pfam/Pfam-A.hmm gtdbtk_test_out/output/marker_genes/genome_2/genome_2_protein.faa' returned non-zero exit status 1
[2019-03-25 08:31:40] ERROR: Pfam Error
('Unexpected error:', <type 'exceptions.ValueError'>)
Traceback (most recent call last):
  File "/home/mk/anaconda3/envs/gtdbtk/bin/gtdbtk", line 408, in <module>
    gt_parser.parse_options(args)
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 388, in parse_options
    self.identify(options)
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 161, in identify
    options.prefix)
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/markers.py", line 244, in identify
    pfam_search.run(gene_files)
  File "/home/mk/anaconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/pfam_search.py", line 185, in run
    raise ValueError("Pfam Error")
ValueError: Pfam Error
[2019-03-25 08:31:40] INFO: Test has successfully finished.

So, maybe this is a pfam issue? Also:

(gtdbtk) mk@mk-davis:~$ which hmmsearch
/home/mk/anaconda3/envs/gtdbtk/bin/hmmsearch

I would appreciate any help here, not sure what's happening.

Thanks!!

Megan

**Comment by pchaumeil** [comment]
Hello Megan,
Could you please provide the version of hmmsearch you are using ( hmmsearch -h) ?

Thanks,
Pierre

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
