### ISSUE TITLE
 Pfam Error

### ISSUE THREAD

**Issue by TJrogers86** [Ecogenomics/GTDBTk#109]
Hey y'all,

I am getting the following error when trying to run the classify workflow. Any advice??
[2019-04-04 18:23:13] INFO: gtdbtk classify_wf --genome_dir ./CR_FUNCT_ANNOT/bin_translated_genes/ --extension faa --out_dir CR_gtdbtk_output
[2019-04-04 18:23:13] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2019-04-04 18:23:13] INFO: Identifying markers in 406 genomes with 1 threads.
[2019-04-04 18:23:13] INFO: Running Prodigal to identify genes.
==> Finished processing 406 of 406 (100.0%) genomes.
[2019-04-04 18:27:50] INFO: Identifying TIGRFAM protein families.
==> Finished processing 58 of 406 (14.3%) genomes.
Error: Sequence file CR_gtdbtk_output/marker_genes/bin.216/bin.216_protein.faa is empty or misformatted

Process Process-4:
Traceback (most recent call last):
  File "/home/lloydlab/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/lloydlab/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/external/tigrfam_search.py", line 115, in _workerThread
    checksum = sha256(output_hit_file)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/tools.py", line 70, in sha256
    with open(input_file, 'rb') as afile:
IOError: [Errno 2] No such file or directory: 'CR_gtdbtk_output/marker_genes/bin.216/bin.216_tigrfam.tsv'

[2019-04-04 18:28:13] INFO: Identifying Pfam protein families.
FATAL: no sequence given58 of 406 (14.3%) genomes.
[2019-04-04 18:28:16] ERROR: Pfam Error
('Unexpected error:', <type 'exceptions.ValueError'>)
Traceback (most recent call last):
  File "/home/lloydlab/miniconda2/bin/gtdbtk", line 408, in <module>
    gt_parser.parse_options(args)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/main.py", line 388, in parse_options
    self.identify(options)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/main.py", line 161, in identify
    options.prefix)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/markers.py", line 244, in identify
    pfam_search.run(gene_files)
  File "/home/lloydlab/miniconda2/lib/python2.7/site-packages/gtdbtk/external/pfam_search.py", line 185, in run
    raise ValueError("Pfam Error")
ValueError: Pfam Error

**Comment by pchaumeil** [comment]
Hello,
It seems Prodigal cannot detect any gene in one of your bin ( bin.216 ) so the downstream analysis cannot take place.
To check the quality of your bins, we would recommend running CheckM (https://github.com/Ecogenomics/CheckM)  before submitting your results to GTDB-Tk.


Thanks,
Pierre

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
