### ISSUE TITLE
Exception: Unable to get mask from hmm align result file

### ISSUE THREAD

**Issue by Erica9219** [Ecogenomics/GTDBTk#166]
gtdbtk align  --identify_dir ./identify --out_dir test
[2019-07-23 10:02:21] INFO: GTDB-Tk v0.3.2
[2019-07-23 10:02:21] INFO: gtdbtk align --identify_dir ./identify --out_dir test
[2019-07-23 10:02:21] INFO: Using GTDB-Tk reference data version r89: /home/zhangtingting/reference/release89/
[2019-07-23 10:02:21] INFO: Aligning markers in 1 genomes with 1 threads.
[2019-07-23 10:02:21] INFO: Processing 1 genomes identified as archaeal.
[2019-07-23 10:02:21] INFO: Read concatenated alignment for 1248 GTDB genomes.
Process Process-2:
Traceback (most recent call last):
  File "/home/zhangtingting/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zhangtingting/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangtingting/anaconda3/lib/python3.7/site-packages/gtdbtk/external/hmm_aligner.py", line 97, in _worker
    marker_set_id)
  File "/home/zhangtingting/anaconda3/lib/python3.7/site-packages/gtdbtk/external/hmm_aligner.py", line 199, in _run_multi_align
    self._run_align(gene_dict, db_genome_id))
  File "/home/zhangtingting/anaconda3/lib/python3.7/site-packages/gtdbtk/external/hmm_aligner.py", line 238, in _run_align
    marker_info.get("gene"), stdout)
  File "/home/zhangtingting/anaconda3/lib/python3.7/site-packages/gtdbtk/external/hmm_aligner.py", line 278, in _get_aligned_marker
    raise Exception("Unable to get mask from hmm align result file")
Exception: Unable to get mask from hmm align result file

**Comment by aaronmussig** [comment]
Hello,

It looks like you're running python 3.7, try creating a python 2.7 environment and let us know if you get the same issue.

**Comment by aaronmussig** [comment]
Closing this due to inactivity, please re-open if the issue persists.
