### ISSUE TITLE
Error during align step: 'Boolean index did not match...'

### ISSUE THREAD

**Issue by justinmaire** [Ecogenomics/GTDBTk#182]
Hi!

I'm having some trouble running classify_wf, it always stops at the beginning of the align step for a reason that's a bit over my head honestly (new to Unix here!). Here the log I get:

[2019-08-22 15:03:34] INFO: GTDB-Tk v0.3.2
[2019-08-22 15:03:34] INFO: gtdbtk classify_wf --genome_dir /data/cephfs/punim0749/justin/sym_genomes/Sym_A3_MA_B_047/PROKKA_08212019 --out_dir /data/cephfs/punim0749/justin/sym_genomes/Sym_A3_MA_B_047/gtdbtk
[2019-08-22 15:03:34] INFO: Using GTDB-Tk reference data version r89: /data/cephfs/punim0749/justin/release89/
[2019-08-22 15:03:34] INFO: Identifying markers in 1 genomes with 1 threads.
[2019-08-22 15:03:34] INFO: Running Prodigal to identify genes.
[2019-08-22 15:04:01] INFO: Identifying TIGRFAM protein families.
[2019-08-22 15:04:12] INFO: Identifying Pfam protein families.
[2019-08-22 15:04:14] INFO: Done.
[2019-08-22 15:04:14] INFO: Aligning markers in 1 genomes with 1 threads.
[2019-08-22 15:04:14] INFO: Processing 1 genomes identified as bacterial.
[2019-08-22 15:04:14] INFO: Read concatenated alignment for 737 GTDB genomes.
[2019-08-22 15:04:18] INFO: Masking columns of multiple sequence alignment using canonical mask.
[2019-08-22 15:04:19] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: boolean index did not match indexed array along dimension 0; dimension is 27884 but corresponding boolean dimension is 41155
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/jmaire/.local/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/home/jmaire/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 600, in parse_options
    self.align(options)
  File "/home/jmaire/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 252, in align
    options.outgroup_taxon)
  File "/home/jmaire/.local/lib/python2.7/site-packages/gtdbtk/markers.py", line 551, in align
    min_perc_aa / 100.0)
  File "/home/jmaire/.local/lib/python2.7/site-packages/gtdbtk/markers.py", line 331, in _apply_mask
    masked_seq = ''.join(np.array(list(seq), dtype=str)[list_mask])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 27884 but corresponding boolean dimension is 41155
================================================================================

I'm running this on .fna files from Prokka analyses. I tried with several genomes and always get this exact error. It does work on the web KBase version so I'm assuming there might be a problem with my installation? If anyone has encountered this error or knows anything on how to fix it, any help will be greatly appreciated!

Thanks!
Justin

**Comment by aaronmussig** [comment]
Hello,

It sounds like your reference data is corrupted. One of the lines from your output indicates it only read `737 GTDB genomes`, whereas it should read 23458.

You should expect an md5sum of `ad01ef6e207e0a2fe0c6b6f52be8d364` if you run:
`md5sum $GTDBTK_DATA_PATH/taxonomy/gtdb_taxonomy.tsv`

If you still have the archive on your disk, you should find that the md5sum is:
`82966ef36086237d7230955e2bfff759  gtdbtk_r89_data.tar.gz`

If it is, try extracting the data again, otherwise, try re-downloading the archive again from [here](https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/).

**Comment by justinmaire** [comment]
Hi Aaron,

Thanks for your answer, it did resolve the problem!
I'm now facing another problem that seems to be quite common: the 'Out of memory' error during pplacer, which is a little weird considering I'm only doing one genome at a time, using 1 cpu. I'll play around a bit to see if I can solve it, but might come back to you if it doesn't work!

Thanks a lot.
Justin

**Comment by aaronmussig** [comment]
Thanks for the feedback, there's a bit of information available in issues #124 and #170. Let us know if there are any issues.
