### ISSUE TITLE
Command to calculate ANI to GTDB representatives

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/GTDBTk#191]
It would be nice to add a new CLI command that took a set of genomes (same formats as supported by the classify workflow) and calculated the ANI to each GTDB species representative genomes. The output would be two files:
1) ANI and AF values for all pairwise comparisons producing valid results (note that FastANI will not report a value for distance genomes)
2) ANI/AF to the closest GTDB representative for each input genome (or "no result" if FastANI failed to produce a value for all representatives)

**Comment by phugenholtz** [comment]
sounds like a good idea.

**Comment by cheberling** [comment]
I tried out the new ani_rep command and got the error:

`[2020-05-07 13:58:26] ERROR: FastANI returned a non-zero exit code.
[2020-05-07 13:58:26] ERROR: Controlled exit resulting from an unrecoverable error or warning.
`
It looks like this error was attempted to be addressed in a previous update to gtdbtk, but appears to be still an issue.  I attempted to run on 141 query genomes with 8 threads.  Controlled exit occurred after less than 10 minutes user time.

I currently have another job running on > 3k genomes which has been fine so far.  I have run fastANI manually previously on all pair-wise comparisons between my query genomes.

**Comment by cheberling** [comment]
Full error log:

```
Thu May  7 13:40:54 EDT 2020
[2020-05-07 13:40:55] ^[[1mINFO:^[[0m GTDB-Tk v1.1.1
[2020-05-07 13:40:55] ^[[1mINFO:^[[0m gtdbtk ani_rep -x fna --no_mash --cpus 8 --genome_dir /nfs/vedanta/vbi_san1/data/culture\
_collection/genome_database/CB18_2020Apr/genomes --out_dir /nfs/vedanta/vbi_san1/data/culture_collection/genome_database/CB18_\
2020Apr/genomes/gtdbtk/ani_rep
[2020-05-07 13:40:55] ^[[1mINFO:^[[0m Using GTDB-Tk reference data version r89: /nfs/vedanta/vbi_san1/databases/gtdbtk/release\
89/release89
[2020-05-07 13:40:55] ^[[1mINFO:^[[0m Calculating ANI with FastANI.
Process Process-2:
Traceback (most recent call last):
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 207, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 279, in run_proc
    return self._parse_output_file(output)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 298, in _parse_outpu\
t_file
    path_qry, path_ref, ani, frac1, frac2 = line.strip().split('\t')
ValueError: not enough values to unpack (expected 5, got 1)

[2020-05-07 13:58:26] ^[[1;31mERROR:^[[0m FastANI returned a non-zero exit code.
[2020-05-07 13:58:26] ^[[1;31mERROR:^[[0m Controlled exit resulting from an unrecoverable error or warning.
```
