### ISSUE TITLE
ERROR: Controlled exit resulting from an unrecoverable error or warning.

### ISSUE THREAD

**Issue by minjaekim45** [Ecogenomics/GTDBTk#208]
**Hello
I'm trying to use this in our cluster and got an error while running a MAG.
(it was installed through conda)
here is the log file**

[2019-12-12 12:50:47] INFO: GTDB-Tk v1.0.2
[2019-12-12 12:50:47] INFO: gtdbtk classify_wf --genome_dir ./ --out_dir ./output/
[2019-12-12 12:50:47] INFO: Using GTDB-Tk reference data version r89: /account/mkim/anaconda3/envs/gtdbtk/share/gtdbtk-1.0.2/db/
[2019-12-12 12:50:47] ERROR: No genomes found in directory: ./. Check the --extension flag used to identify genomes.
[2019-12-12 12:50:47] ERROR: Controlled exit resulting from an unrecoverable error or warning.
[2019-12-12 12:51:12] INFO: GTDB-Tk v1.0.2
[2019-12-12 12:51:12] INFO: gtdbtk classify_wf --extension fasta --genome_dir ./ --out_dir ./output/
[2019-12-12 12:51:12] INFO: Using GTDB-Tk reference data version r89: /account/mkim/anaconda3/envs/gtdbtk/share/gtdbtk-1.0.2/db/
[2019-12-12 12:51:12] INFO: Identifying markers in 1 genomes with 1 threads.
[2019-12-12 12:51:13] INFO: Running Prodigal V2.6.3 to identify genes.
[2019-12-12 12:52:12] INFO: Identifying TIGRFAM protein families.
[2019-12-12 12:52:23] INFO: Identifying Pfam protein families.
[2019-12-12 12:52:24] INFO: Annotations done using HMMER 3.2.1 (June 2018)
[2019-12-12 12:52:25] INFO: Done.
[2019-12-12 12:52:28] INFO: Aligning markers in 1 genomes with 1 threads.
[2019-12-12 12:52:28] INFO: Processing 1 genomes identified as bacterial.
[2019-12-12 12:52:33] INFO: Read concatenated alignment for 23458 GTDB genomes.
[2019-12-12 12:52:45] INFO: Masking columns of multiple sequence alignment using canonical mask.
[2019-12-12 12:53:38] INFO: Masked alignment from 41155 to 5040 AAs.
[2019-12-12 12:53:38] INFO: 0 user genomes have amino acids in <10.0% of columns in filtered MSA.
[2019-12-12 12:53:38] INFO: Creating concatenated alignment for 23459 GTDB and user genomes.
[2019-12-12 12:53:38] INFO: Creating concatenated alignment for 1 user genomes.
[2019-12-12 12:53:38] INFO: Done.
[2019-12-12 12:53:38] WARNING: pplacer requires ~113 GB of RAM to fully load the bacterial tree into memory. However, 98.82GB was detected. This may affect pplacer performance.
[2019-12-12 12:53:38] INFO: Placing 1 bacterial genomes into reference tree with pplacer (be patient).
[2019-12-12 13:05:11] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer, check the log file: ./output/classify/intermediate_results/pplacer/pplacer.bac120.out
________________________________________________________________________________

Traceback (most recent call last):
  File "/account/mkim/anaconda3/envs/gtdbtk/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/account/mkim/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 625, in parse_options
    self.classify(options)
  File "/account/mkim/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 409, in classify
    classify.run(genomes,
  File "/account/mkim/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/classify.py", line 345, in run
    classify_tree = self.place_genomes(user_msa_file,
  File "/account/mkim/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/classify.py", line 163, in place_genomes
    pplacer.run(self.cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out,
  File "/account/mkim/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 154, in run
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: ./output/classify/intermediate_results/pplacer/pplacer.bac120.out
================================================================================

**and here is the pplacer.bac120.out**

Running pplacer v1.1.alpha19-0-g807f6f3 analysis on ./output/align/gtdbtk.bac120.user_msa.fasta...
Didn't find any reference sequences in given alignment file. Using supplied reference alignment.
Pre-masking sequences... sequence length cut from 5040 to 4900.
Determining figs... figs disabled.
Allocating memory for internal nodes... done.
Caching likelihood information on reference tree...

Can you please help me with this error?
Thanks
Minjae

**Comment by dparks1134** [comment]
This is likely a memory issue. GTDB-Tk requires ~100Gb of memory to run. Can you confirm your cluster has access to this amount of memory?

**Comment by minjaekim45** [comment]
Thanks for the quick reply
I increased the memory and it worked.
Thanks!
