### ISSUE TITLE
Exception: An error was encountered while running Prodigal

### ISSUE THREAD

**Issue by Gu2uMo** [Ecogenomics/GTDBTk#229]
Process Process-2:1:1:
Traceback (most recent call last):
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 136, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 309, in __init__
    self.__parseGFF(filename)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 352, in __parseGFF
    start = int(line_split[3])
IndexError: list index out of range
Process Process-2:
Traceback (most recent call last):
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 144, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/lustre/home/acct-ioozy/ioozy/software/anaconda3/envs/python36/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 93, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.

------------------------
here is the command
gtdbtk identify --genome_dir test --out_dir 01_marker_gene -x fna --cpus 1
I run it with my own one MAG, but it failed. But if could process my other MAGs with same  paramater.
could anyone give some help?
Thanks a lot

**Comment by pchaumeil** [comment]
Hello,
Has your input file been modified/opened in a Windows machine and then moved to a Unix server? 
This error can be cause by a Windows return carriage.
Could you please run the command 'dos2unix' (or similar) on your file and run the gtdb-tk command again?

Regards,
Pierre

**Comment by pchaumeil** [comment]
Fixed in 652b8ae015cbdd215925148af4518b3904794a30

**Comment by wangzefei446** [comment]
I have got the same problem,have you solve it?

**Comment by pchaumeil** [comment]
Hi, 
Which version of Tk are you using? Do you get exactly the same error?

**Comment by wangzefei446** [comment]
(gtdbtk-2.0.0) [bgi_cwangzf@mgt02 H1-10]$ gtdbtk classify_wf --genome_dir /share/home/bgi_cwangzf/MAGS/H1-10 --out_dir /share/home/bgi_cwangzf/MAGS/H1-10 --extension fa --prefix bin --cpus 16
[2023-05-17 21:53:02] INFO: GTDB-Tk v2.0.0
[2023-05-17 21:53:02] INFO: gtdbtk classify_wf --genome_dir /share/home/bgi_cwangzf/MAGS/H1-10 --out_dir /share/home/bgi_cwangzf/MAGS/H1-10 --extension fa --prefix bin --cpus 16
[2023-05-17 21:53:02] INFO: Using GTDB-Tk reference data version r207: /share/appspace_data/shared_groups/BGI/02.DataBase/gtdbtk_v2_220806/release207_v2/
[2023-05-17 21:53:02] INFO: Identifying markers in 76 genomes with 16 threads.
[2023-05-17 21:53:02] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/76 genomes (0%) |               | [?genome/s, ETA ?]/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-13:1:1:
Traceback (most recent call last):
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/share/home/bgi_cwangzf/miniconda3/envs/gtdbtk-2.0.0/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by pchaumeil** [comment]
This is probably a numpy error we have had with GTDB-Tk 2.1.
Please have a look at the  issue #459 to solve this problem.
