### ISSUE TITLE
An issue when running classify_wf

### ISSUE THREAD

**Issue by polinanvkv** [Ecogenomics/GTDBTk#238]
Hello all, 

I am running the classify_wf workflow and there's an error when running Prodigal: 

```
Process Process-4:
Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 144, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 93, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
[2020-04-13 20:17:44] ERROR: Controlled exit resulting from an unrecoverable error or warning.


================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 215, in run
    'Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/main.py", line 608, in parse_options
    self.identify(options)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/main.py", line 243, in identify
    options.force)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/markers.py", line 246, in identify
    genome_dictionary = prodigal.run(genomes)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk/lib/python3.6/site-packages/gtdbtk/external/prodigal.py", line 225, in run
    'An exception was caught while running Prodigal.')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal.
```

I tried on both python 3.8 and 3.6, I reinstalled Prodigal separately but this doesn't work. Any ideas?

**Comment by aaronmussig** [comment]
Hello, There are a couple of things we can try for debugging this issue:
1. Which version of GTDB-Tk are you running? (`gtdbtk -v`)
    * If it's < 1.0.2 please update the package and try again.
2. Are you able to provide the input genome(s)?
    * If not, can you try run them on [KBase](https://kbase.us/applist/apps/kb_gtdbtk/run_kb_gtdbtk/release) to see if it's a local issue?

**Comment by polinanvkv** [comment]
Hello Aaron,

Thanks for your swift response! 

1. I just installed it yesterday so must be up-to-date `gtdbtk: version 1.0.2 Copyright 2017 Pierre Chaumeil` 
2. Unfortunately, I cannot sign in for KBase to use the narrative interface, so I already submitted the issue. Nor I can provide the genomes I'm using as they are stored at the institution server. 

The situation is weird as I used the same command a few months ago and everything worked properly.

**Comment by aaronmussig** [comment]
Assuming you have permissions to install conda packages, and to get a better idea of which genome(s) are failing, I've created a dev conda package which has a few extra debug messages.

Install via:
```bash
conda create -n gtdbtk-dev-1.1.0 -c aaronmussig gtdbtk-dev=1.1.0
```

Assuming your paths are the same, update your `GTDBTK_DATA_PATH` configuration via:
```bash
cp /home/users/pnovikova/miniconda3/envs/gtdbtk/etc/conda/activate.d /home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/etc/conda/activate.d
```

Then if you may please run gtdbtk from the `gtdbtk-dev-1.1.0` conda environment with the same command (but use `--cpus 1` and `--debug`).

Once done, may you please share the entire output?

Thanks!

**Comment by polinanvkv** [comment]
Hi Aaron! Thanks for accompanying me with this issue. That's the output I have now:

```
gtdbtk classify_wf --cpus 1 --debug --extension fa --genome_dir /home/users/pnovikov
a/reserach_project/lao/data.new/2011-07-08/mgmt/ --out_dir /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk
[2020-04-15 18:43:03] INFO: GTDB-Tk v1.1.0
[2020-04-15 18:43:03] INFO: gtdbtk classify_wf --cpus 1 --debug --extension fa --genome_dir /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/ --out_dir /home/users
/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk
[2020-04-15 18:43:03] DEBUG: Hardware information:
[2020-04-15 18:43:03] DEBUG:     - Processor: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
[2020-04-15 18:43:03] DEBUG:     - CPU Count: 28
[2020-04-15 18:43:03] DEBUG:     - Memory (GB): 128.82
[2020-04-15 18:43:03] DEBUG:     - Swap (GB): 8.19

[2020-04-15 18:43:03] INFO: Using GTDB-Tk reference data version r89: /scratch/users/pnovikova/tools/gtdbtk/release89/
[2020-04-15 18:43:03] DEBUG: Reading genomes (*.fa) from directory: /home/users/pnovikova/reserach_project/lao/data.new/2011-07-08/mgmt/
[2020-04-15 18:43:03] DEBUG:     - mgmt.assembly.merged.fa
[2020-04-15 18:43:03] INFO: Identifying markers in 1 genomes with 1 threads.
[2020-04-15 18:43:03] DEBUG: Running Prodigal with the following parameters:
[2020-04-15 18:43:03] DEBUG:     - logger: <Logger timestamp (DEBUG)>
[2020-04-15 18:43:03] DEBUG:     - warnings: <Logger warnings (DEBUG)>
[2020-04-15 18:43:03] DEBUG:     - threads: 1
[2020-04-15 18:43:03] DEBUG:     - proteins: False
[2020-04-15 18:43:03] DEBUG:     - marker_gene_dir: /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk/identify/intermediate_results/marker_genes
[2020-04-15 18:43:03] DEBUG:     - protein_file_suffix: _protein.faa
[2020-04-15 18:43:03] DEBUG:     - nt_gene_file_suffix: _protein.fna
[2020-04-15 18:43:03] DEBUG:     - gff_file_suffix: _protein.gff
[2020-04-15 18:43:03] DEBUG:     - force: False
[2020-04-15 18:43:03] DEBUG:     - version: V2.6.3
[2020-04-15 18:43:03] INFO: Running Prodigal V2.6.3 to identify genes.
[2020-04-15 18:43:03] DEBUG: Processing genome: mgmt.assembly.merged
[2020-04-15 18:43:03] DEBUG: Running BiolibProdigal:
[2020-04-15 18:43:03] DEBUG:     - logger: <Logger timestamp (DEBUG)>
[2020-04-15 18:43:03] DEBUG:     - cpus: 1
[2020-04-15 18:43:03] DEBUG:     - verbose: False
[2020-04-15 18:43:03] DEBUG:     - called_genes: False
[2020-04-15 18:43:03] DEBUG:     - translation_table: None
[2020-04-15 18:43:03] DEBUG:     - meta: False
[2020-04-15 18:43:03] DEBUG:     - closed_ends: False
[2020-04-15 18:43:03] DEBUG:     - output_dir: /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk/identify/intermediate_results/marker_genes/mgmt.assembly
.merged
[2020-04-15 18:43:08] DEBUG: Total number of bases: 280924051
[2020-04-15 18:43:09] DEBUG: prodigal -m -p single -q -f gff -g 4 -a /tmp/tmp8uim7pec/4/mgmt.assembly.merged_genes.faa -d /tmp/tmp8uim7pec/4/mgmt.assembly.merged_genes.fna -i /tmp/tm
p8uim7pec/mgmt.assembly.merged.fa > /tmp/tmp8uim7pec/4/mgmt.assembly.merged.gff 2> /dev/null




[2020-04-15 18:48:14] DEBUG: prodigal -m -p single -q -f gff -g 11 -a /tmp/tmp8uim7pec/11/mgmt.assembly.merged_genes.faa -d /tmp/tmp8uim7pec/11/mgmt.assembly.merged_genes.fna -i /tmp
/tmp8uim7pec/mgmt.assembly.merged.fa > /tmp/tmp8uim7pec/11/mgmt.assembly.merged.gff 2> /dev/null
[2020-04-15 18:48:22] DEBUG: Results: None
Process Process-2:
Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 156, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 98, in _run_prodigal
    raise Exception(
Exception: An error was encountered while running Prodigal.

[2020-04-15 18:48:22] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 227, in run
    raise ProdigalException(
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/bin/gtdbtk", line 496, in <module>
    gt_parser.parse_options(args)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 652, in parse_options
    self.identify(options)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 259, in identify
    markers.identify(genomes,
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 146, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 237, in run
    raise ProdigalException(
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal.
================================================================================
```

**Comment by polinanvkv** [comment]
Aaron, I just realised I've been using gtdbtk in the wrong way. I confused the folder with the assembly and the mags. When I changed the input folder to the mags folder, it still worked with errors: 
```
[2020-04-15 19:42:11] INFO: Placing 21 bacterial genomes into reference tree with pplacer using 1 cpus (be patient).
[2020-04-15 19:42:11] DEBUG: pplacer -m WAG -j 1 -c /scratch/users/pnovikova/tools/gtdbtk/release89/pplacer/gtdb_r89_bac120.refpkg -o /home/users/pnovikova/reserach_project/lao/analy
sis/taxonomy/2011-07-08/gtdbtk/dastool/classify/intermediate_results/pplacer/pplacer.bac120.json /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk/dastoo
l/align/gtdbtk.bac120.user_msa.fasta
Initialising pplacer [Didn't find any reference sequences in given align]
Initialising pplacer [        Determining figs... figs disabled.        ]
Initialising pplacer [Caching likelihood information on reference tree..]

[2020-04-15 19:45:47] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException

  MESSAGE: An error was encountered while running pplacer, check the log file: /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk/dastool/classify/interme
diate_results/pplacer/pplacer.bac120.out
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/bin/gtdbtk", line 496, in <module>
    gt_parser.parse_options(args)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 670, in parse_options
    self.classify(options)
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 430, in classify
    classify.run(genomes,
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/classify.py", line 351, in run
    classify_tree = self.place_genomes(user_msa_file,
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/classify.py", line 168, in place_genomes
    pplacer.run(self.pplacer_cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out,
  File "/home/users/pnovikova/miniconda3/envs/gtdbtk-dev-1.1.0/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 154, in run
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: /home/users/pnovikova/reserach_project/lao/analysis/taxonomy/2011-07-08/gtdbtk
/dastool/classify/intermediate_results/pplacer/pplacer.bac120.out
================================================================================ 
```

**Comment by aaronmussig** [comment]
Hello, that's good news. I will try to catch that error in a future release.

Unfortunately, the pplacer error you've encountered is a relatively common one caused by insufficient memory. The `caching likelihood information` step of pplacer loads ~113GB into memory and if it isn't able you get the above error message.

From your debug log it shows you have ~128GB of memory so you should be fine to run it, perhaps something else was running on the server at the same time which was hogging >10GB? Also from the debug log, it shows your swap space is ~8GB so there's little room for any spillover.

There is a flag called `--scratch_dir` which you can use with pplacer to write the cache to disk instead of memory. An alternative is to use that flag and point it to a disk which has >115GB.

Moving forward I'd try run it again when there's nothing else happening on the server while monitoring the memory usage. If that fails the `--scratch_dir` flag may help.
