### ISSUE TITLE
Error in Pplacer step, classify_wf

### ISSUE THREAD

**Issue by suryatri1** [Ecogenomics/GTDBTk#239]
I installed gtdbtk using conda environement while manually downloading gtdbtk database and giving pathname and the installation looks good. However when I run classify_wf, it always gets stuck at pplacer step, I have tried with single and multiple mags with single 1, 16, 64 cpu threads and it just doesn't seem to work, my mags are raw fasta files. 

pplacer.bac120.out gives this error:

Didn't find any reference sequences in given alignment file. Using supplied reference al$
Pre-masking sequences... sequence length cut from 5040 to 4980.
Determining figs... figs disabled.
Allocating memory for internal nodes... done.
Caching likelihood information on reference tree...

Would really appreciate your help.

**Comment by aaronmussig** [comment]
Hello,

The pplacer error you've encountered is a relatively common one caused by insufficient memory. The caching likelihood information step of pplacer loads ~113GB into memory and if it isn't able you get the above error message.

Do you have at least 113 GB of memory on the server you're running, if so, is anything else running at the time and have you monitored the free memory available?

There is a flag called --scratch_dir which you can use with pplacer to write the cache to disk instead of memory. An alternative is to use that flag and point it to a disk which has >115GB.

Moving forward I'd try run it again when there's nothing else happening on the server while monitoring the memory usage. If that fails the --scratch_dir flag may help.

**Comment by suryatri1** [comment]
Thanks Aaron! The server I am using has ~100GB free memory so that might be the issue, I will do as you suggested.

**Comment by suryatri1** [comment]
I tried on 3 genomes with the flag --scratch_dir and made it point to disk in server (has TBs of disk space) but got another pplacer error.

gtdbtk classify_wf --genome_dir Nayfach_Oscillo/ --extension .gz --out_dir gtdbtk_output/ --scrat
ch_dir junk/ --cpu 1 --debug
[2020-04-15 23:47:00] INFO: GTDB-Tk v1.1.0
[2020-04-15 23:47:00] INFO: gtdbtk classify_wf --genome_dir Nayfach_Oscillo/ --extension .gz --out_dir gtdbtk_output/ --scratch_dir junk/ --cpu 1 --debug
[2020-04-15 23:47:00] INFO: Using GTDB-Tk reference data version r89: /home/suryatri/user_data/software/gtdbtk_dataset/release89/
[2020-04-15 23:47:00] INFO: Identifying markers in 3 genomes with 1 threads.
[2020-04-15 23:47:00] INFO: Running Prodigal V2.6.3 to identify genes.
==> Finished processing 3 of 3 (100.0%) genomes.
[2020-04-15 23:47:19] INFO: Identifying TIGRFAM protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
[2020-04-15 23:47:37] INFO: Identifying Pfam protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
[2020-04-15 23:47:40] INFO: Annotations done using HMMER 3.1b2 (February 2015)
[2020-04-15 23:47:40] INFO: Done.
[2020-04-15 23:47:40] INFO: Aligning markers in 3 genomes with 1 threads.
[2020-04-15 23:47:40] INFO: Processing 3 genomes identified as bacterial.
[2020-04-15 23:47:41] INFO: Read concatenated alignment for 23458 GTDB genomes.
==> Finished aligning 3 of 3 (100.0%) genomes.
[2020-04-15 23:48:05] DEBUG: Successfully written all markers to: gtdbtk_output/align/intermediate_results/markers
[2020-04-15 23:48:05] INFO: Masking columns of multiple sequence alignment using canonical mask.
[2020-04-15 23:48:32] INFO: Masked alignment from 41155 to 5040 AAs.
[2020-04-15 23:48:32] INFO: 0 user genomes have amino acids in <10.0% of columns in filtered MSA.
[2020-04-15 23:48:32] INFO: Creating concatenated alignment for 23461 GTDB and user genomes.
[2020-04-15 23:48:32] INFO: Creating concatenated alignment for 3 user genomes.
[2020-04-15 23:48:32] INFO: Done.
[2020-04-15 23:48:32] INFO: Using a scratch file for pplacer allocations. This decreases memory usage and performance.
[2020-04-15 23:48:32] INFO: Placing 3 bacterial genomes into reference tree with pplacer using 1 cpus (be patient).
[2020-04-15 23:48:32] DEBUG: pplacer -m WAG -j 1 -c /home/suryatri/user_data/software/gtdbtk_dataset/release89/pplacer/gtdb_r89_bac120.refpkg -o gtdbtk_output/classify/intermediate_results/pplacer/pplacer.bac120.json gtdbtk_output/align/gtdbtk.bac120.user_msa.fasta --mmap-file  --mmap-file junk/gtdbtk.pplacer.scratch
Initialising pplacer [Pre-masking sequences... sequence length cut from ]pplacer: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Initialising pplacer [     Allocating memory for internal nodes...      ]

[2020-04-15 23:49:01] ERROR: Controlled exit resulting from an unrecoverable error or warning.
================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer, check the log file: gtdbtk_output/classify/intermediate_results/pplacer/pplacer.bac120.out
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/suryatri/miniconda3/envs/gtdbtk/bin/gtdbtk", line 492, in <module>
    gt_parser.parse_options(args)
  File "/home/suryatri/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 666, in parse_options
    self.classify(options)
  File "/home/suryatri/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 426, in classify
    classify.run(genomes,
  File "/home/suryatri/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/classify.py", line 351, in run
    classify_tree = self.place_genomes(user_msa_file,
  File "/home/suryatri/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/classify.py", line 168, in place_genomes
    pplacer.run(self.pplacer_cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out,
  File "/home/suryatri/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 154, in run
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: gtdbtk_output/classify/intermediate_results/pplacer/pplacer.bac120.out
