### ISSUE TITLE
IndexError with FastANI

### ISSUE THREAD

**Issue by johanneswerner** [Ecogenomics/GtdbTk#24]
Hi, 

currently all my samples are failing and I am getting the same error for all samples. 

```bash
[2018-07-26 18:13:03] INFO: Calculating Average Nucleotide Identity using FastANI.
list index out of range
Process Process-111:
Traceback (most recent call last):
  File "/data/miniconda3/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/data/miniconda3/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/miniconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 389, in _fastaniWorker
    dict_parser_distance = self._calculate_fastani_distance(items, genomes)
  File "/data/miniconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 618, in _calculate_fastani_distance
    dict_parser_distance = self._parse_fastani_results(os.path.join(self.tmp_output_dir,'results.tab'),list_leaf)
  File "/data/miniconda3/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/classify.py", line 648, in _parse_fastani_results
    ref_genome = os.path.basename(info[1]).replace(Config.FASTANI_GENOMES_EXT,"")
IndexError: list index out of range
GTDB-Tk has stopped before finishing
```

I looked into the fastANI result file and for some reason the files are empty: 

```bash
$ cat gtdbtk_BS090.bac120.fastani_results.tsv 
User genome     Reference genome        ANI
```

Do you have any idea where this error can come from?

**Comment by johanneswerner** [comment]
sorry, i forgot, this is how I call the program: 

```bash
/data/miniconda3/envs/gtdbtk/bin/gtdbtk classify_wf --cpus 26 --genome_dir /data/binning/${SAMPLE}/ --out_dir /data/binning/${SAMPLE}/gtdbtk_${SAMPLE} --prefix sample_${SAMPLE} --extension fasta --debug
```

**Comment by johanneswerner** [comment]
this is from `classify.py`

```python
    def _parse_fastani_results(self,fastout_file,list_leaf):
        """ Parse the fastani output file
        
        
        Parameters
        ----------
        fastout_file : fastani output file.
    
        Returns
        -------
        dictionary
            dict_results[user_g]={"ref_genome":ref_genome,"ani":ani}
        """
        dict_results = {}
        with open(fastout_file) as fastfile:
            for line in fastfile:
                info = line.strip().split(" ")
                ref_genome = os.path.basename(info[1]).replace(Config.FASTANI_GENOMES_EXT,"")
                user_g = remove_extension(os.path.basename(info[0]))
                ani = float(info[2])
                if user_g in dict_results:
                    print "it should not happen! (if user_g in dict_results)"
                else:
                    dict_results[user_g]={"ref_genome":ref_genome,"ani":ani}

        return dict_results
```

I printed info and it seems like the split command has a bug: 

```
['/data/binning/4/4_maxbin.007.fasta\t/data/gtdbtk_db/release83/fastani/database/GCF_900098805.1_genomic.fna\t98.4274\t913\t1071']
```

**Comment by johanneswerner** [comment]
Hi Pierre, 
ah okay, that is where the problem might arise from. 

```bash
$ gtdbtk --version
gtdbtk: version 0.0.7 Copyright 2017 Pierre Chaumeil
```

This is the current version in bioconda.

**Comment by pchaumeil** [comment]
Hi Johannes,
I am not sure why the split by spaces does not work in you environment. 
I just ran gtdbtk on my machine and it worked fine with spaces.
For your information, A new version of GTDB-Tk using the NCBI release 86 is about to be released in the coming days and I will modify the function to split on both spaces and tabs.

Thanks,
Pierre

**Comment by johanneswerner** [comment]
Hi Pierre, 
thank you for the information. That is very helpful. Could you notify me when the new version will be released?
Kind regards
Johannes

**Comment by pchaumeil** [comment]
Hi Johannes,
No problem, we will send you a notification!

Regards,
Pierre

**Comment by pchaumeil** [comment]
Hello Johannes,

The new version of GTDB-Tk (based on R86) is now available through Github and Pip.

Regards,
Pierre

**Comment by johanneswerner** [comment]
That is wonderful, thank you very much. :-)
