### ISSUE TITLE
issue with running fastANI with gtdbtk v1.1.1

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#251]
I am getting the following error:

```
[2020-05-11 17:26:35] ^[[1mINFO:^[[0m Calculating average nucleotide identity using FastANI.
[2020-05-11 17:27:01] ^[[1mINFO:^[[0m fastANI version: unknown (<1.3)
Process Process-40:
Traceback (most recent call last):
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 207, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 279, in run_proc
    return self._parse_output_file(output)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 298, in _parse_outpu\
t_file
    path_qry, path_ref, ani, frac1, frac2 = line.strip().split('\t')
ValueError: not enough values to unpack (expected 5, got 1)
Process Process-42:
Traceback (most recent call last):
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 207, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 279, in run_proc
    return self._parse_output_file(output)
  File "/nfs/vedanta/sw/packages/miniconda3/lib/python3.7/site-packages/gtdbtk/external/fastani.py", line 298, in _parse_outpu\
t_file
    path_qry, path_ref, ani, frac1, frac2 = line.strip().split('\t')
ValueError: not enough values to unpack (expected 5, got 1)

[2020-05-11 17:27:04] ^[[1;31mERROR:^[[0m FastANI returned a non-zero exit code.
[2020-05-11 17:27:04] ^[[1;31mERROR:^[[0m Controlled exit resulting from an unrecoverable error or warning.
```

Also, I noticed a similar problem when trying to run the new feature ani_rep.  I posted the error messages I was seeing when running ani_rep in issue #191 , which I believe are essentially the same error messages.

**Comment by aaronmussig** [comment]
At a glance, the FastANI output is being parsed incorrectly. I'll do some testing to try and replicate this error. If possible can you please share the smallest subset of genome(s) you're encountering this error with so I can use it to validate the error is fixed, thanks.

**Comment by cheberling** [comment]
The smallest number of genomes I've encountered this with is 37 genomes, but I cannot share them due to proprietary reasons.  I don't think the problem involves the genomes themselves, as fastANI couldn't even start processing this set.  When I had tried running the new ani_rep command to query ~3000 user genomes against the GTDB rep genomes (or a subset of ~150 query genomes), fastANI actually did start running properly, as it showed the first few pair-wise comparisons out of over a million queued, and then crashed due to the same error I pasted above.

Might it have to do with the switch to python3?

**Comment by aaronmussig** [comment]
That's alright. Once I've got some code that I think will fix the problem I might ask you to run a development branch on the problem genomes to see if it resolves the issue. I'll get back to you.

Specifically, this problem is to do with parsing the FastANI output file so I assume it's a case that wasn't considered, possibly caused by a specific version of FastANI.

**Comment by aaronmussig** [comment]
I assume you're running FastANI version 1.0 which spaced items in the output file using spaces, whereas version >=1.1 uses tabs. If you update FastANI this error will be resolved and I'll put check in place for a future release.

**Comment by cheberling** [comment]
That's strange, many of my more recent runs of fastANI had outputs with tab delimiters, but my most recent run today had space delimiters.  I'm wondering if I have two installations of fastANI, and gtdbtk v1.1.1 is referencing the old installation?  I ran my older gtdbtk version today (0.3.2) without any issues in my python2 conda environment.  When I looked at fastANI's github page today, I couldn't find anything regarding version updates, and there doesn't seem to be any way to check the version with the software itself.

**Comment by aaronmussig** [comment]
Hard to say how your environment is configured but GTDB-Tk will be using whichever fastANI is on the system path. The most recent bioconda recipe will require fastANI >=1.2 so maybe there is another fastANI on the path.

FastANI's changelog isn't particularly verbose but from what I can see the releases page is the best spot to view it. Only from version FastANI v1.3 can you check the version, otherwise you can compare the checksum against the releases page (if you used the pre-compiled binary).

**Comment by cheberling** [comment]
I upgraded to fastANI v1.3, and I'm trying gtdbtk classify_wf and ani_rep on 37 genomes again.  I'll let you know tomorrow how it goes.

**Comment by cheberling** [comment]
Looks to be working now.  Thanks!
