### ISSUE TITLE
alignment length is not equal to length of markergenes. Is the list custom generated?

### ISSUE THREAD

**Issue by Jigyasa3** [Ecogenomics/GTDBTk#261]
Hey all!

I am trying to trim my msa file of 43 marker genes from MAGs. The marker genes were obtained from CheckM, aligned by Mafft local alignment, and a concatenated sequence file was generated via "fasconcat.pl". 

I am running the "trim_msa.py" python script (which is saved as "gtdb_trim.py"). But I keep getting the following error.

Code-
`python3 ${IN_DIR}/gtdk_trim.py --msa mybins_proteins_smatrix.fasta --marker_list gtdbtk.ar122.marker_info.tsv --out_dir gtdb_mybins`

Error-
`trim_msa.py v0.0.4: Randomly select a subset of columns from the MSA of each marker.
  by Pierre Chaumeil and Donovan Parks (p.chaumeil@uq.edu.au)

[2020-06-22 16:45:19] INFO: trim_msa v0.0.4
[2020-06-22 16:45:19] INFO: gtdk_trim.py --msa mybins_proteins_smatrix.fasta --marker_list gtdbtk.ar122.marker_info.tsv --out_dir gtdb_mybins
[2020-06-22 16:45:19] INFO: Reading multiple sequence alignment.
[2020-06-22 16:45:23] INFO: Read MSA for 17209 genomes.
[2020-06-22 16:45:23] INFO: Reading marker info.
[2020-06-22 16:45:23] ERROR: Length of MSA (98834 columns) does not equal length of marker genes (32675 columns).

Unexpected error: <class 'gtdbtk.exceptions.MSAMarkerLengthMismatch'>
Traceback (most recent call last):
  File "/bucket/BourguignonU/Jigs_backup/working_files/AIMS/AIM1/old_stuff/scripts/gtdk_trim.py", line 311, in <module>
    p.run(args.msa, args.marker_list)
  File "/bucket/BourguignonU/Jigs_backup/working_files/AIMS/AIM1/old_stuff/scripts/gtdk_trim.py", line 89, in run
    filtered_seqs, pruned_seqs = self.trim(msa, marker_list)
  File "/bucket/BourguignonU/Jigs_backup/working_files/AIMS/AIM1/old_stuff/scripts/gtdk_trim.py", line 136, in trim
    raise MSAMarkerLengthMismatch
gtdbtk.exceptions.MSAMarkerLengthMismatch`

Any suggestions? I am aligning commonly used marker genes. Do I need to generate my own list of marker gene info? I tried both bacterial and archaeal gtdb tsv files available on GTDBTk github page.

Looking forward to your reply!

**Comment by dparks1134** [comment]
Hi. The `trim_msa.py` script cannot handle arbitrary marker gene sets. It is designed to work with the GTDB-Tk bacterial and archaeal marker sets.

**Comment by Jigyasa3** [comment]
thank you!
