### ISSUE TITLE
error message when use gtdbtk align command

### ISSUE THREAD

**Issue by zyyalice** [Ecogenomics/GTDBTk#263]
Hi

I got a error message when i use gtdbtk align command. The detail as follow:

 gtdbtk align --identify_dir identify_out/ --out_dir 2 --cpus 42
[2020-07-02 22:44:34] INFO: GTDB-Tk v1.2.0
[2020-07-02 22:44:34] INFO: gtdbtk align --identify_dir identify_out/ --out_dir 2 --cpus 42
[2020-07-02 22:44:34] INFO: Using GTDB-Tk reference data version r89: /media/HD1/database/release89
[2020-07-02 22:44:34] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: AttributeError
  MESSAGE: 'Namespace' object has no attribute 'debug'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/emma/anaconda2/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/home/emma/anaconda2/envs/gtdbtk-dev-1.2.0_2/lib/python3.8/site-packages/gtdbtk/main.py", line 761, in parse_options
    self.align(options)
  File "/home/emma/anaconda2/envs/gtdbtk-dev-1.2.0_2/lib/python3.8/site-packages/gtdbtk/main.py", line 332, in align
    markers = Markers(options.cpus, options.debug)
AttributeError: 'Namespace' object has no attribute 'debug'

Could you help me?

Thank you very much!
Alice

**Comment by aaronmussig** [comment]
Hello,

You should be able to specify `--debug` when you run the align command and it will be the same with some additional information generated. 

In a future release, it will be explicitly set. However, given that this variable is set to false by default, I strongly recommend [re-creating your conda environment](https://docs.anaconda.com/anaconda/install/uninstall/) (there could be other issues which are not apparent, as this issue is similar to #255).

**Comment by zyyalice** [comment]
Hi

Thank you very much for your reply.  But I still don't understand the meaning of recreating the conda environment. Does this mean that I need to uninstall the existing Conda and then reinstall it? I look forward to your guidance.

Thank you!

**Comment by aaronmussig** [comment]
Hello,

Yes, I would follow the installation instructions for installing miniconda3 into a new different directory, then using that conda environment (check via `which conda`) to install and run GTDB-Tk.
