### ISSUE TITLE
error in "variable row[]: isn't properly declared"

### ISSUE THREAD

**Issue by spongebob22** [Ecogenomics/GtdbTk#27]
Hi,

I have installed all the prerequisite packages and softwares and then used pip to install the tgdbtk. But while I run gtdbtk, it errors after Identifying Pfam protein families:

Any ideas what is wrong?

Thanks
-----------------------------------------------------------------------------------------------------------------------
gtdbtk classify_wf --cpus 2 --genome_dir /mnt/nfs/sharknado/gtdbtk_bin_analysis/gtdbtk_input/ --out_dir /mnt/nfs/sharknado/gtdbtk_bin_analysis/gtdbtk_output/ --debug
[2018-07-31 15:51:05] INFO: GTDB-Tk v0.0.7
[2018-07-31 15:51:05] INFO: gtdbtk classify_wf --cpus 2 --genome_dir /mnt/nfs/sharknado/gtdbtk_bin_analysis/gtdbtk_input/ --out_dir /mnt/nfs/sharknado/gtdbtk_bin_analysis/gtdbtk_output/ --debug
[2018-07-31 15:51:05] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2018-07-31 15:51:05] INFO: Identifying markers in 9 genomes with 2 threads.
[2018-07-31 15:51:05] INFO: Running Prodigal to identify genes.
==> Finished processing 9 of 9 (100.0%) genomes.
[2018-07-31 15:51:34] INFO: Identifying TIGRFAM protein families.
==> Finished processing 9 of 9 (100.0%) genomes.
[2018-07-31 15:51:56] INFO: Identifying Pfam protein families.
==> Finished processing 9 of 9 (100.0%) genomes.
[2018-07-31 15:52:02] INFO: Done.
[2018-07-31 15:52:02] INFO: Aligning markers in 9 genomes with 2 threads.
('Unexpected error:', <type 'exceptions.UnboundLocalError'>)
Traceback (most recent call last):
  File "/usr/bin/gtdbtk", line 328, in <module>
    gt_parser.parse_options(args)
  File "/usr/lib/python2.7/site-packages/gtdbtk/main.py", line 295, in parse_options
    self.align(options)
  File "/usr/lib/python2.7/site-packages/gtdbtk/main.py", line 173, in align
    options.outgroup_taxon)
  File "/usr/lib/python2.7/site-packages/gtdbtk/markers.py", line 380, in align
    gtdb_taxonomy = Taxonomy().read(self.taxonomy_file)
  File "/usr/lib/python2.7/site-packages/biolib/taxonomy.py", line 804, in read
    self.logger.error('Failed to parse taxonomy file on line %d' % (row+1))
UnboundLocalError: local variable 'row' referenced before assignment

**Comment by pchaumeil** [comment]
Hi spongebob22,
It looks like the gtdbtk sofware is unable to access the taxonomy file to parse it.
Please make sure the config file points to it and the path is properly declared.

Regards,
Pierre

**Comment by spongebob22** [comment]
turns out i the config file was correctly configured. But the download had failed.  I re-did that and everything appears to be running now!  thanks

**Comment by waoverholt** [comment]
I just had this same issue. It was because the PATH specified in the config.py file used an environment variable (e.g. $HOME/data/databases/gtdbtk).

Probably a low priority, but the error message was unhelpful at figuring out what was going wrong (at least I thought so).

**Comment by ahnishida** [comment]
Hi all, 
I'm also having a similar issue. When I run gtdbtk test I get the following error. I've tried uninstalling and reinstalling the software. I also tried to look at the output.py file to see if there is an issue designating the correct path, but I am unsure of what to change. The identify command works fine, it breaks when it gets to align. 

Any help would be appreciated. Thanks. 


(py2) an25562@ochmcomp01:~$ gtdbtk test --out_dir test1
[2019-10-07 11:33:29] INFO: GTDB-Tk v0.3.2
[2019-10-07 11:33:29] INFO: gtdbtk test --out_dir test1
[2019-10-07 11:33:29] INFO: Using GTDB-Tk reference data version r89: projects/SGB/gtdbtk/gtdbtk_database
[2019-10-07 11:33:29] INFO: Command: gtdbtk classify_wf --genome_dir test1/genomes --out_dir test1/output --cpus 1
[2019-10-07 11:34:18] ERROR: The test returned a non-zero exit code.
[2019-10-07 11:34:18] ERROR: A detailed summary of the execution log can be found here: test1/test_execution.log
[2019-10-07 11:34:18] ERROR: The test has failed.
[2019-10-07 11:34:18] ERROR: Controlled exit resulting from early termination.
(py2) an25562@ochmcomp01:~$ cat test1/test_execution.log
[2019-10-07 11:33:30] INFO: GTDB-Tk v0.3.2
[2019-10-07 11:33:30] INFO: gtdbtk classify_wf --genome_dir test1/genomes --out_dir test1/output --cpus 1
[2019-10-07 11:33:30] INFO: Using GTDB-Tk reference data version r89: projects/SGB/gtdbtk/gtdbtk_database
[2019-10-07 11:33:30] INFO: Identifying markers in 3 genomes with 1 threads.
[2019-10-07 11:33:30] INFO: Running Prodigal to identify genes.
==> Finished processing 3 of 3 (100.0%) genomes.
[2019-10-07 11:34:00] INFO: Identifying TIGRFAM protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
[2019-10-07 11:34:16] INFO: Identifying Pfam protein families.
==> Finished processing 3 of 3 (100.0%) genomes.
[2019-10-07 11:34:18] INFO: Done.
[2019-10-07 11:34:18] INFO: Aligning markers in 3 genomes with 1 threads.
[2019-10-07 11:34:18] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: UnboundLocalError
  MESSAGE: local variable 'row' referenced before assignment
________________________________________________________________________________

Traceback (most recent call last):
  File "/stor/home/an25562/miniconda3/envs/py2/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/stor/home/an25562/miniconda3/envs/py2/lib/python2.7/site-packages/gtdbtk/main.py", line 600, in parse_options
    self.align(options)
  File "/stor/home/an25562/miniconda3/envs/py2/lib/python2.7/site-packages/gtdbtk/main.py", line 252, in align
    options.outgroup_taxon)
  File "/stor/home/an25562/miniconda3/envs/py2/lib/python2.7/site-packages/gtdbtk/markers.py", line 464, in align
    gtdb_taxonomy = Taxonomy().read(self.taxonomy_file)
  File "/stor/home/an25562/miniconda3/envs/py2/lib/python2.7/site-packages/gtdbtk/biolib_lite/taxonomy.py", line 821, in read
    'Failed to parse taxonomy file on line %d' % (row + 1))
UnboundLocalError: local variable 'row' referenced before assignment
