### ISSUE TITLE
gtdbtk classify_wf error with Prodigal & possibly input file format error?

### ISSUE THREAD

**Issue by brookeweigel** [Ecogenomics/GTDBTk#274]
## Environment
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
gtdbtk                    0.3.2                    py27_1    bioconda

## Server information
Running on the University of Chicago's Midway2 server.
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name	: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz 56
- RAM: `grep "^MemTotal" /proc/meminfo`
263307568 kB
- OS: `cat /etc/os-release`

Here is my check_install for gtdbtk (all is good):
[2020-09-09 12:20:31] INFO: gtdbtk check_install
[2020-09-09 12:20:31] INFO: Using GTDB-Tk reference data version r95: /project2/cpfister/genome_taxonomy_database/release95/
[2020-09-09 12:20:31] INFO: Running install verification
[2020-09-09 12:20:31] INFO: Check file Taxonomy (/project2/cpfister/genome_taxonomy_database/release95/taxonomy/gtdb_taxonomy.tsv): OK
[2020-09-09 12:20:31] INFO: Check file concat_bac120 (/project2/cpfister/genome_taxonomy_database/release95/msa/gtdb_r95_bac120.faa): OK
[2020-09-09 12:20:31] INFO: Check file concat_ar122 (/project2/cpfister/genome_taxonomy_database/release95/msa/gtdb_r95_ar122.faa): OK
[2020-09-09 12:20:31] INFO: Check file mask_bac120 (/project2/cpfister/genome_taxonomy_database/release95/masks/gtdb_r95_bac120.mask): OK
[2020-09-09 12:20:31] INFO: Check file mask_ar122 (/project2/cpfister/genome_taxonomy_database/release95/masks/gtdb_r95_ar122.mask): OK
[2020-09-09 12:20:31] INFO: Check file tirgfam_hmms (/project2/cpfister/genome_taxonomy_database/release95/markers/tigrfam/tigrfam.hmm): OK
[2020-09-09 12:20:31] INFO: Check file pfam_hmms (/project2/cpfister/genome_taxonomy_database/release95/markers/pfam/Pfam-A.hmm): OK
[2020-09-09 12:20:31] INFO: Check folder fastani_genomes (/project2/cpfister/genome_taxonomy_database/release95/fastani/database/): OK
[2020-09-09 12:20:31] INFO: Check folder pplacer_bac120 (/project2/cpfister/genome_taxonomy_database/release95/pplacer/gtdb_r95_bac120.refpkg): OK
[2020-09-09 12:20:31] INFO: Check folder pplacer_ar122 (/project2/cpfister/genome_taxonomy_database/release95/pplacer/gtdb_r95_ar122.refpkg): OK
[2020-09-09 12:20:31] INFO: Done.

## Here is the code that I am trying to run
$ gtdbtk classify_wf --cpus 13 --batchfile Nereo_MAG_paths.txt --out_dir gtdbtk_output

## Here are a few lines of the batchfile:
g1_MAG_00002	10_BINNING_SUMMARY/g1_MAGs_final/bin_by_bin/g1_MAG_00002/g1_MAG_00002-contigs.fa
g1_MAG_00003	10_BINNING_SUMMARY/g1_MAGs_final/bin_by_bin/g1_MAG_00003/g1_MAG_00003-contigs.fa
g1_MAG_00004	10_BINNING_SUMMARY/g1_MAGs_final/bin_by_bin/g1_MAG_00004/g1_MAG_00004-contigs.fa

## A few times in the error message, it says:
InputFileError: Input file g2_MAG_00013 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)

** Does this mean that my files are not in the right format? These are contigs.fa files, created in anvio, of individual MAGs, with the correct file paths. I don't know what could be wrong here, unless .fasta is needed rather than .fa

** Or, maybe there is some other error with Prodial. I am doing this as a test run on the server and I haven't submitted it as a batch script yet, which I will do once the test script is working. Any help would be wonderful! :) Thank you.

## Here is the full output error from Prodigal:
[2020-09-09 12:31:48] INFO: GTDB-Tk v0.3.2
[2020-09-09 12:31:48] INFO: gtdbtk classify_wf --cpus 13 --batchfile Nereo_MAG_paths.txt --out_dir gtdbtk_output
[2020-09-09 12:31:48] INFO: Using GTDB-Tk reference data version r95: /project2/cpfister/genome_taxonomy_database/release95/
[2020-09-09 12:31:48] INFO: Identifying markers in 84 genomes with 13 threads.
[2020-09-09 12:31:48] INFO: Running Prodigal to identify genes.
Process Process-3:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-5:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-4:1:1:
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
Traceback (most recent call last):
Process Process-2:1:1:
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    rtn = producer_callback(dataItem)
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
Process Process-7:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-6:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
Process Process-12:1:1:
Traceback (most recent call last):
Process Process-9:1:1:
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
Process Process-10:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
Process Process-11:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Process Process-8:1:1:
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
Process Process-13:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
Process Process-14:1:1:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/parallel.py", line 109, in __producer
    rtn = producer_callback(dataItem)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 81, in _producer
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
    seqs = read_fasta(genome_file)
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
    seqs = read_fasta(genome_file)
    seqs = read_fasta(genome_file)
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
    seqs = read_fasta(genome_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/biolib_lite/seq_io.py", line 57, in read_fasta
InputFileError: Input file g2_MAG_00013 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)
InputFileError: Input file g2_MAG_00037 does not exist.
InputFileError: Input file g3_MAG_00020 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
InputFileError: Input file g1_MAG_00012 does not exist.
InputFileError: Input file g3_MAG_00014 does not exist.
InputFileError: Input file g2_MAG_00036 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
    raise InputFileError('Input file %s does not exist.' % fasta_file)
InputFileError: Input file g2_MAG_00027 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)
InputFileError: Input file g2_Bin_00040 does not exist.
InputFileError: Input file g2_MAG_00029 does not exist.
InputFileError: Input file g4_MAG_00003 does not exist.
InputFileError: Input file g3_MAG_00011 does not exist.
InputFileError: Input file g2_MAG_00023 does not exist.
    raise InputFileError('Input file %s does not exist.' % fasta_file)
InputFileError: Input file g3_MAG_00023 does not exist.
Process Process-2:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
Process Process-6:
Process Process-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-13:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
Exception: An error was encountered while running Prodigal.
Process Process-5:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
[2020-09-09 12:31:48] ERROR: Prodigal returned a non-zero exit code.
Process Process-14:
Traceback (most recent call last):
Process Process-12:
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-11:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
Exception: An error was encountered while running Prodigal.
    "An error was encountered while running Prodigal.")
    rtn_files = self._run_prodigal(genome_id, file_path)
Exception: An error was encountered while running Prodigal.
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
Process Process-7:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
Process Process-3:
Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-10:
Traceback (most recent call last):
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process Process-9:
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
Process Process-8:
    self.run()
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    self._target(*self._args, **self._kwargs)
    "An error was encountered while running Prodigal.")
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
Exception: An error was encountered while running Prodigal.
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
    self.run()
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/multiprocessing/process.py", line 114, in run
    "An error was encountered while running Prodigal.")
    self._target(*self._args, **self._kwargs)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 122, in _worker
Exception: An error was encountered while running Prodigal.
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 76, in _run_prodigal
    "An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
[2020-09-09 12:31:48] ERROR: An exception was caught while running Prodigal.
[2020-09-09 12:31:48] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: 
________________________________________________________________________________

Traceback (most recent call last):
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 586, in parse_options
    self.identify(options)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/main.py", line 219, in identify
    options.force)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/markers.py", line 238, in identify
    genome_dictionary = prodigal.run(genomes)
  File "/software/python-anaconda-2020.02-el7-x86_64/envs/gtdbtk/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 203, in run
    raise ProdigalException
ProdigalException
================================================================================

**Comment by brookeweigel** [comment]
Update: @watsonar solved this issue! She said: "My batchfile that worked successfully is formatted with the path in the first column and the MAG name in the second column," but I had the MAG name in the first column and the path in the second. Once I switched the order, IT WORKED! :)
