### ISSUE TITLE
 Pfam Error

### ISSUE THREAD

**Issue by yuboer** [Ecogenomics/GTDBTk#28]
Hi,

The -GENERIC_PATH variable was changed to the absolute path of the directory containing the data downloaded from the https://data.ace.uq.edu.au/public/gtdbtk/ with this command:
 (GENERIC_PATH = "/projects/b1052/pythonenvs/python2.7/GTDB/gtdb_database/release83/")
while it error message in the log file suggested that the path was not read properly and pfam database could not be reached properly

"   summary_stats = summary_stats[summary_stats.keys()[0]]
AttributeError: 'NoneType' object has no attribute 'keys'

Error: File existence/permissions problem in trying to open HMM file /PATH/To/GtdbTK/data/markers/tigrfam/tigrfam.hmm.
HMM file /PATH/To/GtdbTK/data/markers/tigrfam/tigrfam.hmm not found (nor an .h3m binary of it); "

The path in the error above should be "/projects/b1052/pythonenvs/python2.7/GTDB/gtdb_database/release83/", instead of "/PATH/To/GtdbTK/data/"

Thanks!

**Comment by pchaumeil** [comment]
Hello,

Thanks for your message!
" /PATH/To/GtdbTK/data/ " is actually a generic path that people need to modify to fit their server configuration. 

in your example it has to be replaced with "/projects/b1052/pythonenvs/python2.7/GTDB/gtdb_database/release83/" but that does not mean that another user will have the data at the exact same location on their server.

Thanks,
Pierre

**Comment by yuboer** [comment]
Thanks, Pierre! But i still do not understand how i may solve the error i have come across, i have changed " /PATH/To/GtdbTK/data/ " to "/projects/b1052/pythonenvs/python2.7/GTDB/gtdb_database/release83/", but i do not understand why i came across with the pfam error, is it because the database could not be identified?
The error message is as below:
1)
Can't locate IPC/Run.pm in @INC (@INC contains: /projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/external /software/activeperl/5.16/site/lib /software/activeperl/5.16/lib .) at /projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/external/Bio/Pfam/Scan/PfamScan.pm line 39.
BEGIN failed--compilation aborted at /projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/external/Bio/Pfam/Scan/PfamScan.pm line 39.
2)
[2018-08-22 17:49:51] INFO: Identifying Pfam protein families.
[2018-08-22 17:49:53] ERROR: Pfam Error
('Unexpected error:', <type 'exceptions.ValueError'>)
3)
File "/projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/markers.py", line 238, in identify
    pfam_search.run(gene_files)
  File "/projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/external/pfam_search.py", line 188, in run
    raise ValueError("Pfam Error")
ValueError: Pfam Error
  File "/projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/external/pfam_search.py", line 136, in _workerThread
    raise error
    raise error

**Comment by pchaumeil** [comment]
It looks like the IPC::Run Perl module is not installed or not included in the @inc variable .

You first need to install the perl module using ' perl -MCPAN -e"install IPC::Run" '
Make sure that the IPC::Run module (.pm) paths is part of the @inc variable. 

If not , Please modify the PERL5LIB ( or PERLIB) environment variable to include the module :
export PERL5LIB="$PERL5LIB:/path/to/directory/where/ipc/module/.pm/is/installed"

**Comment by yuboer** [comment]
Hi  pchaumeil,

Thanks for the information, the above error was solved after loading the module needed. While i came across with another error in the FastANI step, the detailed information is as below: 

1. outlog:
[2018-08-31 15:58:14] INFO: Calculating Average Nucleotide Identity using FastANI.
list index out of range;

2. errorlog
  File "/projects/b1052/pythonenvs/python2.7/GTDB/lib/python2.7/site-packages/gtdbtk/classify.py", line 648, in _parse_fastani_results
    ref_genome = os.path.basename(info[1]).replace(Config.FASTANI_GENOMES_EXT,"")
IndexError: list index out of range

Thanks!

**Comment by yuboer** [comment]
Hi Pierre,

I am using GTDB-Tk v0.0.7 

Thanks,
Yubo

**Comment by pchaumeil** [comment]
Hi Yubo, 
Can you try to update GTDB-Tk to the latest version ( v0.1.2 ) and see if the problem still occurs?
You will also have to download the latest data ( release 86 ).

Thanks,
Pierre

**Comment by yuboer** [comment]
Hi Pierre,

Thanks!

I have downloaded the new data (release 86), and successfully updated the GTDB-Tk to the latest version (gtdbtk-0.1.3);

while i encountered errors in the test by running the command "gtdbtk -h"

the error message is as below:

"Successfully installed gtdbtk-0.1.3
(/projects/b1052/pythonenvs/python2.7/GTDB) [ywx1845@quser13 genes]$ gtdbtk -h
Traceback (most recent call last):
  File "/projects/b1052/pythonenvs/python2.7/GTDB/bin/gtdbtk", line 37, in <module>
    from gtdbtk.main import OptionsParser
  File "/home/ywx1845/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 22, in <module>
    from markers import Markers
  File "/home/ywx1845/.local/lib/python2.7/site-packages/gtdbtk/markers.py", line 35, in <module>
    import config.config as Config
ImportError: No module named config"

i did not came up with this type of error in using the previous version

Thanks,
Yubo

**Comment by pchaumeil** [comment]
Hi Yubo, 
Could you please confirm that you have created the config (config.py) file under /home/ywx1845/.local/lib/python2.7/site-packages/gtdbtk/config/  and it is readable?

Thanks,
Pierre
