### ISSUE TITLE
KeyError in gtdbtk infer_ranks

### ISSUE THREAD

**Issue by SilasK** [Ecogenomics/GTDBTk#300]
## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

gtdbtk-1.4.0

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments

I run gtdb 
- infer
- align
- classify

Then I run Fasttree on the msa similar to `gtdb infer` and rooted by the midpoint.

Then I run 
gtdb decorate and then infer_ranks

Then I encountered the following error:

## Error message

````
$ gtdbtk infer_ranks --ingroup_taxon c__Bacilli --input_tree tree/decorated.bac120.nwk --output_tree tree/manual.nwk
[2020-12-16 17:16:45] INFO: GTDB-Tk v1.4.0
[2020-12-16 17:16:45] INFO: gtdbtk infer_ranks --ingroup_taxon c__Bacilli --input_tree tree/decorated.bac120.nwk --output_tree tree/manual.nwk
[2020-12-16 17:16:45] INFO: Using GTDB-Tk reference data version r95: /home/kiesers/s/Atlas/databases/GTDB_V05/
[2020-12-16 17:16:45] INFO: Median RED values for Bacteria:
[2020-12-16 17:16:45] INFO:   Phylum    0.339
[2020-12-16 17:16:45] INFO:   Class     0.462
[2020-12-16 17:16:45] INFO:   Order     0.623
[2020-12-16 17:16:45] INFO:   Family    0.771
[2020-12-16 17:16:45] INFO:   Genus     0.934
[2020-12-16 17:16:45] INFO: Reading tree.
[2020-12-16 17:16:45] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: KeyError
  MESSAGE: 'RS_GCF_000430305.1'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/main.py", line 748, in parse_options
    self.infer_ranks(options)
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/main.py", line 577, in infer_ranks
    p.run(options.input_tree,
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/infer_ranks.py", line 174, in run
    ingroup_red = self._find_ingroup_red(ingroup_node, ingroup_domain, tree)
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/infer_ranks.py", line 119, in _find_ingroup_red
    taxa = [leaf_node_map[label].taxon for label in labels]
  File "/home/kiesers/scratch/Atlas/databases/conda_envs/28558858/lib/python3.8/site-packages/gtdbtk/infer_ranks.py", line 119, in <listcomp>
    taxa = [leaf_node_map[label].taxon for label in labels]
KeyError: 'RS_GCF_000430305.1'
================================================================================
```

**Comment by SilasK** [comment]
If I did something wrong, What would be the intended way for running infer_ranks ?

**Comment by SilasK** [comment]
Does the error mean that gtdbtk expects the reference genome to be part of the tree? I can do this by creating the tree from the .msa instead of the .user_msa

**Comment by SilasK** [comment]
Some comments about usage of the `infer` command and on which input files would still be appreciated. Thank you.

**Comment by aaronmussig** [comment]
Hello, I'm not able to reproduce the error. So that I can debug it, can you please share the tree? Thanks.

**Comment by SilasK** [comment]
I think at the end I made it work by using the tree that contains the user and the reference genomes. 

Thank you ...
