### ISSUE TITLE
Error encountered while running classify

### ISSUE THREAD

**Issue by rainbow218** [Ecogenomics/GTDBTk#303]
Hello,

appreciate any help in understanding the following error:

[2021-01-13 16:58:28] INFO: GTDB-Tk v0.3.3
[2021-01-13 16:58:28] INFO: gtdbtk classify --genome_dir ./gtdbtk/ --align_dir ./gtdbtk/align --out_dir ./gtdbtk/classify -x fa --cpus 2
[2021-01-13 16:58:28] INFO: Using GTDB-Tk reference data version r89: /data/gtdbtk/release89/
[2021-01-13 16:58:28] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: AttributeError
  MESSAGE: 'module' object has no attribute 'AF_THRESHOLD'
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/local/bin/gtdbtk", line 451, in <module>
    gt_parser.parse_options(args)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/main.py", line 588, in parse_options
    self.classify(options)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/main.py", line 385, in classify
    classify = Classify(options.cpus)
  File "/usr/local/lib/python2.7/dist-packages/gtdbtk/classify.py", line 56, in __init__
    self.af_threshold = Config.AF_THRESHOLD
AttributeError: 'module' object has no attribute 'AF_THRESHOLD'
================================================================================

**Comment by pchaumeil** [comment]
Hello,
I would recommend updating GTDB-Tk to the latest version 1.4.0 and rerun the command.
GTDB-Tk is an ongoing project and a lot of features have been implemented since release 0.3.3
