### ISSUE TITLE
align IndexError: 

### ISSUE THREAD

**Issue by yifengyuan** [Ecogenomics/GTDBTk#315]
Hi,

Identification looks good. IndexError occurred using align as below:

Looks like a similar error with https://github.com/Ecogenomics/GTDBTk/issues/281

OS: centos7

Thanks for advice in advance.

```
gtdbtk identify --genome_dir $dir_genome --out_dir $dir_identify --extension $extension --cpus 10 --prefix $sample

[2021-04-12 20:39:19] INFO: GTDB-Tk v1.4.0
[2021-04-12 20:39:19] INFO: gtdbtk identify --genome_dir /scratch/users/yfyuan/genomes/combin13663 --out_dir /scratch/users/yfyuan/PT/phylo/identify --extension faa --cpus 10 --prefix almuhgg
[2021-04-12 20:39:19] INFO: Using GTDB-Tk reference data version r95: /scratch/users/yfyuan/conda3/envs/gtdbtk-1.4.0/share/gtdbtk-1.4.0/db/release95
[2021-04-12 20:39:25] INFO: Identifying markers in 13,663 genomes with 10 threads.
[2021-04-12 20:39:25] TASK: Running Prodigal V2.6.3 to identify genes.
[2021-04-12 21:13:55] INFO: Completed 13,663 genomes in 34.49 minutes (396.16 genomes/minute).
[2021-04-12 21:13:58] WARNING: Skipping 15 of 13663 genomes as no genes were called by Prodigal. Check the genome quality (see gtdb.warnings.log).
[2021-04-12 21:13:58] TASK: Identifying TIGRFAM protein families.
[2021-04-12 21:30:16] INFO: Completed 13,648 genomes in 16.31 minutes (837.02 genomes/minute).
[2021-04-12 21:30:16] TASK: Identifying Pfam protein families.
[2021-04-12 21:33:27] INFO: Completed 13,648 genomes in 3.19 minutes (4,283.18 genomes/minute).
[2021-04-12 21:33:27] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2021-04-12 21:33:27] TASK: Summarising identified marker genes.
[2021-04-12 21:34:48] INFO: Completed 13,648 genomes in 1.34 minutes (10,196.61 genomes/minute).
[2021-04-12 21:34:48] INFO: Done.

gtdbtk align --identify_dir $dir_identify --out_dir $dir_align --cpus 10 --prefix $sample --skip_gtdb_refs --debug

[2021-04-12 22:46:54] INFO: GTDB-Tk v1.4.1
[2021-04-12 22:46:54] INFO: gtdbtk align --identify_dir /scratch/users/yfyuan/PT/phylo/identify --out_dir /scratch/users/yfyuan/PT/phylo/align --cpus 10 --prefix almuhgg --skip_gtdb_refs --debug
[2021-04-12 22:46:54] INFO: Using GTDB-Tk reference data version r95: /scratch/users/yfyuan/conda3/envs/gtdbtk/share/gtdbtk-1.4.1/db/release95
[2021-04-12 22:47:04] WARNING: Excluding 15 genomes in the identify directory which have no genes called (see gtdb.warnings.log)
[2021-04-12 22:47:11] INFO: Aligning markers in 13,648 genomes with 10 CPUs.
[2021-04-12 22:47:11] INFO: Processing 13,648 genomes identified as bacterial.
[2021-04-12 22:47:11] TASK: Generating concatenated alignment for each marker.
[2021-04-12 22:48:43] INFO: Completed 13,648 genomes in 1.53 minutes (8,949.20 genomes/minute).
[2021-04-12 22:48:43] TASK: Aligning 0 identified markers using hmmalign 3.1b2 (February 2015).
[2021-04-12 22:48:44] DEBUG: Successfully written all markers to: /scratch/users/yfyuan/PT/phylo/align/align/intermediate_results/markers
[2021-04-12 22:48:44] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2021-04-12 22:48:44] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/scratch/users/yfyuan/conda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/scratch/users/yfyuan/conda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 724, in parse_options
    self.align(options)
  File "/scratch/users/yfyuan/conda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 276, in align
    markers.align(options.identify_dir,
  File "/scratch/users/yfyuan/conda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 564, in align
    len(list(user_msa.values())[0]),
IndexError: list index out of range
================================================================================

**Comment by yifengyuan** [comment]
I am closing this issue because it works well after I replaced the sequences.

**Comment by oschakoory** [comment]
Hi,
i am having the same problem as stated above. Can you tell me how you solve it?

You replaced the sequences? how?

Thank you for your help

**Comment by yifengyuan** [comment]
I modified the header line of my sequences by removing some special characters and re-format my sequences.

**Comment by oschakoory** [comment]
Thank you for your rapid reply.

I changed the name of my sequences
3|EU334524.1.1558 --> seq1 but i am having the same error.

How did you re-format your sequences?

Here is part of my sequence:

```
>seq1
CAGGCTCCGAATTCGCCCTTAGAGTTTGATCCTGGCTCAGAACGAACGCTGGCGGCGTGC
CTAACACATGCAAGTCGAACGGAGTGAAGGAGCTTGCTCTTTCATTTAGTGGCGCACGGG
TGAGTAACGCGTAGATAATCTGCCTTGGACTCTGGGATAACATCTCGAAAGGGGTGCTAA
TACCGGATAAGCCCACGATGGCGTAAGTCATTGCGGGAAAAGGGGGCCTCTGAATATGCT
```

Thank you very much for your precious help.
