### ISSUE TITLE
EXCEPTION: IndexError

### ISSUE THREAD

**Issue by Lcornet** [Ecogenomics/GTDBTk#316]
I have this error on some of my bins, output of CONCOT:

[2021-04-15 14:50:18] INFO: GTDB-Tk v1.4.1
[2021-04-15 14:50:18] INFO: gtdbtk classify_wf --genome_dir 10.fa-temp --out_dir concoct-GTDB-10.fa -x fa --cpus 40
[2021-04-15 14:50:18] INFO: Using GTDB-Tk reference data version r95: /media/vol1/databases/gtdbtk-r95
[2021-04-15 14:50:18] INFO: Identifying markers in 1 genomes with 40 threads.
[2021-04-15 14:50:18] TASK: Running Prodigal V2.6.2 to identify genes.
[2021-04-15 14:50:19] INFO: Completed 1 genome in 0.86 seconds (1.17 genomes/second).
[2021-04-15 14:50:18] INFO: GTDB-Tk v1.4.1
[2021-04-15 14:50:18] INFO: gtdbtk classify_wf --genome_dir 10.fa-temp --out_dir concoct-GTDB-10.fa -x fa --cpus 40
[2021-04-15 14:50:18] INFO: Using GTDB-Tk reference data version r95: /media/vol1/databases/gtdbtk-r95
[2021-04-15 14:50:18] INFO: Identifying markers in 1 genomes with 40 threads.
[2021-04-15 14:50:18] TASK: Running Prodigal V2.6.2 to identify genes.
[2021-04-15 14:50:19] INFO: Completed 1 genome in 0.86 seconds (1.17 genomes/second).
[2021-04-15 14:50:19] TASK: Identifying TIGRFAM protein families.
[2021-04-15 14:50:19] INFO: Completed 1 genome in 0.80 seconds (1.25 genomes/second).
[2021-04-15 14:50:19] TASK: Identifying Pfam protein families.
[2021-04-15 14:50:20] INFO: Completed 1 genome in 0.23 seconds (4.39 genomes/second).
[2021-04-15 14:50:20] INFO: Annotations done using HMMER 3.3 (Nov 2019).
[2021-04-15 14:50:20] TASK: Summarising identified marker genes.
[2021-04-15 14:50:20] INFO: Completed 1 genome in 0.00 seconds (395.09 genomes/second).
[2021-04-15 14:50:20] INFO: Done.
[2021-04-15 14:50:20] INFO: Aligning markers in 1 genomes with 40 CPUs.
[2021-04-15 14:50:20] INFO: Processing 1 genomes identified as bacterial.
[2021-04-15 14:50:23] INFO: Read concatenated alignment for 30,238 GTDB genomes.
[2021-04-15 14:50:23] TASK: Generating concatenated alignment for each marker.
[2021-04-15 14:50:26] INFO: Completed 1 genome in 0.01 seconds (89.75 genomes/second).
[2021-04-15 14:50:26] TASK: Aligning 0 identified markers using hmmalign 3.3 (Nov 2019).
[2021-04-15 14:50:29] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2021-04-15 14:51:32] INFO: Completed 30,238 sequences in 1.05 minutes (28,715.94 sequences/minute).
[2021-04-15 14:51:32] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/media/vol1/apps/pyenv/versions/3.6.3/lib/python3.6/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/media/vol1/apps/pyenv/versions/3.6.3/lib/python3.6/site-packages/gtdbtk/main.py", line 718, in parse_options
    self.align(options)
  File "/media/vol1/apps/pyenv/versions/3.6.3/lib/python3.6/site-packages/gtdbtk/main.py", line 290, in align
    self.genomes_to_process)
  File "/media/vol1/apps/pyenv/versions/3.6.3/lib/python3.6/site-packages/gtdbtk/markers.py", line 564, in align
    len(list(user_msa.values())[0]),
IndexError: list index out of range

When bins comes from metabat, it works well but not on concoct.
Ani idea on how to solve that ?

**Comment by aaronmussig** [comment]
Hello,

Based on the output it appears that no single-copy markers were identified:

```
[2021-04-15 14:50:26] TASK: Aligning 0 identified markers using hmmalign 3.3 (Nov 2019).
```

Can you please provide your `identify/gtdbtk.bac120.markers_summary.tsv` or the input bin?

**Comment by aaronmussig** [comment]
Closing due to inactivity, feel free to reply in the future.

**Comment by nick-youngblut** [comment]
I got the same error. It would be helpful, especially for processing large numbers of assemblies, if gtdb-tk reported a warning and output NA values for any problematic assemblies instead of throwing an error.

**Comment by braddmg** [comment]
Hello! I am having the same error (or similar) when I try to run the program in the Kbase web: 
Job 66df9bef1fb35d444ad3f8db ran, but /cdr/prod/dir_2105840/JobRunner/workdir/output.json contained an error. Error in output job msg:'list index out of range' code:-32000 name:Server error error:Traceback (most recent call last): File "/kb/module/bin/../lib/kb_gtdbtk/kb_gtdbtkServer.py", line 101, in _call_method result = method(ctx, *params) File "/kb/module/lib/kb_gtdbtk/kb_gtdbtkImpl.py", line 174, in run_kb_gtdbtk_classify_wf (classification, summary_tables) = run_gtdbtk (runner, File "/kb/module/lib/kb_gtdbtk/core/gtdbtk_runner.py", line 131, in run_gtdbtk return _process_output_files(temp_output, temp_trees_output, output_dir, id_to_name) File "/kb/module/lib/kb_gtdbtk/core/gtdbtk_runner.py", line 268, in _process_output_files if row[field_i] == 'N/A': IndexError: list index out of range

Also when I try to run the program in institutional server I got the next error in the ani step: 
[2024-09-09 19:49:15] INFO: pplacer version: v1.1.alpha19-0-g807f6f3
[2024-09-09 19:53:53] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/__main__.py", line 101, in main
    gt_parser.parse_options(args)
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/main.py", line 1190, in parse_options
    self.classify(options)
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/main.py", line 587, in classify
    reports = classify.run(genomes=genomes,
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/classify.py", line 542, in run
    high_classify_tree = self.place_genomes(user_msa_file,
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/classify.py", line 270, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/opt/python/miniconda3/envs/gtdbtk-2.2.6/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 92, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================
