### ISSUE TITLE
GTDB-Tk classify_wf error during Pfam step "No such file or directory: PF00380.14.hmm"

### ISSUE THREAD

**Issue by zehanna** [Ecogenomics/GTDBTk#324]
Hello,

I have installed GTDBTk using conda and I have downloaded and unzipped the databases as described here:
https://ecogenomics.github.io/GTDBTk/installing/index.html

When using gtdbtk classify_wf, the program starts to run, however shortly afterwards I get this error:

[2021-06-14 15:13:06] INFO: GTDB-Tk v1.0.2
[2021-06-14 15:13:06] INFO: gtdbtk classify_wf -x fasta --cpus 4 --genome_dir fastANI --out_dir gtdb
[2021-06-14 15:13:06] INFO: Using GTDB-Tk reference data version r202: /home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202
[2021-06-14 15:13:06] INFO: Identifying markers in 9 genomes with 4 threads.
[2021-06-14 15:13:06] INFO: Running Prodigal V2.6.3 to identify genes.
==> Finished processing 9 of 9 (100.0%) genomes.
[2021-06-14 15:13:38] INFO: Identifying TIGRFAM protein families.
==> Finished processing 9 of 9 (100.0%) genomes.
[2021-06-14 15:13:56] INFO: Identifying Pfam protein families.
==> Finished processing 9 of 9 (100.0%) genomes.
[2021-06-14 15:13:58] INFO: Annotations done using HMMER 3.3.2 (Nov 2020)
[2021-06-14 15:13:59] INFO: Done.
[2021-06-14 15:13:59] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: '/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202/markers/pfam/individual_hmms/PF00380.14.hmm'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/lib/python3.8/site-packages/gtdbtk/main.py", line 623, in parse_options
    self.align(options)
  File "/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/lib/python3.8/site-packages/gtdbtk/main.py", line 263, in align
    markers.align(options.identify_dir,
  File "/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/lib/python3.8/site-packages/gtdbtk/markers.py", line 484, in align
    self._write_marker_info(Config.BAC120_MARKERS, bac120_marker_info_file)
  File "/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/lib/python3.8/site-packages/gtdbtk/markers.py", line 436, in _write_marker_info
    with open(marker_path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202/markers/pfam/individual_hmms/PF00380.14.hmm'

The content of ~/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202/markers/pfam/individual_hmms:

PF00368.19.hmm  PF00466.21.hmm  PF00900.21.hmm  PF01025.20.hmm  PF01157.19.hmm  PF01198.20.hmm  PF01280.21.hmm  PF01655.19.hmm  PF01866.18.hmm  PF01990.18.hmm  PF02978.20.hmm  PF04019.13.hmm  PF07541.13.hmm
PF00380.20.hmm  PF00687.22.hmm  PF01000.27.hmm  PF01090.20.hmm  PF01191.20.hmm  PF01200.19.hmm  PF01282.20.hmm  PF01798.19.hmm  PF01868.17.hmm  PF02006.17.hmm  PF03726.15.hmm  PF04104.15.hmm  PF13656.7.hmm
PF00410.20.hmm  PF00827.18.hmm  PF01015.19.hmm  PF01092.20.hmm  PF01194.18.hmm  PF01269.18.hmm  PF01496.20.hmm  PF01864.18.hmm  PF01984.21.hmm  PF02576.18.hmm  PF03874.17.hmm  PF04919.13.hmm  PF13685.7.hmm

I don't know why this one specific file PF00380.14.hmm is missing, could there be an error in how I downloaded the database?
When running gtdbtk check_install, I get:

[2021-06-14 15:17:31] INFO: GTDB-Tk v1.0.2
[2021-06-14 15:17:31] INFO: gtdbtk check_install
[2021-06-14 15:17:31] INFO: Using GTDB-Tk reference data version r202: /home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202
[2021-06-14 15:17:31] INFO: Running install verification
[2021-06-14 15:17:31] INFO: Checking /home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb/share/gtdbtk-1.0.2/db/release202
[2021-06-14 15:17:32] INFO:          |-- pplacer          HASH MISMATCH                             files (90.0%)
[2021-06-14 15:17:32] INFO:          |-- masks            HASH MISMATCH                             es (50.0%)
[2021-06-14 15:17:32] INFO:          |-- markers          HASH MISMATCH                             45 files (99.59%)
[2021-06-14 15:17:32] INFO:          |-- radii            HASH MISMATCH                             es (0.0%)
[2021-06-14 15:17:35] INFO:          |-- msa              HASH MISMATCH                              (50.0%)
[2021-06-14 15:17:35] INFO:          |-- metadata         HASH MISMATCH                             files (0.0%)
[2021-06-14 15:17:35] INFO:          |-- taxonomy         HASH MISMATCH                             files (0.0%)
[2021-06-14 15:27:37] INFO:          |-- fastani          HASH MISMATCH                             /47895 files (100.0%)
[2021-06-14 15:27:37] INFO:          |-- mrca_red         HASH MISMATCH                             files (50.0%)
[2021-06-14 15:27:37] ERROR: Unexpected files were seen, or the reference package is corrupt.
[2021-06-14 15:27:37] ERROR: Controlled exit resulting from an unrecoverable error or warning.

Would appreciate any help and/or comments.

Thanks a lot,

Hanna

Installation & server information:
## Environment
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
# packages in environment at /home/ollie/hzehnle/ownSoft/miniconda3/envs/gtdb:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dendropy                  4.5.2              pyh3252c3a_0    bioconda
fastani                   1.32                 he1c1bb9_0    bioconda
fasttree                  2.1.10               h779adbc_5    bioconda
freetype                  2.10.4               h0708190_1    conda-forge
gtdbtk                    1.0.2                    py38_1    bioconda
hmmer                     3.3.2                h1b792b2_1    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py38h5d868c9_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.3           py38h9894fe3_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                h779adbc_3    bioconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.6.3            py38h7b17777_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
2021-06-11 14:34:23  (rev 0)

2021-06-11 14:35:47  (rev 1)
    +_libgcc_mutex-0.1 (conda-forge/linux-64)
    +_openmp_mutex-4.5 (conda-forge/linux-64)
    +boost-1.70.0 (conda-forge/linux-64)
    +boost-cpp-1.70.0 (conda-forge/linux-64)
    +bzip2-1.0.8 (conda-forge/linux-64)
    +ca-certificates-2021.5.30 (conda-forge/linux-64)
    +certifi-2021.5.30 (conda-forge/linux-64)
    +cycler-0.10.0 (conda-forge/noarch)
    +dendropy-4.5.2 (bioconda/noarch)
    +fastani-1.32 (bioconda/linux-64)
    +fasttree-2.1.10 (bioconda/linux-64)
    +freetype-2.10.4 (conda-forge/linux-64)
    +gtdbtk-1.0.2 (bioconda/linux-64)
    +hmmer-3.3.2 (bioconda/linux-64)
    +icu-67.1 (conda-forge/linux-64)
    +kiwisolver-1.3.1 (conda-forge/linux-64)
    +ld_impl_linux-64-2.35.1 (conda-forge/linux-64)
    +libblas-3.9.0 (conda-forge/linux-64)
    +libcblas-3.9.0 (conda-forge/linux-64)
    +libffi-3.3 (conda-forge/linux-64)
    +libgcc-ng-9.3.0 (conda-forge/linux-64)
    +libgfortran-ng-9.3.0 (conda-forge/linux-64)
    +libgfortran5-9.3.0 (conda-forge/linux-64)
    +libgomp-9.3.0 (conda-forge/linux-64)
    +liblapack-3.9.0 (conda-forge/linux-64)
    +libopenblas-0.3.15 (conda-forge/linux-64)
    +libpng-1.6.37 (conda-forge/linux-64)
    +libstdcxx-ng-9.3.0 (conda-forge/linux-64)
    +lz4-c-1.9.3 (conda-forge/linux-64)
    +matplotlib-3.2.2 (conda-forge/linux-64)
    +matplotlib-base-3.2.2 (conda-forge/linux-64)
    +ncurses-6.2 (conda-forge/linux-64)
    +numpy-1.20.3 (conda-forge/linux-64)
    +openssl-1.1.1k (conda-forge/linux-64)
    +pip-21.1.2 (conda-forge/noarch)
    +pplacer-1.1.alpha19 (bioconda/linux-64)
    +prodigal-2.6.3 (bioconda/linux-64)
    +pyparsing-2.4.7 (conda-forge/noarch)
    +python-3.8.10 (conda-forge/linux-64)
    +python-dateutil-2.8.1 (conda-forge/noarch)
    +python_abi-3.8 (conda-forge/linux-64)
    +readline-8.1 (conda-forge/linux-64)
    +scipy-1.6.3 (conda-forge/linux-64)
    +setuptools-49.6.0 (conda-forge/linux-64)
    +six-1.16.0 (conda-forge/noarch)
    +sqlite-3.35.5 (conda-forge/linux-64)
    +tk-8.6.10 (conda-forge/linux-64)
    +tornado-6.1 (conda-forge/linux-64)
    +wheel-0.36.2 (conda-forge/noarch)
    +xz-5.2.5 (conda-forge/linux-64)
    +zlib-1.2.11 (conda-forge/linux-64)
    +zstd-1.4.9 (conda-forge/linux-64)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name      : Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
28
- RAM: `grep "^MemTotal" /proc/meminfo`
MemTotal:       263853068 kB
- OS: `cat /etc/os-release`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

## Debugging information
- [x] `gtdbtk.log` has been included (drag and drop the file to upload).
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/6648647/gtdbtk.log)

**Comment by zehanna** [comment]
I could solve this problem by downloading the newest version of GTDBTk using these instructions:
https://ecogenomics.github.io/GTDBTk/installing/bioconda.html

I believe there was an incompability between the previous GTDBTk version I had downloaded (v1.0.2) and the database release 202.
