### ISSUE TITLE
Error while processing 54 genomes

### ISSUE THREAD

**Issue by aaronmussig** [Ecogenomics/GTDBTk#327]
I am also getting similar error while processing 54 genomes:
 ERROR: Input file does not exist: /tmp/tmpl4th9zaugtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_GCF_013283645.1.gff
Process Process-3:1:1:
Traceback (most recent call last):
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 313, in __init__
    check_file_exists(filename)
  File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/biolib_lite/common.py", line 96, in check_file_exists
    raise BioLibFileNotFound('Input file does not exist: ' + input_file)
gtdbtk.biolib_lite.exceptions.BioLibFileNotFound: Input file does not exist: /tmp/tmpl4th9zaugtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_GCF_013283645.1.gff

gtdbtk.biolib_lite.exceptions.BioLibFileNotFound: Input file does not exist: /tmp/tmpu5ref0kbgtdbtk_prodigal_tmp_/4/Ensifer_psoraleae_CCBAU 65732_G283645.1.gff
Process Process-3:
Traceback (most recent call last):
File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/dnd/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 141, in _worker
rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
File "/home/dnd/miniconda3/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 107, in _run_prodigal
raise Exception("An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
==> Processed 52/54 genomes (96%) |██████████████▍| [87.36genome/s, ETA 00:00][2021-06-19 17:22:08] ERROR: Controlled exit resulting from an unrecoe error or warning.

================================================================================
EXCEPTION: ProdigalException
MESSAGE: An exception was caught while running Prodigal.

_Originally posted by @RahiPraveen in https://github.com/Ecogenomics/GTDBTk/issues/325#issuecomment-864395959_

**Comment by aaronmussig** [comment]
Hi @RahiPraveen this issue is caused by having a space in the name of the input file, if you replace the spaces with underscores it will work.

In version 1.5.1 this will be fixed.

**Comment by RahiPraveen** [comment]
> Hi @RahiPraveen this issue is caused by having a space in the name of the input file, if you replace the spaces with underscores it will work.
> 
> In version 1.5.1 this will be fixed.
@aaronmussig 
Oh, yes I found those sequences with spaces in their labels, it worked. Thanks
