### ISSUE TITLE
Error in de_novo_wf

### ISSUE THREAD

**Issue by mlbonatelli** [Ecogenomics/GTDBTk#331]
Hi,

I am using de_novo_wf to help me identify a bacterium. I am using the command below:

    gtdbtk de_novo_wf --genome_dir $GENDIR --bacteria --outgroup_taxon g__Acidobacterium --taxa_filter f__Comamonadaceae -x fasta --cpus 12 --out_dir $OUTDIR

However, I am getting the following error (this is the log):

[2021-06-30 06:19:40] INFO: GTDB-Tk v1.5.0
[2021-06-30 06:19:40] INFO: gtdbtk de_novo_wf --genome_dir ../../results/11_GTDB/denovo_wf_delftia --bacteria --outgroup_taxon g__Acidobacterium --taxa_filter f__Comamonadaceae -x fasta --cpus 12 --out_dir ../../results/11_GTDB/denovo_wf_delftia
[2021-06-30 06:19:40] INFO: Using GTDB-Tk reference data version r202: /software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/share/gtdbtk-1.5.0/db/
[2021-06-30 06:19:40] INFO: Identifying markers in 1 genomes with 12 threads.
[2021-06-30 06:19:40] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/1 genomes (0%) |               | [?genome/s, ETA ?]
[2021-06-30 06:21:43] INFO: Completed 1 genome in 2.03 minutes (2.03 minutes/genome).
[2021-06-30 06:21:43] TASK: Identifying TIGRFAM protein families.             
[2021-06-30 06:21:53] INFO: Completed 1 genome in 10.35 seconds (10.35 seconds/genome).
[2021-06-30 06:21:53] TASK: Identifying Pfam protein families.               
[2021-06-30 06:21:55] INFO: Completed 1 genome in 1.74 seconds (1.74 seconds/genome).
[2021-06-30 06:21:55] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2021-06-30 06:21:55] TASK: Summarising identified marker genes.
[2021-06-30 06:21:55] INFO: Completed 1 genome in 0.11 seconds (8.73 genomes/second).
[2021-06-30 06:21:55] INFO: Done.
[2021-06-30 06:21:55] INFO: Aligning markers in 1 genomes with 12 CPUs.
[2021-06-30 06:21:55] INFO: Processing 1 genomes identified as bacterial.
[2021-06-30 06:22:02] INFO: Read concatenated alignment for 45,555 GTDB genomes.
[2021-06-30 06:22:02] INFO: Filtered 100.00% (45,553/45,555) taxa based on assigned taxonomy, 2 taxa remain.
[2021-06-30 06:22:02] TASK: Generating concatenated alignment for each marker.
[2021-06-30 06:22:04] INFO: Completed 1 genome in 0.10 seconds (10.01 genomes/second).
[2021-06-30 06:22:04] TASK: Aligning 118 identified markers using hmmalign 3.1b2 (February 2015).
[2021-06-30 06:22:07] INFO: Completed 118 markers in 0.95 seconds (124.74 markers/second).
[2021-06-30 06:22:07] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2021-06-30 06:22:07] INFO: Completed 3 sequences in 0.01 seconds (359.43 sequences/second).
[2021-06-30 06:22:07] INFO: Masked bacterial alignment from 41,084 to 5,037 AAs.
[2021-06-30 06:22:07] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
[2021-06-30 06:22:07] INFO: Creating concatenated alignment for 3 bacterial GTDB and user genomes.
[2021-06-30 06:22:07] INFO: Creating concatenated alignment for 1 bacterial user genomes.
[2021-06-30 06:22:07] INFO: Done.
[2021-06-30 06:22:07] INFO: Inferring FastTree (WAG, SH support values) using a maximum of 12 CPUs.
[2021-06-30 06:22:08] INFO: FastTree version: 2.1.10
[2021-06-30 06:22:08] INFO: Done.
[2021-06-30 06:22:08] INFO: Reading GTDB taxonomy for representative genomes.
[2021-06-30 06:22:08] INFO: Read taxonomy for 47,894 genomes.
[2021-06-30 06:22:08] INFO: Identifying genomes from the specified outgroup: g__Acidobacterium
[2021-06-30 06:22:08] INFO: Identified 2 outgroup taxa in the tree.
[2021-06-30 06:22:08] INFO: Identified 1 ingroup taxa in the tree.
[2021-06-30 06:22:08] INFO: Outgroup is monophyletic.
[2021-06-30 06:22:08] INFO: Rerooting tree.
[2021-06-30 06:22:08] INFO: Rerooted tree written to: ../../results/11_GTDB/denovo_wf_delftia/infer/intermediate_results/gtdbtk.bac120.rooted.tree
[2021-06-30 06:22:08] INFO: Done.
[2021-06-30 06:22:08] INFO: Reading GTDB taxonomy for representative genomes.
[2021-06-30 06:22:09] INFO: Read taxonomy for 47,894 genomes.
[2021-06-30 06:22:09] INFO: Reading tree.
[2021-06-30 06:22:09] INFO: Removing any previous internal node labels.
[2021-06-30 06:22:09] INFO: Calculating F-measure statistic for each taxa.
[2021-06-30 06:22:09] INFO: Calculating taxa within each lineage.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Domain rank.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Phylum rank.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Class rank.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Order rank.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Family rank.
[2021-06-30 06:22:09] INFO: Processing 1 taxa at Genus rank.
[2021-06-30 06:22:09] INFO: Processing 2 taxa at Species rank.
[2021-06-30 06:22:09] WARNING: There are 6 taxa with multiple placements of equal quality.
[2021-06-30 06:22:09] WARNING: These were resolved by placing the label at the most terminal position.
[2021-06-30 06:22:09] WARNING: Ideally, taxonomic assignment of all genomes should be established before tree decoration.
[2021-06-30 06:22:09] INFO: Placing labels on tree.
[2021-06-30 06:22:09] INFO: Writing out statistics for taxa.
[2021-06-30 06:22:09] INFO: Writing out inferred taxonomy for each genome.
[2021-06-30 06:22:09] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/main.py", line 686, in parse_options
    self.decorate(options)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/main.py", line 523, in decorate
    d.run(options.input_tree,
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/decorate.py", line 379, in run
    self._write_taxonomy(tree, out_taxonomy)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/decorate.py", line 314, in _write_taxonomy
    taxa = self._leaf_taxa(leaf)
  File "/software/anaconda3/4.9.2/lssc0-linux/envs/gtdbtk-1.5.0/lib/python3.8/site-packages/gtdbtk/decorate.py", line 295, in _leaf_taxa
    last_rank = ordered_taxa[-1][0:3]
IndexError: list index out of range

Can anyone figure out what is the problem?

Thanks!
Maria

-----

## Environment
- [X] Using a conda environment (include the output of `conda list && conda list --revisions`)
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
capnproto                 0.6.1                hfc679d8_1    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
dendropy                  4.5.2              pyh3252c3a_0    bioconda
fastani                   1.32                 he1c1bb9_0    bioconda
fasttree                  2.1.10               h779adbc_5    bioconda
gsl                       2.6                  he838d99_2    conda-forge
gtdbtk                    1.5.0              pyhdfd78af_0    bioconda
hmmer                     3.1b2                         3    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mash                      2.3                  he348c14_1    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.3           py38h9894fe3_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                h779adbc_3    bioconda
python                    3.8.10          h49503c6_1_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.61.0             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name	: AMD Opteron(tm) Processor 6380 64
- RAM: `grep "^MemTotal" /proc/meminfo`
MemTotal:       264121592 kB
- OS: `cat /etc/os-release`
Ubuntu version 16.04.6 LTS (Xenial Xerus)

## Debugging information
- [X] `gtdbtk.log` has been included (drag and drop the file to upload).
- [X] Genomes have been included (if possible, and there are few).
[Delftia-005_gapClosed_min515.fa.zip](https://github.com/Ecogenomics/GTDBTk/files/6741369/Delftia-005_gapClosed_min515.fa.zip)

**Comment by pchaumeil** [comment]
Hello,

There is actually no rank called 'f__Comamonadaceae' in GTDB R202 so GTDB-Tk is only recovering the outgroup 'g__Acidobacterium' ( with 2 genomes) . with 'f__Comamonadaceae' There is some missing information to decorate the final tree.

We will update GTDB-Tk to return a warning when this case happens. In the meantime, you should get a taxonomy for your genome of interest by picking any other taxa_filter in R202.

**Comment by mlbonatelli** [comment]
Thank you, I will change this parameter!
