### ISSUE TITLE
error occured using gtdbtk de_novo_wf for genome tree

### ISSUE THREAD

**Issue by Holly202109** [Ecogenomics/GTDBTk#336]
Dear GTDB-Tk team,

I am using gtdbtk de_novo_wf to analyze a set of draft genome files, in order to obtain a tree file only inlcuding the targeted genomes, with the following command:

" gtdbtk de_novo_wf --genome_dir medhigh --bacteria --outgroup_taxon d__Archaea --out_dir tree -x fa --skip_gtdb_refs  --gtdbtk_classification_file med-high-taxo.csv --custom_taxonomy_file med-high-taxo.csv --cpus 30 "

These genomes have actually already been anazlyed with  classify_wf, with the taxonomy information obtained.
I then made a med-high-taxo.csv which included the user_genome and classification as follows:

user_genome | classification |  
-- | -- | --
bin.cz1.105 | d__Bacteria;p__Chloroflexota;c__Anaerolineae;o__Promineofilales;f__;g__;s__ |  
bin.cz1.11 | d__Bacteria;p__Spirochaetota;c__Spirochaetia;o__Sphaerochaetales;f__Sphaerochaetaceae;g__Sphaerochaeta;s__Sphaerochaeta sp001604325 |  
bin.cz1.128 | d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Acetivibrionales;f__DSM-8532;g__DTU059;s__ |  

This med-high-taxo.csv was used as "gtdbtk_classification_file" and "custom_taxonomy_file"(as attached).
These genomes include both members identifeid as bacteria and archaea. I intended to  make a tree including both bacteria and archaea, using archaeal genomes as outgroup.

During the running, I got this error message:
[2021-07-18 12:16:33] TASK: Masking columns of archaeal multiple sequence alignment using canonical mask.
[2021-07-18 12:16:33] INFO: Completed 15 sequences in 0.03 seconds (465.69 sequences/second).
[2021-07-18 12:16:33] INFO: Masked archaeal alignment from 32,675 to 5,124 AAs.
[2021-07-18 12:16:33] INFO: 0 archaeal user genomes have amino acids in <10.0% of columns in filtered MSA.
[2021-07-18 12:16:33] INFO: Creating concatenated alignment for 15 archaeal user genomes.
[2021-07-18 12:16:33] INFO: Done.
[2021-07-18 12:16:33] INFO: Inferring FastTree (WAG, SH support values) using a maximum of 30 CPUs.
[2021-07-18 12:18:20] INFO: FastTree version: 2.1.10
[2021-07-18 12:18:20] INFO: Done.
[2021-07-18 12:18:20] INFO: Reading GTDB taxonomy for representative genomes.
[2021-07-18 12:18:20] INFO: Reading GTDB-Tk classification file.
[2021-07-18 12:18:20] ERROR: Failed to parse taxonomy file on line 1
[2021-07-18 12:18:20] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/user/miniconda2/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/home/user/miniconda2/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 673, in parse_options
    self.root(options)
  File "/home/user/miniconda2/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 494, in root
    taxonomy = self._read_taxonomy_files(options)
  File "/home/user/miniconda2/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 190, in _read_taxonomy_files
    gtdbtk_taxonomy = Taxonomy().read(options.gtdbtk_classification_file)
  File "/home/user/miniconda2/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/taxonomy.py", line 825, in read
    tax_str = line_split[1].rstrip()
IndexError: list index out of range

Would you please help me to see what it the problem? 
Thank you very much.

Liping
[med-high-taxo.csv](https://github.com/Ecogenomics/GTDBTk/files/6835756/med-high-taxo.csv)

**Comment by aaronmussig** [comment]
Hello,

Sorry for the late reply. If you remove the header line of `med-high-taxo.csv` then you will no longer have this issue. I'll add a warning to make the error message more descriptive.
