### ISSUE TITLE
KeyError: 'bar'

### ISSUE THREAD

**Issue by samfux84** [Ecogenomics/GTDBTk#337]
## Environment
- [x ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

```
[sfux@eu-login-27 test]$ pip list | grep gtdb
gtdbtk                        1.5.0
WARNING: You are using pip version 21.1.1; however, version 21.2.1 is available.
You should consider upgrading via the '/cluster/apps/gdc/python/3.6.1/bin/python3.6 -m pip install --upgrade pip' command.
[sfux@eu-login-27 test]$ pip list | grep tqdm
tqdm                          4.32.2
WARNING: You are using pip version 21.1.1; however, version 21.2.1 is available.
You should consider upgrading via the '/cluster/apps/gdc/python/3.6.1/bin/python3.6 -m pip install --upgrade pip' command.
[sfux@eu-login-27 test]$

```

## Server information
- CPU:

```
[sfux@eu-login-27 test]$ grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo
model name      : Intel(R) Xeon(R) CPU E3-1284L v4 @ 2.90GHz
4
[sfux@eu-login-27 test]$
```

- RAM: 

```
[sfux@eu-login-27 test]$ grep "^MemTotal" /proc/meminfo
MemTotal:       32871788 kB
[sfux@eu-login-27 test]$
```

- OS: 

```
[sfux@eu-login-27 test]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[sfux@eu-login-27 test]$
```

## Debugging information
- [x] `gtdbtk.log` has been included (drag and drop the file to upload).

```
[sfux@eu-login-27 test]$ cat test/gtdbtk.log
[2021-07-28 14:19:33] INFO: GTDB-Tk v1.5.0
[2021-07-28 14:19:33] INFO: gtdbtk test --out_dir test --cpus 1
[2021-07-28 14:19:33] INFO: Using GTDB-Tk reference data version r202: /cluster/project/gdc/shared/databases/gtdbtk/release202
[2021-07-28 14:19:33] INFO: Command: gtdbtk classify_wf --genome_dir test/genomes --out_dir test/output --cpus 1
[2021-07-28 14:20:10] ERROR: The test returned a non-zero exit code.
[2021-07-28 14:20:10] ERROR: A detailed summary of the execution log can be found here: test/test_execution.log
[2021-07-28 14:20:10] ERROR: The test has failed.
[2021-07-28 14:20:10] ERROR: Controlled exit resulting from early termination.
[sfux@eu-login-27 test]$
```

- [ ] Genomes have been included (if possible, and there are few).

I don't know what genomes were included. It is a standard test from GTDB-Tk that I was running:

## Additional comments

When installing GTDB-Tk, I used dependencies that I compiled myself (most of them from source):

module load gcc/4.8.2 gdc prodigal/2.6.3 hmmer/3.3.2 python/3.6.1 pplacer/1.1.alpha19 gsl/1.16 fastani/1.33 fasttree/2.1.11 mash/2.3 gtdb-tk/1.5.0

I tried to run the standard test

gtdbtk test --out_dir test --cpus 1

which failed:

```
[sfux@eu-login-27 test]$ module load gcc/4.8.2 gdc prodigal/2.6.3 hmmer/3.3.2 python/3.6.1 pplacer/1.1.alpha19 gsl/1.16 fastani/1.33 fasttree/2.1.11 mash/2.3 gtdb-tk/1.5.0
Autoloading openblas/0.2.13_seq
[sfux@eu-login-27 test]$ mkdir test
[sfux@eu-login-27 test]$ gtdbtk test --out_dir test --cpus 1
[2021-07-28 14:19:33] INFO: GTDB-Tk v1.5.0
[2021-07-28 14:19:33] INFO: gtdbtk test --out_dir test --cpus 1
[2021-07-28 14:19:33] INFO: Using GTDB-Tk reference data version r202: /cluster/project/gdc/shared/databases/gtdbtk/release202
[2021-07-28 14:19:33] INFO: Command: gtdbtk classify_wf --genome_dir test/genomes --out_dir test/output --cpus 1
[2021-07-28 14:20:10] ERROR: The test returned a non-zero exit code.
[2021-07-28 14:20:10] ERROR: A detailed summary of the execution log can be found here: test/test_execution.log
[2021-07-28 14:20:10] ERROR: The test has failed.
[2021-07-28 14:20:10] ERROR: Controlled exit resulting from early termination.
[sfux@eu-login-27 test]$
```

The traceback looks like:

```
================================================================================
EXCEPTION: KeyError
  MESSAGE: 'bar'
________________________________________________________________________________

Traceback (most recent call last):
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/main.py", line 700, in parse_options
    self.identify(options)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/main.py", line 259, in identify
    options.write_single_copy_genes)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/markers.py", line 220, in identify
    write_single_copy_genes)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/markers.py", line 87, in _report_identified_marker_genes
    for db_genome_id, info in tqdm_log(sorted(gene_dict.items()), unit='genome'):
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/gtdbtk/tools.py", line 369, in __init__
    self.tqdm = tqdm(iterable, **merged)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/tqdm/_tqdm.py", line 945, in __init__
    self.display()
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/tqdm/_tqdm.py", line 1335, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __repr__
    return self.format_meter(**self.format_dict)
  File "/cluster/apps/gdc/python/3.6.1/lib64/python3.6/site-packages/tqdm/_tqdm.py", line 419, in format_meter
    return bar_format.format(**format_dict)
KeyError: 'bar'
================================================================================
```

Any help is appreciated.

Best regards

Sam

**Comment by pchaumeil** [comment]
Hi,
Please make the version of tqdm you have installed is 4.31.0 or higher.
This can be the issue in your setup.

**Comment by samfux84** [comment]
@pchaumeil Thank you for your reply. If you look at the the information that I provided in the section "Environment", then you can see that the tqdm version is already 4.32.2.

Best regards

Sam

**Comment by samfux84** [comment]
@pchaumeil Updating tqdm from 4.32.2 to 4.35.0 solve the issue.

Thank you for your help
