### ISSUE TITLE
Error during gtdbtk classify_wf 

### ISSUE THREAD

**Issue by oschakoory** [Ecogenomics/GTDBTk#348]
Hi,

Please help me solve this error:
````
$ gtdbtk classify_wf --genome_dir genomes/ --out_dir classify_output

[2021-09-15 16:00:44] INFO: GTDB-Tk v1.6.0
[2021-09-15 16:00:44] INFO: gtdbtk classify_wf --genome_dir genomes/ --out_dir classify_output
[2021-09-15 16:00:44] INFO: Using GTDB-Tk reference data version r202: /miniconda3/envs/gtdbtk/share/gtdbtk-1.6.0/db/
[2021-09-15 16:00:44] INFO: Identifying markers in 55 genomes with 1 threads.
[2021-09-15 16:00:44] TASK: Running Prodigal V2.6.3 to identify genes.
[2021-09-15 16:00:53] INFO: Completed 55 genomes in 8.55 seconds (6.43 genomes/second).
[2021-09-15 16:00:53] WARNING: Skipping 3 of 55 genomes as no genes were called by Prodigal. Check the genome quality (see gtdbtk.warnings.log).
[2021-09-15 16:00:53] WARNING: Skipping: HQ220022.1.1466
[2021-09-15 16:00:53] WARNING: Skipping: KT280489.1.1462
[2021-09-15 16:00:53] WARNING: Skipping: M59134.1.1466
[2021-09-15 16:00:53] TASK: Identifying TIGRFAM protein families.
[2021-09-15 16:01:03] INFO: Completed 52 genomes in 10.38 seconds (5.01 genomes/second).
[2021-09-15 16:01:03] TASK: Identifying Pfam protein families.                 
[2021-09-15 16:01:05] INFO: Completed 52 genomes in 2.30 seconds (22.64 genomes/second).
[2021-09-15 16:01:05] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2021-09-15 16:01:05] TASK: Summarising identified marker genes.
[2021-09-15 16:01:06] INFO: Completed 52 genomes in 0.36 seconds (143.65 genomes/second).
[2021-09-15 16:01:06] INFO: Done.
[2021-09-15 16:01:06] INFO: Aligning markers in 52 genomes with 1 CPUs.
[2021-09-15 16:01:06] INFO: Processing 52 genomes identified as bacterial.
[2021-09-15 16:01:12] INFO: Read concatenated alignment for 45,555 GTDB genomes.
[2021-09-15 16:01:12] TASK: Generating concatenated alignment for each marker.
[2021-09-15 16:01:12] INFO: Completed 52 genomes in 0.60 seconds (86.38 genomes/second).
[2021-09-15 16:01:13] TASK: Aligning 0 identified markers using hmmalign 3.1b2 (February 2015).
[2021-09-15 16:01:13] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2021-09-15 16:02:21] INFO: Completed 45,555 sequences in 1.13 minutes (40,296.19 sequences/minute).
[2021-09-15 16:02:21] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 735, in parse_options
    self.align(options)
  File "/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 291, in align
    markers.align(options.identify_dir,
  File "/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 567, in align
    len(list(user_msa.values())[0]),
IndexError: list index out of range
================================================================================
````
Thank you very much for your help.

**Comment by aaronmussig** [comment]
Hello, based on this error it appears that GTDB-Tk was unable to assign a domain to your genomes, please check the [marker summary file](https://ecogenomics.github.io/GTDBTk/files/markers_summary.tsv.html) and run your genomes through a QC program such as [CheckM](https://github.com/Ecogenomics/CheckM). Let me know if you would otherwise have expected them to suceed.

In a future version, the program will exit gracefully if this happens.

**Comment by saad272** [comment]
Hi,

Please help me to resolve this error:
```
(gtdbtk-2.1.0) [root@83d6a774cfa6 Binning]# gtdbtk classify_wf --extension .fa --cpus 14 --genome_dir . --out_dir gtdbtk
[2022-10-21 18:58:00] INFO: GTDB-Tk v2.1.0
[2022-10-21 18:58:00] INFO: gtdbtk classify_wf --extension .fa --cpus 14 --genome_dir . --out_dir gtdbtk
[2022-10-21 18:58:00] INFO: Using GTDB-Tk reference data version r207: /home/IAME/db/gtdbtk-2.1.0/release207_v2/
[2022-10-21 18:58:02] INFO: Identifying markers in 20 genomes with 14 threads.
[2022-10-21 18:58:02] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-10-21 18:58:55] INFO: Completed 20 genomes in 52.83 seconds (2.64 seconds/genome).
[2022-10-21 18:58:55] TASK: Identifying TIGRFAM protein families.
[2022-10-21 18:59:07] INFO: Completed 20 genomes in 12.16 seconds (1.64 genomes/second).
[2022-10-21 18:59:07] TASK: Identifying Pfam protein families.
[2022-10-21 18:59:08] INFO: Completed 20 genomes in 1.11 seconds (18.09 genomes/second).
[2022-10-21 18:59:08] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2022-10-21 18:59:08] TASK: Summarising identified marker genes.
[2022-10-21 18:59:09] INFO: Completed 20 genomes in 0.82 seconds (24.27 genomes/second).
[2022-10-21 18:59:09] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: OSError
  MESSAGE: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdbtk/gtdbtk.failed_genomes.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 243, in identify
    self._report_identified_marker_genes(genome_dictionary, out_dir, prefix,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 117, in _report_identified_marker_genes
    symlink_f(PATH_FAILS.format(prefix=prefix),
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/tools.py", line 245, in symlink_f
    os.symlink(src, dst)
OSError: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdbtk/gtdbtk.failed_genomes.tsv'
================================================================================
```
