### ISSUE TITLE
PplacerException Error

### ISSUE THREAD

**Issue by kevinmyers** [Ecogenomics/GTDBTk#352]
## Additional comments
I am running GTDBTk on 123 bacterial MAGs using GTDB-Tk v1.5.1 (installed via Anaconda, see below) and release202 using the following commands:

`export GTDBTK_DATA_PATH=/mnt/bigdata/processed_data/kmyers/GTDB/release202`
`~/anaconda3/bin/gtdbtk classify_wf --genome_dir ./ --out_dir ./GTDBTk_out/ -x fasta --cpus 16`

It runs fine until step 6 of 9:  Pulling Exponents when I get the following error (also in the LOG file, attached):

`[2021-10-04 15:58:06] INFO: pplacer version: v1.1.alpha19-0-g807f6f3
==> Step 6 of 9: Pulling exponents.                               Process Process-137:                      
Traceback (most recent call last):
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/external/pplacer.py", line 126, in _worker
    'file: {}'.format(pplacer_out))
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: ./GTDBTk_out/classify/intermediate_results/pplacer/pplacer.bac120.out
[2021-10-04 16:27:29] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/main.py", line 737, in parse_options
    self.classify(options)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/main.py", line 462, in classify
    options.split_tree)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/classify.py", line 448, in run
    scratch_dir)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/classify.py", line 241, in place_genomes
    user_msa_file, pplacer_out, pplacer_mmap_file)
  File "/home/GLBRCORG/kmyers/anaconda3/lib/python3.6/site-packages/gtdbtk/external/pplacer.py", line 93, in run
    'An error was encountered while running pplacer.')
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
`
Here is what is in placer.bac120.out:

> Running pplacer v1.1.alpha19-0-g807f6f3 analysis on ./GTDBTk_dRep/align/gtdbtk.bac120.user_msa.fasta...
> Didn't find any reference sequences in given alignment file. Using supplied reference alignment.
> Pre-masking sequences... sequence length cut from 5037 to 5037.
> Determining figs... figs disabled.
> Allocating memory for internal nodes... done.
> Caching likelihood information on reference tree... 

I've successfully run GTDBTk before and as far as I know, nothing as changed on the server side (I'm running this on a shared server cluster). I've included the Environment and CPU/OS information below. Any help would be greatly appreciated. Thanks!!

## Environment
- [X] Using a conda environment (include the output of `conda list && conda list --revisions`)

$ conda list && conda list --revisions
packages in environment at /opt/bifxapps/miniconda3:
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
blas                      1.0                         mkl  
boost                     1.74.0           py37h429e714_0    conda-forge
boost-cpp                 1.74.0               h9359b55_0    conda-forge
bottleneck                1.3.2            py37heb32a55_1  
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2021.5.30        py37h06a4308_0  
cffi                      1.14.6           py37h400218f_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     4.10.3           py37h06a4308_0  
conda-package-handling    1.7.3            py37h27cfd23_1  
cryptography              3.4.7            py37hd23ed53_0  
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.4               h5ab3b9f_0  
glib                      2.69.1               h5202010_0  
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.2                pyhd3eb1b0_0  
intel-openmp              2021.3.0          h06a4308_3350  
jpeg                      9b                   h024ee3a_2  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libedit                   3.1.20210714         h7f8727e_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               h68273f3_2    conda-forge
lz4-c                     1.9.3                h295c915_1  
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.0            py37h42c9631_2  
mkl_random                1.2.2            py37h51133e4_0  
ncurses                   6.2                  he6710b0_1  
numexpr                   2.7.3            py37h22e1b3c_1  
numpy                     1.20.3           py37hf144106_0  
numpy-base                1.20.3           py37h74d4b33_0  
olefile                   0.46                     py37_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   1.1.1k               h27cfd23_0  
pandas                    1.3.2            py37h8c16a72_0  
pcre                      8.45                 h295c915_0  
pillow                    8.3.1            py37h2c7a002_0  
pip                       21.0.1           py37h06a4308_0  
pixman                    0.38.0            h516909a_1003    conda-forge
pycairo                   1.19.1           py37h708ec4a_0  
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0  
rdkit                     2020.03.6        py37h0c252aa_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.26.0             pyhd3eb1b0_0  
ruamel_yaml               0.15.100         py37h27cfd23_0  
setuptools                52.0.0           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.62.1             pyhd3eb1b0_1  
urllib3                   1.26.6             pyhd3eb1b0_1  
wheel                     0.37.0             pyhd3eb1b0_0  
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
2019-10-24 19:27:50  (rev 0)
    +_libgcc_mutex-0.1
    +asn1crypto-1.2.0
    +ca-certificates-2019.10.16
    +certifi-2019.9.11
    +cffi-1.13.0
    +chardet-3.0.4
    +conda-4.7.12
    +conda-package-handling-1.6.0
    +cryptography-2.8
    +idna-2.8
    +libedit-3.1.20181209
    +libffi-3.2.1
    +libgcc-ng-9.1.0
    +libstdcxx-ng-9.1.0
    +ncurses-6.1
    +openssl-1.1.1d
    +pip-19.3.1
    +pycosat-0.6.3
    +pycparser-2.19
    +pyopenssl-19.0.0
    +pysocks-1.7.1
    +python-3.7.4
    +readline-7.0
    +requests-2.22.0
    +ruamel_yaml-0.15.46
    +setuptools-41.4.0
    +six-1.12.0
    +sqlite-3.30.0
    +tk-8.6.8
    +tqdm-4.36.1
    +urllib3-1.24.2
    +wheel-0.33.6
    +xz-5.2.4
    +yaml-0.1.7
    +zlib-1.2.11

2020-01-22 11:01:30  (rev 1)
     asn1crypto  {1.2.0 -> 1.3.0}
     ca-certificates  {2019.10.16 -> 2019.11.27}
     certifi  {2019.9.11 -> 2019.11.28}
     cffi  {1.13.0 -> 1.13.2}
     conda  {4.7.12 -> 4.8.1}
     pycosat  {0.6.3 -> 0.6.3}
     pyopenssl  {19.0.0 -> 19.1.0}
     python  {3.7.4 -> 3.7.6}
     requests  {2.22.0 -> 2.22.0}
     ruamel_yaml  {0.15.46 -> 0.15.87}
     setuptools  {41.4.0 -> 44.0.0}
     six  {1.12.0 -> 1.13.0}
     sqlite  {3.30.0 -> 3.30.1}
     tqdm  {4.36.1 -> 4.41.1}
     urllib3  {1.24.2 -> 1.25.7}
    +ld_impl_linux-64-2.33.1

2020-03-09 12:25:21  (rev 2)
     _libgcc_mutex  {0.1 -> 0.1 (defaults/linux-64)}
     asn1crypto  {1.3.0 -> 1.3.0 (defaults/linux-64)}
     ca-certificates  {2019.11.27 -> 2020.1.1 (defaults/linux-64)}
     certifi  {2019.11.28 -> 2019.11.28 (defaults/linux-64)}
     cffi  {1.13.2 -> 1.14.0 (defaults/linux-64)}
     chardet  {3.0.4 -> 3.0.4 (defaults/linux-64)}
     conda  {4.8.1 -> 4.8.2 (defaults/linux-64)}
     conda-package-handling  {1.6.0 -> 1.6.0 (defaults/linux-64)}
     cryptography  {2.8 -> 2.8 (defaults/linux-64)}
     idna  {2.8 -> 2.8 (defaults/linux-64)}
     ld_impl_linux-64  {2.33.1 -> 2.33.1 (defaults/linux-64)}
     libedit  {3.1.20181209 -> 3.1.20181209 (defaults/linux-64)}
     libffi  {3.2.1 -> 3.2.1 (defaults/linux-64)}
     libgcc-ng  {9.1.0 -> 9.1.0 (defaults/linux-64)}
     libstdcxx-ng  {9.1.0 -> 9.1.0 (defaults/linux-64)}
     ncurses  {6.1 -> 6.2 (defaults/linux-64)}
     openssl  {1.1.1d -> 1.1.1d (defaults/linux-64)}
     pip  {19.3.1 -> 20.0.2 (defaults/linux-64)}
     pycosat  {0.6.3 -> 0.6.3 (defaults/linux-64)}
     pycparser  {2.19 -> 2.19 (defaults/linux-64)}
     pyopenssl  {19.1.0 -> 19.1.0 (defaults/linux-64)}
     pysocks  {1.7.1 -> 1.7.1 (defaults/linux-64)}
     python  {3.7.6 -> 3.7.6 (defaults/linux-64)}
     readline  {7.0 -> 7.0 (defaults/linux-64)}
     requests  {2.22.0 -> 2.22.0 (defaults/linux-64)}
     ruamel_yaml  {0.15.87 -> 0.15.87 (defaults/linux-64)}
     setuptools  {44.0.0 -> 45.2.0 (defaults/linux-64)}
     six  {1.13.0 -> 1.14.0 (defaults/linux-64)}
     sqlite  {3.30.1 -> 3.31.1 (defaults/linux-64)}
     tk  {8.6.8 -> 8.6.8 (defaults/linux-64)}
     tqdm  {4.41.1 -> 4.42.1 (defaults/noarch)}
     urllib3  {1.25.7 -> 1.25.8 (defaults/linux-64)}
     wheel  {0.33.6 -> 0.34.2 (defaults/linux-64)}
     xz  {5.2.4 -> 5.2.4 (defaults/linux-64)}
     yaml  {0.1.7 -> 0.1.7 (defaults/linux-64)}
     zlib  {1.2.11 -> 1.2.11 (defaults/linux-64)}

2020-03-16 12:54:01  (rev 3)
     requests  {2.22.0 (defaults/linux-64) -> 2.23.0 (defaults/linux-64)}
     setuptools  {45.2.0 (defaults/linux-64) -> 46.0.0 (defaults/linux-64)}

2020-05-04 16:52:25  (rev 4)
     certifi  {2019.11.28 (defaults/linux-64) -> 2020.4.5.1 (defaults/linux-64)}
     conda  {4.8.2 (defaults/linux-64) -> 4.8.3 (defaults/linux-64)}
     idna  {2.8 (defaults/linux-64) -> 2.9 (defaults/noarch)}
     ncurses  {6.2 (defaults/linux-64) -> 6.2 (defaults/linux-64)}
     openssl  {1.1.1d (defaults/linux-64) -> 1.1.1g (defaults/linux-64)}
     pycparser  {2.19 (defaults/linux-64) -> 2.20 (defaults/noarch)}
     setuptools  {46.0.0 (defaults/linux-64) -> 46.1.3 (defaults/linux-64)}
     sqlite  {3.31.1 (defaults/linux-64) -> 3.31.1 (defaults/linux-64)}
     tqdm  {4.42.1 (defaults/noarch) -> 4.45.0 (defaults/noarch)}
     xz  {5.2.4 (defaults/linux-64) -> 5.2.5 (defaults/linux-64)}

2020-09-18 13:28:32  (rev 5)
     ca-certificates  {2020.1.1 (defaults/linux-64) -> 2020.7.22 (defaults/linux-64)}
     certifi  {2020.4.5.1 (defaults/linux-64) -> 2020.6.20 (defaults/linux-64)}
     cffi  {1.14.0 (defaults/linux-64) -> 1.14.2 (defaults/linux-64)}
     conda  {4.8.3 (defaults/linux-64) -> 4.8.4 (defaults/linux-64)}
     conda-package-handling  {1.6.0 (defaults/linux-64) -> 1.6.1 (defaults/linux-64)}
     cryptography  {2.8 (defaults/linux-64) -> 3.1 (defaults/linux-64)}
     idna  {2.9 (defaults/noarch) -> 2.10 (defaults/noarch)}
     libedit  {3.1.20181209 (defaults/linux-64) -> 3.1.20191231 (defaults/linux-64)}
     libffi  {3.2.1 (defaults/linux-64) -> 3.3 (defaults/linux-64)}
     pip  {20.0.2 (defaults/linux-64) -> 20.2.2 (defaults/linux-64)}
     pycparser  {2.20 (defaults/noarch) -> 2.20 (defaults/noarch)}
     pyopenssl  {19.1.0 (defaults/linux-64) -> 19.1.0 (defaults/noarch)}
     pysocks  {1.7.1 (defaults/linux-64) -> 1.7.1 (defaults/linux-64)}
     requests  {2.23.0 (defaults/linux-64) -> 2.24.0 (defaults/noarch)}
     ruamel_yaml  {0.15.87 (defaults/linux-64) -> 0.15.87 (defaults/linux-64)}
     setuptools  {46.1.3 (defaults/linux-64) -> 49.6.0 (defaults/linux-64)}
     six  {1.14.0 (defaults/linux-64) -> 1.15.0 (defaults/noarch)}
     sqlite  {3.31.1 (defaults/linux-64) -> 3.33.0 (defaults/linux-64)}
     tk  {8.6.8 (defaults/linux-64) -> 8.6.10 (defaults/linux-64)}
     tqdm  {4.45.0 (defaults/noarch) -> 4.48.2 (defaults/noarch)}
     urllib3  {1.25.8 (defaults/linux-64) -> 1.25.10 (defaults/noarch)}
     wheel  {0.34.2 (defaults/linux-64) -> 0.35.1 (defaults/noarch)}
     yaml  {0.1.7 (defaults/linux-64) -> 0.2.5 (defaults/linux-64)}
    -asn1crypto-1.3.0 (defaults/linux-64)
    +brotlipy-0.7.0 (defaults/linux-64)

2020-09-22 11:24:29  (rev 6)
     cffi  {1.14.2 (defaults/linux-64) -> 1.14.3 (defaults/linux-64)}
     conda  {4.8.4 (defaults/linux-64) -> 4.8.5 (defaults/linux-64)}
     openssl  {1.1.1g (defaults/linux-64) -> 1.1.1h (defaults/linux-64)}
     tqdm  {4.48.2 (defaults/noarch) -> 4.49.0 (defaults/noarch)}

2020-09-22 11:26:01  (rev 7)

2020-10-02 13:00:04  (rev 8)
    +_libgcc_mutex-0.1 (defaults/linux-64)
    +boost-1.74.0 (conda-forge/linux-64)
    +boost-cpp-1.74.0 (conda-forge/linux-64)
    +brotlipy-0.7.0 (defaults/linux-64)
    +bzip2-1.0.8 (conda-forge/linux-64)
    +ca-certificates-2020.6.20 (conda-forge/linux-64)
    +cairo-1.16.0 (conda-forge/linux-64)
    +certifi-2020.6.20 (conda-forge/linux-64)
    +cffi-1.14.3 (defaults/linux-64)
    +chardet-3.0.4 (defaults/linux-64)
    +conda-4.8.5 (conda-forge/linux-64)
    +conda-package-handling-1.6.1 (defaults/linux-64)
    +cryptography-3.1 (defaults/linux-64)
    +fontconfig-2.13.1 (conda-forge/linux-64)
    +freetype-2.10.2 (conda-forge/linux-64)
    +glib-2.65.0 (defaults/linux-64)
    +icu-67.1 (conda-forge/linux-64)
    +idna-2.10 (defaults/noarch)
    +jpeg-9d (conda-forge/linux-64)
    +lcms2-2.11 (conda-forge/linux-64)
    +ld_impl_linux-64-2.33.1 (defaults/linux-64)
    +libblas-3.8.0 (conda-forge/linux-64)
    +libcblas-3.8.0 (conda-forge/linux-64)
    +libedit-3.1.20191231 (defaults/linux-64)
    +libffi-3.3 (defaults/linux-64)
    +libgcc-ng-9.1.0 (defaults/linux-64)
    +libgfortran-ng-7.5.0 (conda-forge/linux-64)
    +libiconv-1.16 (conda-forge/linux-64)
    +liblapack-3.8.0 (conda-forge/linux-64)
    +libopenblas-0.3.10 (conda-forge/linux-64)
    +libpng-1.6.37 (conda-forge/linux-64)
    +libstdcxx-ng-9.1.0 (defaults/linux-64)
    +libtiff-4.1.0 (conda-forge/linux-64)
    +libuuid-2.32.1 (conda-forge/linux-64)
    +libwebp-base-1.1.0 (conda-forge/linux-64)
    +libxcb-1.13 (conda-forge/linux-64)
    +libxml2-2.9.10 (conda-forge/linux-64)
    +lz4-c-1.9.2 (conda-forge/linux-64)
    +ncurses-6.2 (defaults/linux-64)
    +numpy-1.19.1 (conda-forge/linux-64)
    +olefile-0.46 (conda-forge/noarch)
    +openssl-1.1.1h (conda-forge/linux-64)
    +pandas-1.1.2 (conda-forge/linux-64)
    +pcre-8.44 (conda-forge/linux-64)
    +pillow-7.2.0 (conda-forge/linux-64)
    +pip-20.2.2 (defaults/linux-64)
    +pixman-0.38.0 (conda-forge/linux-64)
    +pthread-stubs-0.4 (conda-forge/linux-64)
    +pycairo-1.19.1 (conda-forge/linux-64)
    +pycosat-0.6.3 (defaults/linux-64)
    +pycparser-2.20 (defaults/noarch)
    +pyopenssl-19.1.0 (defaults/noarch)
    +pysocks-1.7.1 (defaults/linux-64)
    +python-3.7.6 (defaults/linux-64)
    +python-dateutil-2.8.1 (conda-forge/noarch)
    +python_abi-3.7 (conda-forge/linux-64)
    +pytz-2020.1 (conda-forge/noarch)
    +rdkit-2020.03.6 (conda-forge/linux-64)
    +readline-7.0 (defaults/linux-64)
    +requests-2.24.0 (defaults/noarch)
    +ruamel_yaml-0.15.87 (defaults/linux-64)
    +setuptools-49.6.0 (defaults/linux-64)
    +six-1.15.0 (defaults/noarch)
    +sqlite-3.33.0 (defaults/linux-64)
    +tk-8.6.10 (defaults/linux-64)
    +tqdm-4.49.0 (defaults/noarch)
    +urllib3-1.25.10 (defaults/noarch)
    +wheel-0.35.1 (defaults/noarch)
    +xorg-kbproto-1.0.7 (conda-forge/linux-64)
    +xorg-libice-1.0.10 (conda-forge/linux-64)
    +xorg-libsm-1.2.3 (conda-forge/linux-64)
    +xorg-libx11-1.6.12 (conda-forge/linux-64)
    +xorg-libxau-1.0.9 (conda-forge/linux-64)
    +xorg-libxdmcp-1.1.3 (conda-forge/linux-64)
    +xorg-libxext-1.3.4 (conda-forge/linux-64)
    +xorg-libxrender-0.9.10 (conda-forge/linux-64)
    +xorg-renderproto-0.11.1 (conda-forge/linux-64)
    +xorg-xextproto-7.3.0 (conda-forge/linux-64)
    +xorg-xproto-7.0.31 (conda-forge/linux-64)
    +xz-5.2.5 (defaults/linux-64)
    +yaml-0.2.5 (defaults/linux-64)
    +zlib-1.2.11 (defaults/linux-64)
    +zstd-1.4.5 (conda-forge/linux-64)

2021-02-18 11:35:16  (rev 9)
     brotlipy  {0.7.0 (defaults/linux-64) -> 0.7.0 (defaults/linux-64)}
     bzip2  {1.0.8 (conda-forge/linux-64) -> 1.0.8 (defaults/linux-64)}
     ca-certificates  {2020.6.20 (conda-forge/linux-64) -> 2021.1.19 (defaults/linux-64)}
     certifi  {2020.6.20 (conda-forge/linux-64) -> 2020.12.5 (defaults/linux-64)}
     cffi  {1.14.3 (defaults/linux-64) -> 1.14.5 (defaults/linux-64)}
     chardet  {3.0.4 (defaults/linux-64) -> 4.0.0 (defaults/linux-64)}
     conda  {4.8.5 (conda-forge/linux-64) -> 4.9.2 (defaults/linux-64)}
     conda-package-handling  {1.6.1 (defaults/linux-64) -> 1.7.2 (defaults/linux-64)}
     cryptography  {3.1 (defaults/linux-64) -> 3.3.1 (defaults/linux-64)}
     freetype  {2.10.2 (conda-forge/linux-64) -> 2.10.4 (defaults/linux-64)}
     glib  {2.65.0 (defaults/linux-64) -> 2.67.4 (defaults/linux-64)}
     idna  {2.10 (defaults/noarch) -> 2.10 (defaults/noarch)}
     jpeg  {9d (conda-forge/linux-64) -> 9b (defaults/linux-64)}
     lcms2  {2.11 (conda-forge/linux-64) -> 2.11 (defaults/linux-64)}
     libpng  {1.6.37 (conda-forge/linux-64) -> 1.6.37 (defaults/linux-64)}
     libtiff  {4.1.0 (conda-forge/linux-64) -> 4.1.0 (defaults/linux-64)}
     libxcb  {1.13 (conda-forge/linux-64) -> 1.14 (defaults/linux-64)}
     lz4-c  {1.9.2 (conda-forge/linux-64) -> 1.9.3 (defaults/linux-64)}
     numpy  {1.19.1 (conda-forge/linux-64) -> 1.19.2 (defaults/linux-64)}
     olefile  {0.46 (conda-forge/noarch) -> 0.46 (defaults/linux-64)}
     openssl  {1.1.1h (conda-forge/linux-64) -> 1.1.1i (defaults/linux-64)}
     pandas  {1.1.2 (conda-forge/linux-64) -> 1.2.1 (defaults/linux-64)}
     pcre  {8.44 (conda-forge/linux-64) -> 8.44 (defaults/linux-64)}
     pillow  {7.2.0 (conda-forge/linux-64) -> 8.1.0 (defaults/linux-64)}
     pip  {20.2.2 (defaults/linux-64) -> 20.3.3 (defaults/linux-64)}
     pycairo  {1.19.1 (conda-forge/linux-64) -> 1.19.1 (defaults/linux-64)}
     pycosat  {0.6.3 (defaults/linux-64) -> 0.6.3 (defaults/linux-64)}
     pyopenssl  {19.1.0 (defaults/noarch) -> 20.0.1 (defaults/noarch)}
     python-dateutil  {2.8.1 (conda-forge/noarch) -> 2.8.1 (defaults/noarch)}
     pytz  {2020.1 (conda-forge/noarch) -> 2021.1 (defaults/noarch)}
     requests  {2.24.0 (defaults/noarch) -> 2.25.1 (defaults/noarch)}
     setuptools  {49.6.0 (defaults/linux-64) -> 52.0.0 (defaults/linux-64)}
     six  {1.15.0 (defaults/noarch) -> 1.15.0 (defaults/linux-64)}
     tqdm  {4.49.0 (defaults/noarch) -> 4.56.0 (defaults/noarch)}
     urllib3  {1.25.10 (defaults/noarch) -> 1.26.3 (defaults/noarch)}
     wheel  {0.35.1 (defaults/noarch) -> 0.36.2 (defaults/noarch)}
     xorg-xproto  {7.0.31 (conda-forge/linux-64) -> 7.0.31 (defaults/linux-64)}
     zstd  {1.4.5 (conda-forge/linux-64) -> 1.4.5 (defaults/linux-64)}
    -libblas-3.8.0 (conda-forge/linux-64)
    -libcblas-3.8.0 (conda-forge/linux-64)
    -libgfortran-ng-7.5.0 (conda-forge/linux-64)
    -liblapack-3.8.0 (conda-forge/linux-64)
    -libopenblas-0.3.10 (conda-forge/linux-64)
    -libwebp-base-1.1.0 (conda-forge/linux-64)
    -pthread-stubs-0.4 (conda-forge/linux-64)
    -xorg-libxau-1.0.9 (conda-forge/linux-64)
    -xorg-libxdmcp-1.1.3 (conda-forge/linux-64)
    +blas-1.0 (defaults/linux-64)
    +intel-openmp-2020.2 (defaults/linux-64)
    +mkl-2020.2 (defaults/linux-64)
    +mkl-service-2.3.0 (defaults/linux-64)
    +mkl_fft-1.2.0 (defaults/linux-64)
    +mkl_random-1.1.1 (defaults/linux-64)
    +numpy-base-1.19.2 (defaults/linux-64)

2021-02-18 11:54:43  (rev 10)
     openssl  {1.1.1i (defaults/linux-64) -> 1.1.1j (defaults/linux-64)}

2021-02-26 11:21:32  (rev 11)
     mkl_fft  {1.2.0 (defaults/linux-64) -> 1.2.1 (defaults/linux-64)}
     pandas  {1.2.1 (defaults/linux-64) -> 1.2.2 (defaults/linux-64)}
     pip  {20.3.3 (defaults/linux-64) -> 21.0.1 (defaults/linux-64)}
     pycairo  {1.19.1 (defaults/linux-64) -> 1.19.1 (defaults/linux-64)}

2021-09-02 11:03:41  (rev 12)
     ca-certificates  {2021.1.19 (defaults/linux-64) -> 2021.7.5 (defaults/linux-64)}
     certifi  {2020.12.5 (defaults/linux-64) -> 2021.5.30 (defaults/linux-64)}
     cffi  {1.14.5 (defaults/linux-64) -> 1.14.6 (defaults/linux-64)}
     conda  {4.9.2 (defaults/linux-64) -> 4.10.3 (defaults/linux-64)}
     conda-package-handling  {1.7.2 (defaults/linux-64) -> 1.7.3 (defaults/linux-64)}
     cryptography  {3.3.1 (defaults/linux-64) -> 3.4.7 (defaults/linux-64)}
     glib  {2.67.4 (defaults/linux-64) -> 2.69.1 (defaults/linux-64)}
     idna  {2.10 (defaults/noarch) -> 3.2 (defaults/noarch)}
     intel-openmp  {2020.2 (defaults/linux-64) -> 2021.3.0 (defaults/linux-64)}
     lcms2  {2.11 (defaults/linux-64) -> 2.12 (defaults/linux-64)}
     ld_impl_linux-64  {2.33.1 (defaults/linux-64) -> 2.35.1 (defaults/linux-64)}
     libedit  {3.1.20191231 (defaults/linux-64) -> 3.1.20210714 (defaults/linux-64)}
     libgcc-ng  {9.1.0 (defaults/linux-64) -> 9.3.0 (defaults/linux-64)}
     libstdcxx-ng  {9.1.0 (defaults/linux-64) -> 9.3.0 (defaults/linux-64)}
     libtiff  {4.1.0 (defaults/linux-64) -> 4.2.0 (defaults/linux-64)}
     lz4-c  {1.9.3 (defaults/linux-64) -> 1.9.3 (defaults/linux-64)}
     mkl  {2020.2 (defaults/linux-64) -> 2021.3.0 (defaults/linux-64)}
     mkl-service  {2.3.0 (defaults/linux-64) -> 2.4.0 (defaults/linux-64)}
     mkl_fft  {1.2.1 (defaults/linux-64) -> 1.3.0 (defaults/linux-64)}
     mkl_random  {1.1.1 (defaults/linux-64) -> 1.2.2 (defaults/linux-64)}
     numpy  {1.19.2 (defaults/linux-64) -> 1.20.3 (defaults/linux-64)}
     numpy-base  {1.19.2 (defaults/linux-64) -> 1.20.3 (defaults/linux-64)}
     openssl  {1.1.1j (defaults/linux-64) -> 1.1.1k (defaults/linux-64)}
     pandas  {1.2.2 (defaults/linux-64) -> 1.3.2 (defaults/linux-64)}
     pcre  {8.44 (defaults/linux-64) -> 8.45 (defaults/linux-64)}
     pillow  {8.1.0 (defaults/linux-64) -> 8.3.1 (defaults/linux-64)}
     python-dateutil  {2.8.1 (defaults/noarch) -> 2.8.2 (defaults/noarch)}
     requests  {2.25.1 (defaults/noarch) -> 2.26.0 (defaults/noarch)}
     ruamel_yaml  {0.15.87 (defaults/linux-64) -> 0.15.100 (defaults/linux-64)}
     six  {1.15.0 (defaults/linux-64) -> 1.16.0 (defaults/noarch)}
     tqdm  {4.56.0 (defaults/noarch) -> 4.62.1 (defaults/noarch)}
     urllib3  {1.26.3 (defaults/noarch) -> 1.26.6 (defaults/noarch)}
     wheel  {0.36.2 (defaults/noarch) -> 0.37.0 (defaults/noarch)}
     zstd  {1.4.5 (defaults/linux-64) -> 1.4.9 (defaults/linux-64)}
    -chardet-4.0.0 (defaults/linux-64)
    +_openmp_mutex-4.5 (defaults/linux-64)
    +bottleneck-1.3.2 (defaults/linux-64)
    +charset-normalizer-2.0.4 (defaults/noarch)
    +libgomp-9.3.0 (defaults/linux-64)
    +libwebp-base-1.2.0 (defaults/linux-64)
    +numexpr-2.7.3 (defaults/linux-64)
    +openjpeg-2.4.0 (defaults/linux-64)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name	: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
64
- RAM: `grep "^MemTotal" /proc/meminfo`
MemTotal:       263849352 kB
- OS: `cat /etc/os-release`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

## Debugging information
- [X] `gtdbtk.log` has been included (drag and drop the file to upload).
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/7281481/gtdbtk.log)
- [ ] Genomes have been included (if possible, and there are few).

**Comment by kevinmyers** [comment]
I realized I was using a Node on our server cluster with too little RAM. I have gotten it to work fine when I increase the available RAM. Closing now.
