### ISSUE TITLE
Function not implemented - Error 38

### ISSUE THREAD

**Issue by ntromas** [Ecogenomics/GTDBTk#365]
Hi,

First of all, I hope  this pb was not already reported... I got this issue and the markers summary file seems well generated and is not empty. Each genomes has unique genes...
Thanks for your help!

Nico

_MESSAGE: [Errno 38] Function not implemented: 'identify/gtdbtk.bac120.markers_summary.tsv' -> 'GTDBTK_out/gtdbtk.bac120.markers_summary.tsv'_

GTDB-Tk information:
Conda installation
Reference 202
Version 1.7.0

Command used:
gtdbtk classify_wf --genome_dir GENOMES/ --out_dir GTDBTK_out --cpus 6 --pplacer_cpus 1 -x fa --scratch_dir GTDBK_pplcare_tmp/

Log:
[2022-01-27 10:08:54] INFO: GTDB-Tk v1.7.0
[2022-01-27 10:08:54] INFO: gtdbtk classify_wf --genome_dir GENOMES/ --out_dir GTDBTK_out --cpus 6 --pplacer_cpus 1 -x fa --scratch_dir GTDBK_pplcare_tmp/
[2022-01-27 10:08:54] INFO: Using GTDB-Tk reference data version r202: /media/nico/MyBook/GTDBTK/release202/
[2022-01-27 10:08:54] INFO: Identifying markers in 263 genomes with 6 threads.
[2022-01-27 10:08:54] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-01-27 10:28:36] INFO: Completed 263 genomes in 19.70 minutes (13.35 genomes/minute).
[2022-01-27 10:28:36] TASK: Identifying TIGRFAM protein families.                
[2022-01-27 10:34:51] INFO: Completed 263 genomes in 6.24 minutes (42.13 genomes/minute).
[2022-01-27 10:34:51] TASK: Identifying Pfam protein families.                   
[2022-01-27 10:35:39] INFO: Completed 263 genomes in 48.36 seconds (5.44 genomes/second).
[2022-01-27 10:35:39] INFO: Annotations done using HMMER 3.1b2 (February 2015).  
[2022-01-27 10:35:39] TASK: Summarising identified marker genes.
[2022-01-27 10:35:49] INFO: Completed 263 genomes in 9.46 seconds (27.80 genomes/second).
[2022-01-27 10:35:49] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: OSError
  MESSAGE: [Errno 38] Function not implemented: 'identify/gtdbtk.bac120.markers_summary.tsv' -> 'GTDBTK_out/gtdbtk.bac120.markers_summary.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 734, in parse_options
    self.identify(options)
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 219, in identify
    self._report_identified_marker_genes(genome_dictionary, out_dir, prefix,
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 109, in _report_identified_marker_genes
    symlink_f(PATH_BAC120_MARKER_SUMMARY.format(prefix=prefix),
  File "/home/nico/miniconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/tools.py", line 200, in symlink_f
    os.symlink(src, dst)
OSError: [Errno 38] Function not implemented: 'identify/gtdbtk.bac120.markers_summary.tsv' -> 'GTDBTK_out/gtdbtk.bac120.markers_summary.tsv'

Computer info
- CPU:  Intel 28 proc
- RAM: 128 Go
- OS:  Ubuntu 20.04.3 LTS

**Comment by pchaumeil** [comment]
Hello,
Apologies for the delay,
Is this still an issue?

Thanks

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
