### ISSUE TITLE
"AttributeError" during Prodigal step

### ISSUE THREAD

**Issue by robporch** [Ecogenomics/GTDBTk#366]
Hi,
I'm running the de_novo_wf command and I keep running into an error during the Prodigal step.
I'm using GTDBTk v1.3.0 with Release 95 reference data.

Code:
gtdbtk de_novo_wf --genome_dir select_genomes1/ --extension fasta --outgroup_taxon p__Chloroflexota --bacteria --custom_taxonomy_file genomes_for_Rob/genome_metadata.tsv --out_dir select_genomes1/output

Log:
[2022-02-08 15:07:39] INFO: Using GTDB-Tk reference data version r95: /Users/Shared/Bioinformatics_data/GTDBtk/GTDBtk_r95/release95
[2022-02-08 15:07:39] WARNING: You are not using the reference data intended for this release: r202
[2022-02-08 15:07:39] INFO: Identifying markers in 182 genomes with 1 threads.
[2022-02-08 15:07:39] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/182 genomes (0%) |               | [?genome/s, ETA ?]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'Parallel' object has no attribute '__process_manager'

Any help would be appreciated.

Thank you!
Rob

**Comment by pchaumeil** [comment]
Hello,
Apologies for the delay,
Is this still an issue?

Thanks

**Comment by tmesut** [comment]
Hello,
I have also similar error. I followed the example steps they are mentioned in your example page and I took this error:

(gtdbtk) turgutyilmaz@Turguts-iMac test1 % gtdbtk identify --genome_dir genomes --out_dir identify --cpus 4
[2024-06-28 14:44:58] INFO: GTDB-Tk v2.4.0
[2024-06-28 14:44:58] INFO: gtdbtk identify --genome_dir genomes --out_dir identify --cpus 4
[2024-06-28 14:44:58] INFO: Using GTDB-Tk reference data version r220: /opt/anaconda3/envs/gtdbtk/share/gtdbtk-2.4.0/db
[2024-06-28 14:44:58] INFO: Identifying markers in 2 genomes with 1 threads.
[2024-06-28 14:44:58] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/2 genomes (0%) |               | [?genome/s, ETA ?]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/gtdbtk/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/envs/gtdbtk/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'Parallel' object has no attribute '__process_manager'

Thank you for your time and attention.

Best regards
Turgut
