### ISSUE TITLE
libgsl.so.25 not found - FastANI

### ISSUE THREAD

**Issue by rhysnewell** [Ecogenomics/GTDBTk#370]
Hey Aaron & team,

We seem to be running into this issue with fresh installs of gtdb-tk: https://github.com/ParBLiSS/FastANI/issues/96
Not sure but this might be an issue with a conda update that you've recently pushed? Maybe gsl isn't being installed properly. `echo $LD_LIBRARY_PATH` returns nothing in both new installations and working old installations of gtdb-tk, so not sure why it has started complaining about a missing shared library now.

Additional details provided below.

Cheers,
Rhys

Error:
```
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/conda/cefdf9f2d339be6c23ee5efbdea39be9/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/mnt/hpccs01/work/microbiome/conda/cefdf9f2d339be6c23ee5efbdea39be9/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/hpccs01/work/microbiome/conda/cefdf9f2d339be6c23ee5efbdea39be9/lib/python3.10/site-packages/gtdbtk/external/fastani.py", line 224, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/mnt/hpccs01/work/microbiome/conda/cefdf9f2d339be6c23ee5efbdea39be9/lib/python3.10/site-packages/gtdbtk/external/fastani.py", line 285, in run_proc
    raise GTDBTkExit('FastANI returned a non-zero exit code.')
gtdbtk.exceptions.GTDBTkExit: FastANI returned a non-zero exit code.
[2022-03-29 15:58:14] ERROR: STDOUT:
[2022-03-29 15:58:14] ERROR: STDERR:
fastANI: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
```

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: 
```
model name      : AMD EPYC 7702 64-Core Processor
128
```
- RAM: 
```
MemTotal:       1056360120 kB
```
- OS: 
```
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"
```

conda list:
```
# packages in environment at /mnt/hpccs01/work/microbiome/conda/cefdf9f2d339be6c23ee5efbdea39be9:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blas                      1.0                    openblas
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2022.3.18            h06a4308_0
capnproto                 0.9.1                h4ff587b_0
certifi                   2021.10.8                pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
dendropy                  4.5.2                    pypi_0    pypi
fastani                   1.33                 h0fdf51a_0    bioconda
fasttree                  2.1.11               hec16e2b_1    bioconda
gsl                       2.7                  he838d99_0    conda-forge
gtdbtk                    1.7.0                    pypi_0    pypi
hmmer                     3.1b2                         3    bioconda
ld_impl_linux-64          2.35.1               h7274673_9
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            11.2.0              h69a702a_14    conda-forge
libgfortran5              11.2.0              h5c6108e_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libuuid                   1.0.3                h7f8727e_2
libzlib                   1.2.11            h166bdaf_1014    conda-forge
mash                      2.3                  ha9a2dd8_3    bioconda
ncurses                   6.3                  h7f8727e_2
numpy                     1.21.2                   pypi_0    pypi
numpy-base                1.21.2          py310h2b8c604_0
openssl                   1.1.1n               h166bdaf_0    conda-forge
pip                       21.2.4                   pypi_0    pypi
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                hec16e2b_4    bioconda
python                    3.10.3               h12debd9_5
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h7f8727e_1
setuptools                58.0.4                   pypi_0    pypi
sqlite                    3.38.0               hc218d9a_0
tk                        8.6.11               h1ccaba5_0
tqdm                      4.63.0                   pypi_0    pypi
tzdata                    2021e                hda174b7_0
wheel                     0.37.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

Revisions:
```
2022-03-29 10:05:42  (rev 0)
    +_libgcc_mutex-0.1 (conda-forge/linux-64)
    +_openmp_mutex-4.5 (conda-forge/linux-64)
    +blas-1.0 (defaults/linux-64)
    +bzip2-1.0.8 (defaults/linux-64)
    +ca-certificates-2022.3.18 (defaults/linux-64)
    +capnproto-0.9.1 (defaults/linux-64)
    +certifi-2021.5.30 (defaults/linux-64)
    +colorama-0.4.4 (defaults/noarch)
    +dendropy-4.5.2 (bioconda/noarch)
    +fastani-1.33 (bioconda/linux-64)
    +fasttree-2.1.11 (bioconda/linux-64)
    +gsl-2.7.1 (defaults/linux-64)
    +gtdbtk-1.7.0 (bioconda/noarch)
    +hmmer-3.1b2 (bioconda/linux-64)
    +ld_impl_linux-64-2.35.1 (defaults/linux-64)
    +libblas-3.9.0 (conda-forge/linux-64)
    +libcblas-3.9.0 (conda-forge/linux-64)
    +libffi-3.3 (defaults/linux-64)
    +libgcc-ng-11.2.0 (conda-forge/linux-64)
    +libgfortran-ng-11.2.0 (conda-forge/linux-64)
    +libgfortran5-11.2.0 (conda-forge/linux-64)
    +libgomp-11.2.0 (conda-forge/linux-64)
    +libopenblas-0.3.18 (conda-forge/linux-64)
    +libstdcxx-ng-11.2.0 (conda-forge/linux-64)
    +libuuid-1.0.3 (defaults/linux-64)
    +libzlib-1.2.11 (conda-forge/linux-64)
    +mash-2.3 (bioconda/linux-64)
    +ncurses-6.3 (defaults/linux-64)
    +numpy-1.21.2 (defaults/linux-64)
    +numpy-base-1.21.2 (defaults/linux-64)
    +openssl-1.1.1n (defaults/linux-64)
    +pip-21.2.4 (defaults/linux-64)
    +pplacer-1.1.alpha19 (bioconda/linux-64)
    +prodigal-2.6.3 (bioconda/linux-64)
    +python-3.10.3 (defaults/linux-64)
    +readline-8.1.2 (defaults/linux-64)
    +setuptools-58.0.4 (defaults/linux-64)
    +sqlite-3.38.0 (defaults/linux-64)
    +tk-8.6.11 (defaults/linux-64)
    +tqdm-4.63.0 (defaults/noarch)
    +tzdata-2021e (defaults/noarch)
    +wheel-0.37.1 (defaults/noarch)
    +xz-5.2.5 (defaults/linux-64)
    +zlib-1.2.11 (conda-forge/linux-64)

2022-03-30 09:06:09  (rev 1)
     certifi  {2021.5.30 (defaults/linux-64) -> 2021.10.8 (conda-forge/linux-64)}
     gsl  {2.7.1 (defaults/linux-64) -> 2.7 (conda-forge/linux-64)}
     openssl  {1.1.1n (defaults/linux-64) -> 1.1.1n (conda-forge/linux-64)}
    +python_abi-3.10 (conda-forge/linux-64)
```

**Comment by aaronmussig** [comment]
Hi Rhys,

Thanks for bringing this to our attention! I suspect this is due to the latest conda recipe for FastANI being buggy since it was only updated less than a month ago.

I'll try fix the recipe or fix the version in GTDB-Tk to <1.33 today. Cheers!

**Comment by rhysnewell** [comment]
Good stuff, yeah figured it would be just a versioning issue.

Sidenote: How'd you make your GitHub issue opening stuff so fancy? Automatic labels? Issue pre-ambles? So good, teach me how 😆

**Comment by aaronmussig** [comment]
It's a bit of but it's nice to have, it cuts out a bit of the faq: [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) or [commit directly to the repo](https://github.com/Ecogenomics/GTDBTk/tree/master/.github/ISSUE_TEMPLATE)... which after glancing at the docs seems to be the old school way now

**Comment by rhysnewell** [comment]
Downgrading FastANI to v1.32 works, but it requires the entire conda environment to have to be recreated. I'll close this now and let the FastANI people know
