### ISSUE TITLE
Prodigal Error 

### ISSUE THREAD

**Issue by cwood15** [Ecogenomics/GTDBTk#375]
## Environment
Installed using conda

## I have successfully run GTDB-Tk on my concoct bins with the same installation on the same server. This issue only occurs when running on bins that were binned using MetaBat. The bins output by MetaBat were originally named with the format "bin.1.fa"    I changed their names to be "1.fa" because I thought maybe that was the issue but that did not change anything. 
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/8444737/gtdbtk.log)

## Debugging information
- [ ] `gtdbtk.log` has been included 

##Error
metabat
[2022-04-07 11:58:33] INFO: GTDB-Tk v1.5.0
[2022-04-07 11:58:33] INFO: gtdbtk identify --genome_dir . --out_dir gtdbk_identify --extension fa --cpus 5 --prefix S3-010_metabat
[2022-04-07 11:58:33] INFO: Using GTDB-Tk reference data version r202: /home/cwood/miniconda3/envs/GTDB/share/gtdbtk-1.5.0/db/
[2022-04-07 11:58:33] INFO: Identifying markers in 14 genomes with 5 threads.
[2022-04-07 11:58:33] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/14 genomes (0%) |               | [?genome/s, ETA ?][2022-04-07 11:58:33] WARNING: Cannot call Prodigal on an empty genome. Skipped: ./tooShort.fa
Process Process-3:
Traceback (most recent call last):
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/external/prodigal.py", line 143, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/external/prodigal.py", line 109, in _run_prodigal
    raise Exception("An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
==> Processed 10/14 genomes (71%) |██████████▋    | [ 2.42s/genome, ETA 00:09][2022-04-07 11:58:58] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/external/prodigal.py", line 211, in run
    raise ProdigalException('Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/__main__.py", line 95, in main
    gt_parser.parse_options(args)
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/main.py", line 720, in parse_options
    self.identify(options)
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/main.py", line 254, in identify
    markers.identify(genomes,
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/markers.py", line 192, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/home/cwood/miniconda3/envs/GTDB/lib/python3.10/site-packages/gtdbtk/external/prodigal.py", line 220, in run
    raise ProdigalException(f'An exception was caught while running Prodigal: {e}')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.

## Additional comments
##my install is good and works with bins binned with Concoct. 
bins1500-20220406_125450$ gtdbtk check_install
[2022-04-07 11:45:43] INFO: GTDB-Tk v1.5.0
[2022-04-07 11:45:43] INFO: gtdbtk check_install
[2022-04-07 11:45:43] INFO: Using GTDB-Tk reference data version r202: /home/cwood/miniconda3/envs/GTDB/share/gtdbtk-1.5.0/db/
[2022-04-07 11:45:43] INFO: Running install verification
[2022-04-07 11:45:43] INFO: Checking that all third-party software are on the system path:
[2022-04-07 11:45:43] INFO:          |-- FastTree         OK
[2022-04-07 11:45:43] INFO:          |-- FastTreeMP       OK
[2022-04-07 11:45:43] INFO:          |-- fastANI          OK
[2022-04-07 11:45:43] INFO:          |-- guppy            OK
[2022-04-07 11:45:43] INFO:          |-- hmmalign         OK
[2022-04-07 11:45:43] INFO:          |-- hmmsearch        OK
[2022-04-07 11:45:43] INFO:          |-- mash             OK
[2022-04-07 11:45:43] INFO:          |-- pplacer          OK
[2022-04-07 11:45:43] INFO:          |-- prodigal         OK
[2022-04-07 11:45:43] INFO: Checking integrity of reference package: /home/cwood/miniconda3/envs/GTDB/share/gtdbtk-1.5.0/db/
[2022-04-07 11:45:44] INFO:          |-- pplacer          OK                                        
[2022-04-07 11:45:44] INFO:          |-- masks            OK                                        
[2022-04-07 11:45:45] INFO:          |-- markers          OK                                        
[2022-04-07 11:45:45] INFO:          |-- radii            OK                                        
[2022-04-07 11:45:48] INFO:          |-- msa              OK                                        
[2022-04-07 11:45:48] INFO:          |-- metadata         OK                                        
[2022-04-07 11:45:48] INFO:          |-- taxonomy         OK                                        
[/home/cwood/miniconda3/envs/GTDB/share/gtdbtk-1.5.0/db/fastani/] - 17505/47895 files (36.55%)^[[A^[[A^[[A^[[A^[[A^[[A^[[A[/home/cwood/miniconda3/envs/GTDB/share/gtdbtk-1.5.0/db/fastani/] - 17508/47895 files (36.55%)^[[A^[[A^[[A^[[A^[[A^[[A^[[A[2022-04-07 11:54:46] INFO:          |-- fastani          OK                                        [A^[[A^[[A^[[A
[2022-04-07 11:54:46] INFO:          |-- mrca_red         OK                                        
[2022-04-07 11:54:46] INFO: Done.

##thank you

**Comment by pchaumeil** [comment]
Hello ,

it looks like one of your .fa file is empty (`WARNING: Cannot call Prodigal on an empty genome. Skipped: ./tooShort.fa`).
Prodigal returns an error cause of this file and crashes.

Please try to remove this `tooShort.fa` file from the genome directory and run the command again

**Comment by cwood15** [comment]
Okay thank you! Removing the empty pasta resulted in a mismatch or something at another step, but I fixed it by running with the --force option.
