### ISSUE TITLE
inconsistent naming in prodigal-generated .faa file

### ISSUE THREAD

**Issue by cheberling** [Ecogenomics/GTDBTk#39]
When gtdbtk calls prodigal it calls the resulting .faa file <genome_basename>_protein.faa, but then the next step in the workflow searches for <genome_basename>_genes.faa and can't find it!  I can't simply rename the file and then run the workflow again because the file is deleted automatically.

HMMER then seems to have issues with integer division or modulo by zero when looking for TIGRfams and pfams (related to inability to find correct file or something separate?).

**Comment by pchaumeil** [comment]
Hi, 

Could you please send me the command line you are running and the error you generate?

Thanks,
Pierre

**Comment by cheberling** [comment]
command:
gtdbtk classify_wf -x fasta --genome_dir /nfs/vedanta/vbi_san1/data/lbp_cocktails/ve800/genomes_hybrid/gtdbtk_test --out_dir /nfs/vedanta/vbi_san1/data/lbp_cocktails/ve800/genomes_hybrid/gtdbtk_test --cpus 8

[2018-09-12 18:52:10] INFO: Identifying markers in 1 genomes with 8 threads.
[2018-09-12 18:52:10] INFO: Identifying markers in 1 genomes with 8 threads.
[2018-09-12 18:52:10] INFO: Identifying markers in 1 genomes with 8 threads.
[2018-09-12 18:52:10] INFO: Identifying markers in 1 genomes with 8 threads.
[2018-09-12 18:52:10] INFO: Running Prodigal to identify genes.
[2018-09-12 18:52:10] INFO: Running Prodigal to identify genes.
[2018-09-12 18:52:10] INFO: Running Prodigal to identify genes.
[2018-09-12 18:52:10] INFO: Running Prodigal to identify genes.
[2018-09-12 18:52:42] INFO: Identifying TIGRFAM protein families.
[2018-09-12 18:52:42] INFO: Identifying TIGRFAM protein families.
**[2018-09-12 18:52:42] ERROR: integer division or modulo by zero**
[2018-09-12 18:52:58] INFO: Identifying TIGRFAM protein families.
[**2018-09-12 18:52:58] ERROR: integer division or modulo by zero**
[2018-09-12 18:52:58] INFO: Identifying Pfam protein families.
[2018-09-12 18:52:58] INFO: Identifying TIGRFAM protein families.
**[2018-09-12 18:52:58] ERROR: integer division or modulo by zero**
[2018-09-12 18:53:02] INFO: Done.
[2018-09-12 18:53:02] INFO: Aligning markers in 1 genomes with 8 threads.
[2018-09-12 18:53:02] INFO: Processing 1 genomes identified as bacterial.
[2018-09-12 18:53:13] INFO: Read concatenated alignment for 21263 GTDB genomes.
[2018-09-12 18:53:23] INFO: Masking columns of multiple sequence alignment.
[2018-09-12 18:54:22] INFO: Masked alignment from 41155 to 5035 AA.
[2018-09-12 18:54:22] INFO: Creating concatenated alignment for 21264 taxa.
[2018-09-12 18:54:25] INFO: Done.
[2018-09-12 18:54:25] INFO: Placing 1 bacterial genomes into reference tree with pplacer (be patient).

Traceback (most recent call last):
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 100, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/prodigal.py", line 68, in _run_prodigal
    shutil.move(summary_stats.aa_gene_file, aa_gene_file)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/shutil.py", line 316, in move
    copy2(src, real_dst)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
**IOError: [Errno 2] No such file or directory: '/nfs/vedanta/vbi_san1/data/lbp_cocktails/ve800/genomes_hybrid/gtdbtk_test/marker_genes/ve800_82B1_hybrid_assembly_complete/ve800_82B1_hybrid_assembly_complete_genes.faa'**

**Comment by cheberling** [comment]
When running on a different compute node I no longer get that error, but I'm having problems with the software being able to see Moose.pm.  The recommended install for the Moose perl module did not install any file called 'Moose.pm'.  I downloaded from the Moose github page (https://github.com/moose/Moose/edit/master/lib/Moose.pm) and added the filepath to @inc via $PERL5LIB, but the program still can't find it.  It appears to affect finding pfams only, and then the workflow continues?  The final classification still seems to be what I would expect.  Is the pfam step always needed?

**Comment by cheberling** [comment]
Installed Moose via "sudo cpan Moose", then added install path to @inc, then everything worked fine.
