### ISSUE TITLE
Unable to get mask from hmm align result file... still problematic

### ISSUE THREAD

**Issue by GreatScissors** [Ecogenomics/GTDBTk#42]
[2018-09-13 13:10:29] INFO: GTDB-Tk v0.1.1
[2018-09-13 13:10:29] INFO: gtdbtk classify_wf --genome_dir ./sampleGenome --out_dir gtdbtkOutput -x fasta
[2018-09-13 13:10:29] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2018-09-13 13:10:29] INFO: Identifying markers in 1 genomes with 1 threads.
[2018-09-13 13:10:29] INFO: Running Prodigal to identify genes.
==> Finished processing 1 of 1 (100.0%) genomes.
[2018-09-13 13:10:46] INFO: Identifying TIGRFAM protein families.
==> Finished processing 1 of 1 (100.0%) genomes.
[2018-09-13 13:10:55] INFO: Identifying Pfam protein families.
==> Finished processing 1 of 1 (100.0%) genomes.
[2018-09-13 13:11:00] INFO: Done.
[2018-09-13 13:11:00] INFO: Aligning markers in 1 genomes with 1 threads.
[2018-09-13 13:11:00] INFO: Processing 1 genomes identified as bacterial.
[2018-09-13 13:11:08] INFO: Read concatenated alignment for 21263 GTDB genomes.
Process Process-9:
Traceback (most recent call last):
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/hmm_aligner.py", line 96, in _worker
    marker_set_id)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/hmm_aligner.py", line 192, in _run_multi_align
    result_aligns.get(db_genome_id).update(self._run_align(gene_dict, db_genome_id))
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/hmm_aligner.py", line 229, in _run_align
    result = self._get_aligned_marker(marker_info.get("gene"), proc.stdout)
  File "/nfs/vedanta/sw/packages/miniconda2/lib/python2.7/site-packages/gtdbtk/external/hmm_aligner.py", line 268, in _get_aligned_marker
    raise Exception("Unable to get mask from hmm align result file")
Exception: Unable to get mask from hmm align result file

**Comment by dparks1134** [comment]
Have you been able to resolve this issue?

**Comment by GreatScissors** [comment]
I haven't been able to resolve this issue.

**Comment by dparks1134** [comment]
Can you make sure HMMer is on your path. Specifically, hmmscan. Can you also try setting the min_perc_aa parameter to 1? Perhaps your genome doesn't have any marker genes and this is causing the issue.

**Comment by GreatScissors** [comment]
This is contained in my .bashrc file:

export PATH="/nfs/vedanta/sw/packages/hmmer-3.2.1/bin:$PATH"

My colleague was able to successfully run the software on our cluster with the same genome dataset I am using, so I am unsure about the issue.

**Comment by dparks1134** [comment]
We are currently using HMMer 3.1b. Is your colleague also using this previous version of HMMer? We will test out the new version at some point, but it will likely take a bit of time.

**Comment by GreatScissors** [comment]
We are using the same hmmer version.

**Comment by dparks1134** [comment]
I'm not sure I can provide any more assistance on this end. It would appear GTDB-Tk works as expected and  it is an installation/configuration issue on your system. I would recommend running each of the dependencies separately just to ensure they run and are properly on your system path. Please let me know if you resolve the issue as it may be useful knowledge to pass along to others.

**Comment by GreatScissors** [comment]
Thanks for you help.  This issue does warrant more troubleshooting on our system.  I suppose the next step is to see if another colleague can run it.

**Comment by GreatScissors** [comment]
By the way, we are quite excited about your software.

**Comment by dparks1134** [comment]
Hope you get it running soon.
