### ISSUE TITLE
maker not found 

### ISSUE THREAD

**Issue by saras224** [Ecogenomics/GTDBTk#421]
Hi @donovan-parks!
I just ran into an error while running the gtdbtk classify_wf command. My command was:
**gtdbtk classify_wf --genome_dir /lustre/rsharma/FLOOR-METAGENOME-NOVASEQ/ASSEMBLY/MAXBIN_REZ/GOOD_QUALITY_BINS/GBINS/ --out_dir /lustre/rsharma/FLOOR-METAGENOME-NOVASEQ/GTDBTK_REZ/**

Terminal output:
![Screenshot from 2022-07-29 18-36-49](https://user-images.githubusercontent.com/77498189/181767227-02687bb9-e1c6-417d-ab1c-6138d2e94208.png)

ERROR:

ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: '/lustre/rsharma/release207_v2/markers/pfam/individual_hmms/PF00380.14.hmm'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/rsharma/anaconda3/envs/gtdbtk/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 623, in parse_options
    self.align(options)
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 263, in align
    markers.align(options.identify_dir,
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 484, in align
    self._write_marker_info(Config.BAC120_MARKERS, bac120_marker_info_file)
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 436, in _write_marker_info
    with open(marker_path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/rsharma/release207_v2/markers/pfam/individual_hmms/PF00380.14.hmm'

It says that a particular maker file is not found in the individual markers directory of PFAM. 

I want to know if this is an error caused due to improper download of the GTDBTK database or something else and also I would like to find the solution for the above issue. 

Thanks in Advance!

**Comment by donovan-parks** [comment]
Hi,

It looks like you are running an old version of GTDB-Tk. The latest version is 2.1.1 which is designed to work with the latest release of GTDB (R207). Unless you have a specific reason to be using GTDB-Tk v1.0.2 can you please upgrade first.

Cheers,
Donovan

**Comment by saras224** [comment]
Thanks @donovan-parks !

But when I am trying to install through bioconda it is not installing the latest version it is installing the old version. How do I upgrade to the latest version of the Gtdbtk database?

**Comment by saras224** [comment]
Hi @donovan-parks!
I successfully upgraded to the latest version of gtdbtk and I ran the classify_wf command, everything was going fine but I think while assigning the ANI values an error occured. 

Command:
gtdbtk classify_wf --genome_dir /lustre/rsharma/FLOOR-METAGENOME-NOVASEQ/ASSEMBLY/MAXBIN_REZ/GOOD_QUALITY_BINS/GBINS/ --extension fasta --out_dir /lustre/rsharma/FLOOR-METAGENOME-NOVASEQ/GTDBTK_REZ/
 
error: ==> Processed 113/1398 comparisons (8%) |█▏             | [ 1.34comparison/s, ETA 15:58]Process Process-30:
Traceback (most recent call last):
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/external/fastani.py", line 224, in _worker
    result = self.run_proc(q, r, path_qry, path_ref, path_out)
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/external/fastani.py", line 278, in run_proc
    proc = subprocess.Popen(args, stdout=subprocess.PIPE,
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/rsharma/anaconda3/envs/gtdbtk/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory
[2022-08-02 15:15:31] ERROR: FastANI returned a non-zero exit code.
[2022-08-02 15:15:31] ERROR: Controlled exit resulting from an unrecoverable error or warning.

![Screenshot from 2022-08-02 15-38-06](https://user-images.githubusercontent.com/77498189/182350341-7d284dc0-de23-49c2-89dd-f0cd4e426069.png)

I am not able to understand what the error is, please explain me the error so that it can be resolved. 

Thanks in advance :) :)

**Comment by donovan-parks** [comment]
The error indicates FastANI (which does ANI calculations) failed at some point. This is pretty unusual and I haven't seen this before. @pchaumeil, have you seen this error message before?

**Comment by pchaumeil** [comment]
Hi,
No I haven't seen this message either in this FastANI step. It seems there is no problem with the installation.
Would it be possible GTDB-Tk was competing with another process for resources( i.e. memory) on this server? If you rerun the pipeline, would it crash at the exact same stage?

**Comment by SheridanPO** [comment]
> Thanks @donovan-parks !
> 
> But when I am trying to install through bioconda it is not installing the latest version it is installing the old version. How do I upgrade to the latest version of the Gtdbtk database?

I seem to be having the same problem. I'm installing with *conda install -c bioconda gtdbtk*, but it keeps installing the old version of GTDBTk (v1.0.2), which is unable to use the pfams from the newest GTDB release.

**Comment by aaronmussig** [comment]
Not sure why it's choosing that version, try force the version to install with `conda install -c bioconda gtdbtk=2.1.1`

**Comment by SheridanPO** [comment]
Thanks! It is working now

**Comment by jolespin** [comment]
Any idea why this could be happening? 

```
[2022-09-30 17:56:28] INFO: GTDB-Tk v2.1.1
[2022-09-30 17:56:28] INFO: gtdbtk classify_wf --genome_dir veba_output/binning/prokaryotic/S005_R2_POST-PE-N728-S516-1_S23/output/genomes/ --pplacer_cpus 1 --out_dir gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23 -x faa --cpus 4 --genes
[2022-09-30 17:56:28] INFO: Using GTDB-Tk reference data version r207: /expanse/projects/jcl110/db/gtdbtk/release207_v2/
[2022-09-30 17:56:29] INFO: Identifying markers in 16 genomes with 4 threads.
[2022-09-30 17:56:29] INFO: Using supplied genomes as called genes, skipping Prodigal.
[2022-09-30 17:56:29] TASK: Identifying TIGRFAM protein families.
[2022-09-30 17:56:42] INFO: Completed 16 genomes in 12.93 seconds (1.24 genomes/second).
[2022-09-30 17:56:42] TASK: Identifying Pfam protein families.
[2022-09-30 17:56:43] INFO: Completed 16 genomes in 1.01 seconds (15.90 genomes/second).
[2022-09-30 17:56:43] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2022-09-30 17:56:43] TASK: Summarising identified marker genes.
[2022-09-30 17:56:43] INFO: Completed 16 genomes in 0.13 seconds (124.12 genomes/second).
[2022-09-30 17:56:43] INFO: Done.
[2022-09-30 17:56:43] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: 'gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23/identify/intermediate_results/marker_genes/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028_protein.faa'
________________________________________________________________________________

Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/main.py", line 832, in parse_options
    self.align(options)
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/main.py", line 294, in align
    markers.align(options.identify_dir,
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/markers.py", line 478, in align
    genomic_files = self._path_to_identify_data(
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/markers.py", line 268, in _path_to_identify_data
    if os.path.getsize(aa_gene_path) < 1:
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23/identify/intermediate_results/marker_genes/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028_protein.faa'
================================================================================
```
