### ISSUE TITLE
Starting pplacer.pplacer: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed

### ISSUE THREAD

**Issue by sannareddyk** [Ecogenomics/GTDBTk#423]
## Environment
- [x] Using a conda environment (include the output of `conda list && conda list --revisions`)

conda list
```
# packages in environment at /mnt/mibi_ngs/keerthi/miniconda3/envs/gtdbtk-2.1.0:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
boost                     1.70.0           py38h9de70de_1    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
capnproto                 0.9.1                ha19adfc_4    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
dendropy                  4.5.2              pyh3252c3a_0    bioconda
fastani                   1.32                 he1c1bb9_0    bioconda
fasttree                  2.1.11               hec16e2b_1    bioconda
gsl                       2.7                  he838d99_0    conda-forge
gtdbtk                    2.1.0              pyhdfd78af_5    bioconda
hmmer                     3.1b2                         3    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_1    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mash                      2.3                  ha9a2dd8_3    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.1           py38h3a7f9d9_0    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
pip                       22.2.1             pyhd8ed1ab_0    conda-forge
pplacer                   1.1.alpha19          h9ee0642_2    bioconda
prodigal                  2.6.3                hec16e2b_4    bioconda
python                    3.8.13          ha86cf86_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                63.3.0           py38h578d9bd_0    conda-forge
sqlite                    3.39.2               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge


```
conda list --revisions
```
2022-08-02 17:54:29  (rev 0)
    +_libgcc_mutex-0.1 (conda-forge/linux-64)
    +_openmp_mutex-4.5 (conda-forge/linux-64)
    +boost-1.70.0 (conda-forge/linux-64)
    +boost-cpp-1.70.0 (conda-forge/linux-64)
    +bzip2-1.0.8 (conda-forge/linux-64)
    +ca-certificates-2022.6.15 (conda-forge/linux-64)
    +capnproto-0.9.1 (conda-forge/linux-64)
    +colorama-0.4.5 (conda-forge/noarch)
    +dendropy-4.5.2 (bioconda/noarch)
    +fastani-1.32 (bioconda/linux-64)
    +fasttree-2.1.11 (bioconda/linux-64)
    +gsl-2.7 (conda-forge/linux-64)
    +gtdbtk-2.1.0 (bioconda/noarch)
    +hmmer-3.1b2 (bioconda/linux-64)
    +icu-67.1 (conda-forge/linux-64)
    +ld_impl_linux-64-2.36.1 (conda-forge/linux-64)
    +libblas-3.9.0 (conda-forge/linux-64)
    +libcblas-3.9.0 (conda-forge/linux-64)
    +libffi-3.4.2 (conda-forge/linux-64)
    +libgcc-ng-12.1.0 (conda-forge/linux-64)
    +libgfortran-ng-12.1.0 (conda-forge/linux-64)
    +libgfortran5-12.1.0 (conda-forge/linux-64)
    +libgomp-12.1.0 (conda-forge/linux-64)
    +liblapack-3.9.0 (conda-forge/linux-64)
    +libnsl-2.0.0 (conda-forge/linux-64)
    +libopenblas-0.3.20 (conda-forge/linux-64)
    +libstdcxx-ng-12.1.0 (conda-forge/linux-64)
    +libuuid-2.32.1 (conda-forge/linux-64)
    +libzlib-1.2.12 (conda-forge/linux-64)
    +lz4-c-1.9.3 (conda-forge/linux-64)
    +mash-2.3 (bioconda/linux-64)
    +ncurses-6.3 (conda-forge/linux-64)
    +numpy-1.23.1 (conda-forge/linux-64)
    +openssl-3.0.5 (conda-forge/linux-64)
    +pip-22.2.1 (conda-forge/noarch)
    +pplacer-1.1.alpha19 (bioconda/linux-64)
    +prodigal-2.6.3 (bioconda/linux-64)
    +python-3.8.13 (conda-forge/linux-64)
    +python_abi-3.8 (conda-forge/linux-64)
    +readline-8.1.2 (conda-forge/linux-64)
    +setuptools-63.3.0 (conda-forge/linux-64)
    +sqlite-3.39.2 (conda-forge/linux-64)
    +tk-8.6.12 (conda-forge/linux-64)
    +tqdm-4.64.0 (conda-forge/noarch)
    +wheel-0.37.1 (conda-forge/noarch)
    +xz-5.2.5 (conda-forge/linux-64)
    +zlib-1.2.12 (conda-forge/linux-64)
    +zstd-1.4.9 (conda-forge/linux-64)
```

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
model name	: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
56
- RAM: `grep "^MemTotal" /proc/meminfo`
MemTotal:       528097456 kB
- OS: `cat /etc/os-release`
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

## Additional comments
```
INFO: pplacer version: v1.1.alpha19-0-g807f6f3
^M==> .^M==> Step 1 of 9: Starting pplacer.pplacer: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Process Process-10:
Traceback (most recent call last):
  File "/mnt/mibi_ngs/keerthi/miniconda3/envs/gtdbtk-2.1.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/mnt/mibi_ngs/keerthi/miniconda3/envs/gtdbtk-2.1.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/mibi_ngs/keerthi/miniconda3/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 124, in _worker
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: G01929_BIN_REFINEMENT_C/Annotation/classify/intermediate_results/pplacer/pplacer.backbone.bac120.out
ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
```

**Comment by aaronmussig** [comment]
Hi, this is a pplacer error so we won't be able to help too much with this. It appears that pplacer is failing on loading the locale information. You should try changing locales and see if that helps: https://www.tecmint.com/set-system-locales-in-linux/

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
