### ISSUE TITLE
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.

### ISSUE THREAD

**Issue by mattoslmp** [Ecogenomics/GTDBTk#425]
Dear, I' having the errror mensage bellow. Could you give any suggestions/tips:

[2022-08-16 22:00:57] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 834, in parse_options
    self.classify(options)
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 458, in classify
    classify.run(genomes=genomes,
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/classify.py", line 396, in run
    high_classify_tree = self.place_genomes(user_msa_file,
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/classify.py", line 261, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/bio_temp/share_bio/softwares/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 92, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================

**Comment by aaronmussig** [comment]
Hi, how much memory do you have on the server running GTDB-Tk? This usually occurs when pplacer runs out of memory. Do you have the rest of the GTDB-Tk log above the traceback?

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.

**Comment by kunaljaani** [comment]
Hi!

I recently updated my gtdbtk installation to the latest v2.4.0 and also downloaded the associated database v220. I am running gtdbtk as a part of metaGEM pipeline w/ 128GB RAM. It was running fine before the upgrade but is now throwing this error could you please suggest a fix?

Thank you
Kunal


==> Step 9 of 9: placing genome 214 of 246 (86.99%).[2024-06-26 14:40:23] INFO: Calculating RED values based on reference tree.
==> Step 9 of 9: placing genome 216 of 246 (87.80%).[2024-06-26 14:40:24] INFO: 284 out of 284 have an class assignments. Those genomes will be reclassified.
[2024-06-26 14:40:24] TASK: Placing 157 bacterial genomes into class-level reference tree 3 (1/6) with pplacer using 12 CPUs (be patient).
[2024-06-26 14:40:40] INFO: Calculating RED values based on reference tree.
[2024-06-26 14:40:41] INFO: 246 out of 246 have an class assignments. Those genomes will be reclassified.
[2024-06-26 14:40:41] TASK: Placing 155 bacterial genomes into class-level reference tree 3 (1/7) with pplacer using 12 CPUs (be patient).
==> Step 7 of 9: Preparing the edges for baseball.Process Process-67:.51/85.57 GB, 77.73%).
Traceback (most recent call last):
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 127, in _worker
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: GTDBTk/classify/intermediate_results/pplacer/tree_3/pplacer.class_level.bac120.out
==> Step 5 of 9: Caching likelihood information on reference tree (66.76/85.57 GB, 78.02%).[2024-06-26 14:53:48] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/main.py", line 1182, in parse_options
    self.classify(options,all_classified_ani= all_classified_ani,all_failed_prodigal=all_failed_prodigal)
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/main.py", line 587, in classify
    reports = classify.run(genomes=genomes,
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/classify.py", line 624, in run
    low_classify_tree, submsa_file_path = self._place_in_low_tree(
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/classify.py", line 824, in _place_in_low_tree
    low_classify_tree = self.place_genomes(submsa_file_path,
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/classify.py", line 270, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/home/metaGEM/workflow/envs/metagem/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 95, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================
Process Process-68:                                                                        ^C
Process Process-67:
