### ISSUE TITLE
I got the following error while running classify_wf

### ISSUE THREAD

**Issue by aaronmussig** [Ecogenomics/GTDBTk#431]
I got the following error while running classify_wf
[2022-09-11 16:57:34] TASK: Placing 4 archaeal genomes into reference tree with pplacer using 46 CPUs (be patient).
[2022-09-11 16:57:34] INFO: pplacer version: v1.1.alpha19-0-g807f6f3
[2022-09-11 17:01:07] INFO: Calculating RED values based on reference tree.                                    
[2022-09-11 17:01:08] TASK: Traversing tree to determine classification method.
[2022-09-11 17:01:08] INFO: Completed 4 genomes in 0.00 seconds (7,087.97 genomes/second).
[2022-09-11 17:01:08] TASK: Calculating average nucleotide identity using FastANI (v1.33).
[2022-09-11 17:01:10] INFO: Completed 48 comparisons in 2.18 seconds (22.06 comparisons/second).
[2022-09-11 17:01:10] INFO: 0 genome(s) have been classified using FastANI and pplacer.
[2022-09-11 17:01:10] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: PermissionError
  MESSAGE: [Errno 1] Operation not permitted: 'classify/gtdbtk.ar53.summary.tsv' -> 'classify_wf_out/gtdbtk.ar53.summary.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/main.py", line 834, in parse_options
    self.classify(options)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/main.py", line 464, in classify
    fulltreeopt=options.full_tree)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/classify.py", line 531, in run
    os.path.join(out_dir, os.path.basename(PATH_AR53_SUMMARY_OUT.format(prefix=prefix))))
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/tools.py", line 245, in symlink_f
    os.symlink(src, dst)
PermissionError: [Errno 1] Operation not permitted: 'classify/gtdbtk.ar53.summary.tsv' -> 'classify_wf_out/gtdbtk.ar53.summary.tsv'

_Originally posted by @improudofmyself in https://github.com/Ecogenomics/GTDBTk/issues/89#issuecomment-1243052373_

**Comment by aaronmussig** [comment]
Hi @improudofmyself this issue appears to be caused by your account having insufficient permissions to create Symlinks, but it could also be due to relative paths not working correctly. 

To test it out, I would try just to create a basic symlink in the output directory and let us know if that worked.

**Comment by improudofmyself** [comment]
This is my output directory:
/media/scaria/HDD-7/Joy_Data/contigs/bins/classify_wf_out

How am I suppose to create this symlink. Please suggest in detail,

**Comment by saad272** [comment]
Hi @aaronmussig 
I got the following error while running classify_wf and I don't understand why? help me please.
Thank you !

```
2022-10-14 19:20:59] INFO: GTDB-Tk v2.1.0
[2022-10-14 19:20:59] INFO: gtdbtk classify_wf --extension fa --cpus 14 --genome_dir . --out_dir gtdb/
[2022-10-14 19:20:59] INFO: Using GTDB-Tk reference data version r207: /home/IAME/db/gtdbtk-2.1.0/release207_v2
[2022-10-14 19:21:01] INFO: Identifying markers in 26 genomes with 14 threads.
[2022-10-14 19:21:01] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-10-14 19:21:36] INFO: Completed 26 genomes in 34.98 seconds (1.35 seconds/genome).
[2022-10-14 19:21:36] TASK: Identifying TIGRFAM protein families.
[2022-10-14 19:21:45] INFO: Completed 26 genomes in 9.09 seconds (2.86 genomes/second).
[2022-10-14 19:21:45] TASK: Identifying Pfam protein families.
[2022-10-14 19:21:46] INFO: Completed 26 genomes in 0.86 seconds (30.35 genomes/second).
[2022-10-14 19:21:46] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2022-10-14 19:21:46] TASK: Summarising identified marker genes.
[2022-10-14 19:21:47] INFO: Completed 26 genomes in 0.78 seconds (33.44 genomes/second).
[2022-10-14 19:21:47] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: OSError
  MESSAGE: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdb/gtdbtk.failed_genomes.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 243, in identify
    self._report_identified_marker_genes(genome_dictionary, out_dir, prefix,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 117, in _report_identified_marker_genes
    symlink_f(PATH_FAILS.format(prefix=prefix),
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/tools.py", line 245, in symlink_f
    os.symlink(src, dst)
OSError: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdb/gtdbtk.failed_genomes.tsv'
================================================================================
```
