### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: using classify_wf after it processes the protein files

### ISSUE THREAD

**Issue by jolespin** [Ecogenomics/GTDBTk#439]
Any idea why this could be happening? 

```
[2022-09-30 17:56:28] INFO: GTDB-Tk v2.1.1
[2022-09-30 17:56:28] INFO: gtdbtk classify_wf --genome_dir veba_output/binning/prokaryotic/S005_R2_POST-PE-N728-S516-1_S23/output/genomes/ --pplacer_cpus 1 --out_dir gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23 -x faa --cpus 4 --genes
[2022-09-30 17:56:28] INFO: Using GTDB-Tk reference data version r207: /expanse/projects/jcl110/db/gtdbtk/release207_v2/
[2022-09-30 17:56:29] INFO: Identifying markers in 16 genomes with 4 threads.
[2022-09-30 17:56:29] INFO: Using supplied genomes as called genes, skipping Prodigal.
[2022-09-30 17:56:29] TASK: Identifying TIGRFAM protein families.
[2022-09-30 17:56:42] INFO: Completed 16 genomes in 12.93 seconds (1.24 genomes/second).
[2022-09-30 17:56:42] TASK: Identifying Pfam protein families.
[2022-09-30 17:56:43] INFO: Completed 16 genomes in 1.01 seconds (15.90 genomes/second).
[2022-09-30 17:56:43] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2022-09-30 17:56:43] TASK: Summarising identified marker genes.
[2022-09-30 17:56:43] INFO: Completed 16 genomes in 0.13 seconds (124.12 genomes/second).
[2022-09-30 17:56:43] INFO: Done.
[2022-09-30 17:56:43] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: FileNotFoundError
  MESSAGE: [Errno 2] No such file or directory: 'gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23/identify/intermediate_results/marker_genes/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028_protein.faa'
________________________________________________________________________________

Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/main.py", line 832, in parse_options
    self.align(options)
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/main.py", line 294, in align
    markers.align(options.identify_dir,
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/markers.py", line 478, in align
    genomic_files = self._path_to_identify_data(
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/site-packages/gtdbtk/markers.py", line 268, in _path_to_identify_data
    if os.path.getsize(aa_gene_path) < 1:
  File "/expanse/projects/jcl110/anaconda3/envs/gtdbtk_env/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'gtdbtk_output/S005_R2_POST-PE-N728-S516-1_S23/identify/intermediate_results/marker_genes/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028/S005_R2_POST-PE-N728-S516-1_S23__MAXBIN2-40__P.1__bin.028_protein.faa'
================================================================================
```

Looks like it makes a broken symlink: 
<img width="1763" alt="image" src="https://user-images.githubusercontent.com/9061708/193403793-3dd586cd-27dd-4a8e-a5be-085183f5f051.png">

One more update, I just ran it with the genomes instead and it worked perfectly. I think what can fix this is to get full paths for the output path?

**Comment by pchaumeil** [comment]
Thanks Josh for your feedback, 
We will change the behaviour of the symlink to use full path instead. This should be available in the next Tk release.
