### ISSUE TITLE
I got the following error while running classify_wf

### ISSUE THREAD

**Issue by saad272** [Ecogenomics/GTDBTk#447]
Hi
I got the following error while running classify_wf and I don't understand why? help me please.
Thank you !

```
2022-10-14 19:20:59] INFO: GTDB-Tk v2.1.0
[2022-10-14 19:20:59] INFO: gtdbtk classify_wf --extension fa --cpus 14 --genome_dir . --out_dir gtdb/
[2022-10-14 19:20:59] INFO: Using GTDB-Tk reference data version r207: /home/IAME/db/gtdbtk-2.1.0/release207_v2
[2022-10-14 19:21:01] INFO: Identifying markers in 26 genomes with 14 threads.
[2022-10-14 19:21:01] TASK: Running Prodigal V2.6.3 to identify genes.
[2022-10-14 19:21:36] INFO: Completed 26 genomes in 34.98 seconds (1.35 seconds/genome).
[2022-10-14 19:21:36] TASK: Identifying TIGRFAM protein families.
[2022-10-14 19:21:45] INFO: Completed 26 genomes in 9.09 seconds (2.86 genomes/second).
[2022-10-14 19:21:45] TASK: Identifying Pfam protein families.
[2022-10-14 19:21:46] INFO: Completed 26 genomes in 0.86 seconds (30.35 genomes/second).
[2022-10-14 19:21:46] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2022-10-14 19:21:46] TASK: Summarising identified marker genes.
[2022-10-14 19:21:47] INFO: Completed 26 genomes in 0.78 seconds (33.44 genomes/second).
[2022-10-14 19:21:47] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: OSError
  MESSAGE: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdb/gtdbtk.failed_genomes.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 243, in identify
    self._report_identified_marker_genes(genome_dictionary, out_dir, prefix,
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/markers.py", line 117, in _report_identified_marker_genes
    symlink_f(PATH_FAILS.format(prefix=prefix),
  File "/usr/bin/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/tools.py", line 245, in symlink_f
    os.symlink(src, dst)
OSError: [Errno 95] Operation not supported: 'identify/gtdbtk.failed_genomes.tsv' -> 'gtdb/gtdbtk.failed_genomes.tsv'
================================================================================
```

**Comment by aaronmussig** [comment]
Hello,

You're getting an "OSError: [Errno 95] Operation not supported" when GTDB-Tk is creating symlinks to the output data. This occurs when you don't have permission to write to the output directory. This is a problem with your account permissions on your server. See here:
* [Related #1](https://github.com/open-mmlab/mmdetection/issues/1371)
* [Related #2](https://stackoverflow.com/questions/56609051/what-is-oserror-errno-95-operation-not-supported-for-pandas-to-csv-on-colab)

What you can do:
* [Check that you have permission to write to the output directory](https://phoenixnap.com/kb/linux-file-permissions)
* [Try manually creating a symlink in the output directory](https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command/)

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
