### ISSUE TITLE
missing files in gtdbtk_v2_data.tar.gz

### ISSUE THREAD

**Issue by LuffyLuffy** [Ecogenomics/GTDBTk#449]
gtdbtk align --identify_dir  /mnt/g/softwares/GTDB_TK_2.1.0/test/identify  --out_dir /mnt/g/softwares/GTDB_TK_2.1.0/test/align --cpus 2
[2022-11-14 12:29:55] INFO: GTDB-Tk v1.0.2
[2022-11-14 12:29:55] INFO: gtdbtk align --identify_dir /mnt/g/softwares/GTDB_TK_2.1.0/test/identify --out_dir /mnt/g/softwares/GTDB_TK_2.1.0/test/align --cpus 2
[2022-11-14 12:29:55] INFO: Using GTDB-Tk reference data version r207: /mnt/g/softwares/GTDB_TK_2.1.0/release207_v2
[2022-11-14 12:29:55] INFO: Aligning markers in 2 genomes with 2 threads.
[2022-11-14 12:29:55] INFO: Processing 2 genomes identified as archaeal.
[2022-11-14 12:29:55] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: InputFileError
  MESSAGE: Input file /mnt/g/softwares/GTDB_TK_2.1.0/release207_v2/msa/gtdb_r207_ar122.faa does not exist.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/lucy2/anaconda3/envs/gtdbtk/bin/gtdbtk", line 449, in <module>
    gt_parser.parse_options(args)
  File "/home/lucy2/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 629, in parse_options
    self.align(options)
  File "/home/lucy2/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/main.py", line 263, in align
    markers.align(options.identify_dir,
  File "/home/lucy2/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 533, in align
    gtdb_msa = self._msa_filter_by_taxa(msa_file,
  File "/home/lucy2/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/markers.py", line 316, in _msa_filter_by_taxa
    msa = read_fasta(concatenated_file)
  File "/home/lucy2/anaconda3/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/seq_io.py", line 49, in read_fasta
    raise InputFileError('Input file %s does not exist.' % fasta_file)
gtdbtk.biolib_lite.exceptions.InputFileError: Input file /mnt/g/softwares/GTDB_TK_2.1.0/release207_v2/msa/gtdb_r207_ar122.faa does not exist.

## Environment
- [ ] Installed via pip (include the output of `pip list`)
- [ ] Using a conda environment (include the output of `conda list && conda list --revisions`)
- [ ] Using a Docker container (include the `IMAGE ID` of the container)

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- RAM: `grep "^MemTotal" /proc/meminfo`
- OS: `cat /etc/os-release`

## Debugging information
- [ ] `gtdbtk.log` has been included (drag and drop the file to upload).
- [ ] Genomes have been included (if possible, and there are few).

**Comment by pchaumeil** [comment]
Hello,
You are actually running GTDB-Tk v1.0.2 in your environnement. 
This is a deprecated version of GTDB-Tk and it will not work with the latest release207_v2 package.
I wold recommend updating GTDB-Tk to the latest version (2.1.0)

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
