### ISSUE TITLE
gtdbtk_package_backbone.refpkg: No such file or directory

### ISSUE THREAD

**Issue by Mamingjie543** [Ecogenomics/GTDBTk#454]
==> Processed 62252/62292 sequences (100%) |██████████████▉| [569.91sequence/s, ETA 00:00]
                                                                                          [2022-11-30 15:09:29] INFO: Completed 62,292 sequences in 1.61 minutes (38,645.61 sequences/minute).
[2022-11-30 15:09:29] INFO: Masked bacterial alignment from 41,084 to 5,036 AAs.
[2022-11-30 15:09:29] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
[2022-11-30 15:09:29] INFO: Creating concatenated alignment for 62,292 bacterial GTDB and user genomes.
[2022-11-30 15:09:52] INFO: Creating concatenated alignment for 1 bacterial user genomes.
[2022-11-30 15:09:53] INFO: Done.
[2022-11-30 15:09:54] TASK: Placing 1 bacterial genomes into backbone reference tree with pplacer using 10 CPUs (be patient).
[2022-11-30 15:09:54] INFO: pplacer version: v1.1.alpha19-0-g807f6f3

==> .
==> Step 1 of 9: Starting pplacer.Uncaught exception: Sys_error("/data/home/mamj/db/gtdbtk/release207/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")
Fatal error: exception Sys_error("/data/home/mamj/db/gtdbtk/release207/split/backbone/pplacer/gtdbtk_package_backbone.refpkg: No such file or directory")

==> Running pplacer v1.1.alpha19-0-g807f6f3 analysis on ./tax/align/gtdbtk.bac120.user_msa.fasta.gz....Process Process-55:
Traceback (most recent call last):
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 124, in _worker
    raise PplacerException('An error was encountered while '
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer, check the log file: ./tax/classify/intermediate_results/pplacer/pplacer.backbone.bac120.out

                                                                                                       
[2022-11-30 15:09:55] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 834, in parse_options
    self.classify(options)
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 458, in classify
    classify.run(genomes=genomes,
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/classify.py", line 396, in run
    high_classify_tree = self.place_genomes(user_msa_file,
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/classify.py", line 261, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/data/home/mamj/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 92, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================

**Comment by Mamingjie543** [comment]
Very luckily, I solved this problem with the help of a kind person!!!
Here is the help email from the well-wisher：
Hi,
It looks like you are using GTDB-Tk package [R207_v1](https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_data.tar.gz) with GTDB-Tk 2.1.1, That is why the path to gtdbtk_package_backbone.refpkg cannot be found.
v2.1.0+ is not compatible with GTDB-Tk package R207_v1. It is necessary to upgrade to GTDB-Tk package [R207_v2](https://data.gtdb.ecogenomic.org/releases/latest/auxillary_files/gtdbtk_v2_data.tar.gz).

Cheers,
Pierre

**Comment by pchaumeil** [comment]
Glad to hear you have resolved the issue :) . I will now close this ticket
