### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by tnn111** [Ecogenomics/GTDBTk#459]
I followed all of the GTDB-Tk install directions to the letter. The result is attached.

==> Processed 0/6 genomes (0%) |               | [?genome/s, ETA ?]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:1:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
==> Processed 1/6 genomes (17%) |██▌            | [ 5.80s/genome, ETA 00:29]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:2:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
==> Processed 2/6 genomes (33%) |█████          | [ 5.14s/genome, ETA 00:20]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:3:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
==> Processed 3/6 genomes (50%) |███████▌       | [ 4.51s/genome, ETA 00:13]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:4:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
==> Processed 4/6 genomes (67%) |██████████     | [ 4.28s/genome, ETA 00:08]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:5:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
==> Processed 5/6 genomes (83%) |████████████▌  | [ 3.45s/genome, ETA 00:03]/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:6:1:
Traceback (most recent call last):
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/torben/opt/mambaforge/envs/gtdbtk/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
[2022-12-23 16:54:26] INFO: Completed 6 genomes in 36.38 seconds (6.06 seconds/genome).
[2022-12-23 16:54:26] TASK: Identifying TIGRFAM protein families.
[2022-12-23 16:54:26] ERROR: There are no genomes to process.
[2022-12-23 16:54:26] ERROR: Controlled exit resulting from an unrecoverable error or warning.

**Comment by juanu** [comment]
@tnn111 I ran into the same issue. It seems the problem is the version of Numpy that is installed when installing GTDBTk using conda/mamba.

Within the GTDBTk conda environment, I downgraded Numpy, and it fixed the error message.

```
mamba install numpy=1.23.1
```

**Comment by tnn111** [comment]
Thanks Juan!

I needed it to work so I used the Docker container. I don’t like exposing my system to a ton of security issues so I made an Apptainer image and that worked ok.

I had similar issues with CheckM2; I couldn’t install it. I managed to run it without installing.

These packages are great and they carry out a task that really needs doing. It’s really disturbing when they don’t work.

Thanks, Torben

**Comment by zwets** [comment]
This issue appears to be [fixed in the upcoming 2.1.2 release](https://github.com/Ecogenomics/GTDBTk/pull/438). @juanu's workaround in [this comment](https://github.com/Ecogenomics/GTDBTk/issues/459#issuecomment-1365605314) solves it for now.

**Comment by tmmendoza-mbb** [comment]
> @tnn111 I ran into the same issue. It seems the problem is the version of Numpy that is installed when installing GTDBTk using conda/mamba.
> 
> Within the GTDBTk conda environment, I downgraded Numpy, and it fixed the error message.
> 
> ```
> mamba install numpy=1.23.1
> ```

This did not work for me. So what I did was to activate the environment and downgrade numpy using pip instead:

pip install numpy==1.23.1
