### ISSUE TITLE
Prodigal returned a non-zero exit code

### ISSUE THREAD

**Issue by Nephilim94** [Ecogenomics/GTDBTk#462]
Whenever I tried to run gtdbtk classify_wf I faced the following prodigal error with............can anyone please help me to solve this issue ?

gtdbtk classify_wf --genome_dir LP_DASTool_Run1_DASTool_bins/ --out_dir gtbdtk_out -x fa --debug
[2023-01-06 21:25:56] INFO: GTDB-Tk v2.1.1
[2023-01-06 21:25:56] INFO: gtdbtk classify_wf --genome_dir LP_DASTool_Run1_DASTool_bins/ --out_dir gtbdtk_out -x fa --debug
[2023-01-06 21:25:56] INFO: Using GTDB-Tk reference data version r207: /home/me/Documents/db
[2023-01-06 21:25:56] INFO: Identifying markers in 9 genomes with 1 threads.
[2023-01-06 21:25:56] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/9 genomes (0%) |               | [?genome/s, ETA ?]/home/me/env/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:1:1:
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/me/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/home/me/env/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'
Process Process-2:
Traceback (most recent call last):
  File "/home/me/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/me/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 143, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 109, in _run_prodigal
    raise Exception("An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
[2023-01-06 21:26:03] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 211, in run
    raise ProdigalException('Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/markers.py", line 203, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/home/me/env/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 220, in run
    raise ProdigalException(f'An exception was caught while running Prodigal: {e}')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.

**Comment by rrdelahaba** [comment]
This issue has been solved here:
https://github.com/Ecogenomics/GTDBTk/issues/459

**Comment by Nephilim94** [comment]
Thanks for your reply.....and it worked for me.
Is it impossible to use gtdbtk classify_wf in a Linux system with 32 GB memory ?

**Comment by pchaumeil** [comment]
Hi,
Unfortunately classify_wf will need at least 55G to run pplacer so the pipeline will crash with only 32G available.
