### ISSUE TITLE
Dependency on pydantic introduced in 2.2.0

### ISSUE THREAD

**Issue by zwets** [Ecogenomics/GTDBTk#470]
Thank you for releasing GTDB-Tk 2.2.0!

I encountered just one minor glitch when installing it from source. I am aware this is not one of your documented modes of installation, but this worked fine for 2.1.0 and 2.1.1, as follows:

    # create env with requirements from https://ecogenomics.github.io/GTDBTk/installing/index.html
    mamba create --quiet -n gtdbtk-2.2.0 -c conda-forge -c bioconda \
        python dendropy numpy tqdm \
        prodigal hmmer pplacer fastani fasttree mash 

    # install from source repo
    conda activate gtdbtk-2.2.0
    python setup.py install

    # set environment
    conda env config vars set GTDBTK_DATA_PATH=/path/to/gtdbtk/release207_v2
    
Then, running `gtdbtk check_install` (or any `gtdbtk` invocation) gave:

```
Traceback (most recent call last):
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/bin/gtdbtk", line 33, in <module>
    sys.exit(load_entry_point('gtdbtk==2.2.0', 'console_scripts', 'gtdbtk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/bin/gtdbtk", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/lib/python3.11/site-packages/gtdbtk-2.2.0-py3.11.egg/gtdbtk/__main__.py", line 27, in <module>
    from gtdbtk.main import OptionsParser
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/lib/python3.11/site-packages/gtdbtk-2.2.0-py3.11.egg/gtdbtk/main.py", line 46, in <module>
    from gtdbtk.files.stage_logger import StageLoggerFile, ANIScreenStep, IdentifyStep, ClassifyStep, AlignStep, \
  File "/hpc/opt/conda/envs/gtdbtk-2.2.0-3/lib/python3.11/site-packages/gtdbtk-2.2.0-py3.11.egg/gtdbtk/files/stage_logger.py", line 4, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
```

The issue was solved by adding `pydantic` to the `mamba create` package list:

    mamba create --quiet -n gtdbtk-2.2.0 -c conda-forge -c bioconda \
        python dendropy numpy tqdm \
        prodigal hmmer pplacer fastani fasttree mash \
        pydantic
 
This was with the repo pulled to latest on master (2.2.0-3-geef2a2a).

**Comment by aaronmussig** [comment]
Hello! Thanks for pointing this out, it will be fixed in 2.2.1
