### ISSUE TITLE
Prodigal error when running `gtdbtk test`

### ISSUE THREAD

**Issue by ZongzhiWu** [Ecogenomics/GTDBTk#502]
gtdbtk test --out_dir 99data/gtdbtk.test --cpus 3
[2023-03-31 15:54:07] INFO: GTDB-Tk v2.1.1
[2023-03-31 15:54:07] INFO: gtdbtk test --out_dir 99data/gtdbtk.test --cpus 3
[2023-03-31 15:54:07] INFO: Using GTDB-Tk reference data version r207: /lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/share/gtdbtk-2.1.1/db
[2023-03-31 15:54:07] INFO: Command: gtdbtk classify_wf --genome_dir 99data/gtdbtk.test/genomes --out_dir 99data/gtdbtk.test/output --cpus 3 -f
    <TEST OUTPUT>     [2023-03-31 15:54:08] INFO: gtdbtk classify_wf --genome_dir 99data/gtdbtk.test/genomes --out_dir 99data/gtdbtk.test/output --cpus    <TEST OUTPUT>     [2023-03-31 15:54:08] INFO: Using GTDB-Tk reference data version r207: /lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1    <TEST OUTPUT>     [2023-03-31 15:54:08] INFO: Identifying markers in 3 genomes with 3 threads.                                                         <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line    <TEST OUTPUT>     raise ProdigalException('Prodigal returned a non-zero exit code.')                                                                   <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in m    <TEST OUTPUT>     gt_parser.parse_options(args)                                                                                                        <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in pars    <TEST OUTPUT>     self.identify(options)                                                                                                               <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in iden    <TEST OUTPUT>     markers.identify(genomes,                                                                                                            <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/markers.py", line 203, in i    <TEST OUTPUT>     genome_dictionary = prodigal.run(genomes, tln_tables)                                                                                <TEST OUTPUT>     File "/lustre/home/wangbingxue_2020ms/miniconda3/envs/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line    <TEST OUTPUT>     raise ProdigalException(f'An exception was caught while running Prodigal: {e}')                                                  [2023-03-31 15:54:20] ERROR: The test returned a non-zero exit code.
[2023-03-31 15:54:20] ERROR: A detailed summary of the execution log can be found here: 99data/gtdbtk.test/test_execution.log
[2023-03-31 15:54:20] ERROR: The test has failed.
[2023-03-31 15:54:20] ERROR: Controlled exit resulting from early termination.

**Comment by pchaumeil** [comment]
Hello,

Anything returned in the 99data/gtdbtk.test/test_execution.log file? is prodigal properly installed on the server?
If so, can you try to run prodigal outside of GTDB-Tk.
For example just run the prodigal command as following:

`prodigal -m -i 99data/gtdbtk.test/genomes/<input_genome_file> -q -g 11 -f gff -o prodigal_called/prodigal_feature.gff -a prodigal_called/prodigal_amino.faa -d prodigal_called/prodigal_nuc.fna`

This command should use one genome from the test dataset ( in `99data/gtdbtk.test/genomes`) and run prodigal to create 3 files in the `prodigal_called` directory.

Thanks,
Pierre

**Comment by kimseonw** [comment]
Hi Pierre,

gtdbtk classify_wf ended with similar errors and prodigal command went through well.

[2023-04-04 10:01:30] INFO: GTDB-Tk v2.1.1
[2023-04-04 10:01:30] INFO: gtdbtk classify_wf --genome_dir /project/genome_dir/ --out_dir /project/MAG_gtdbtk/ -x fasta --cpus 72 --pplacer_cpus 1 --tmpdir /local/bgfs/9341142
[2023-04-04 10:01:30] INFO: Using GTDB-Tk reference data version r207: /project/gtdbtk-2.1.1/share/gtdbtk-2.1.1/db/
[2023-04-04 10:01:30] INFO: Identifying markers in 1 genomes with 72 threads.
[2023-04-04 10:01:30] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/1 genomes (0%) |               | [?genome/s, ETA ?]/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py:378: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
Process Process-2:1:1:
Traceback (most recent call last):
  File "/project/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/project/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 147, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 322, in __init__
    self.coding_base_masks[seq_id] = self.__build_coding_base_mask(
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/biolib_lite/prodigal_biolib.py", line 378, in __build_coding_base_mask
    coding_base_mask = np.zeros(self.last_coding_base[seq_id], dtype=np.bool)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Process Process-2:
Traceback (most recent call last):
  File "/project/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/project/gtdbtk-2.1.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 143, in _worker
    rtn_files = self._run_prodigal(genome_id, file_path, usr_tln_table)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 109, in _run_prodigal
    raise Exception("An error was encountered while running Prodigal.")
Exception: An error was encountered while running Prodigal.
[2023-04-04 10:01:33] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: ProdigalException
  MESSAGE: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 211, in run
    raise ProdigalException('Prodigal returned a non-zero exit code.')
gtdbtk.exceptions.ProdigalException: Prodigal returned a non-zero exit code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 816, in parse_options
    self.identify(options)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/main.py", line 271, in identify
    markers.identify(genomes,
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/markers.py", line 203, in identify
    genome_dictionary = prodigal.run(genomes, tln_tables)
  File "/project/gtdbtk-2.1.1/lib/python3.8/site-packages/gtdbtk/external/prodigal.py", line 220, in run
    raise ProdigalException(f'An exception was caught while running Prodigal: {e}')
gtdbtk.exceptions.ProdigalException: An exception was caught while running Prodigal: Prodigal returned a non-zero exit code.

**Comment by pchaumeil** [comment]
Hi,
You are both using GTDB-Tk v2.1.1
GTDB-Tk version 2.1.1 had an issue with the numpy library ( see #459 )
I would recommend updating GTDB-Tk to the latest version.

**Comment by liamfitzstevens** [comment]
@ZongzhiWu, as @pchaumeil said, if you define the numpy version (`numpy=1.23.1`) you should be able to run v2.1.1 (we had the same issue, but this fixed it).
