### ISSUE TITLE
An error was encountered while running FastTree.

### ISSUE THREAD

**Issue by diedie9** [Ecogenomics/GTDBTk#517]
Hi, thanks for your nice tool. 
I got the error message: An error was encountered while running FastTree when I use the de_novo_wf workflow.
I submitted commend was: gtdbtk de_novo_wf --genome_dir /work/hudi/lina/prok/med_high_quality_1879bins/ --bacteria --outgroup_taxon p__Firmicutes --out_dir /work/hudi/lina/prok/gtdb-novo2 --cpus 3 --force --extension fa

The error is from the FastTree:
[2023-05-23 12:14:06] INFO: GTDB-Tk v2.1.0
[2023-05-23 12:14:06] INFO: gtdbtk de_novo_wf --genome_dir /work/hudi/lina/prok/med_high_quality_1879bins/ --bacteria --outgroup_taxon p__Firmicutes --out_dir /work/hudi/lina/prok/gtdb-novo2 --cpus 3 --force --extension fa
[2023-05-23 12:14:06] INFO: Using GTDB-Tk reference data version r207: /gpfs1/data/msb/tools/miniconda/miniconda2/envs/gtdbtk-2.1.0/share/gtdbtk-2.1.0/db
[2023-05-23 12:14:07] INFO: Identifying markers in 1,879 genomes with 3 threads.
[2023-05-23 12:14:07] TASK: Running Prodigal V2.6.3 to identify genes.
[2023-05-23 12:14:46] INFO: Completed 1,879 genomes in 38.27 seconds (49.10 genomes/second).
[2023-05-23 12:14:46] WARNING: Prodigal skipped 1879 genomes due to pre-existing data, see warnings.log
[2023-05-23 12:14:50] TASK: Identifying TIGRFAM protein families.
[2023-05-23 12:15:05] INFO: Completed 1,879 genomes in 14.78 seconds (127.14 genomes/second).
[2023-05-23 12:15:05] WARNING: TIGRFAM skipped 1,879 genomes due to pre-existing data, see warnings.log
[2023-05-23 12:15:05] TASK: Identifying Pfam protein families.
[2023-05-23 12:15:16] INFO: Completed 1,879 genomes in 11.05 seconds (170.09 genomes/second).
[2023-05-23 12:15:16] WARNING: Pfam skipped 1,879 genomes due to pre-existing data, see warnings.log
[2023-05-23 12:15:16] INFO: Annotations done using HMMER 3.1b2 (February 2015).
[2023-05-23 12:15:16] TASK: Summarising identified marker genes.
[2023-05-23 12:15:59] INFO: Completed 1,879 genomes in 43.24 seconds (43.45 genomes/second).
[2023-05-23 12:15:59] INFO: Done.
[2023-05-23 12:16:05] INFO: Aligning markers in 1,879 genomes with 3 CPUs.
[2023-05-23 12:16:06] INFO: Processing 1,878 genomes identified as bacterial.
[2023-05-23 12:16:13] INFO: Read concatenated alignment for 62,291 GTDB genomes.
[2023-05-23 12:16:13] TASK: Generating concatenated alignment for each marker.
[2023-05-23 12:16:20] INFO: Completed 1,878 genomes in 7.22 seconds (259.98 genomes/second).
[2023-05-23 12:16:21] TASK: Aligning 120 identified markers using hmmalign 3.1b2 (February 2015).
[2023-05-23 12:25:01] INFO: Completed 120 markers in 8.67 minutes (13.84 markers/minute).
[2023-05-23 12:25:01] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2023-05-23 12:26:09] INFO: Completed 64,169 sequences in 1.12 minutes (57,251.71 sequences/minute).
[2023-05-23 12:26:09] INFO: Masked bacterial alignment from 41,084 to 5,036 AAs.
[2023-05-23 12:26:09] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
[2023-05-23 12:26:09] INFO: Creating concatenated alignment for 64,169 bacterial GTDB and user genomes.
[2023-05-23 12:26:27] INFO: Creating concatenated alignment for 1,878 bacterial user genomes.
[2023-05-23 12:26:28] INFO: Processing 1 genomes identified as archaeal.
[2023-05-23 12:26:28] INFO: Read concatenated alignment for 3,412 GTDB genomes.
[2023-05-23 12:26:28] TASK: Generating concatenated alignment for each marker.
[2023-05-23 12:26:29] INFO: Completed 1 genome in 0.02 seconds (63.10 genomes/second).
[2023-05-23 12:26:29] TASK: Aligning 53 identified markers using hmmalign 3.1b2 (February 2015).
[2023-05-23 12:26:31] INFO: Completed 53 markers in 2.25 seconds (23.55 markers/second).
[2023-05-23 12:26:31] WARNING: Filtered 1878 genomes with no bacterial or archaeal marker.
[2023-05-23 12:26:31] TASK: Masking columns of archaeal multiple sequence alignment using canonical mask.
[2023-05-23 12:26:34] INFO: Completed 3,413 sequences in 2.89 seconds (1,179.73 sequences/second).
[2023-05-23 12:26:34] INFO: Masked archaeal alignment from 13,540 to 10,153 AAs.
[2023-05-23 12:26:34] INFO: 0 archaeal user genomes have amino acids in <10.0% of columns in filtered MSA.
[2023-05-23 12:26:34] INFO: Creating concatenated alignment for 3,413 archaeal GTDB and user genomes.
[2023-05-23 12:26:36] INFO: Creating concatenated alignment for 1 archaeal user genomes.
[2023-05-23 12:26:36] INFO: Done.
[2023-05-23 12:26:36] INFO: Inferring FastTree (WAG, SH support values) using a maximum of 3 CPUs.
[2023-05-23 14:23:41] ERROR: An error was encountered while running FastTree.
[2023-05-23 14:23:41] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: FastTreeException
  MESSAGE: FastTree returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/data/msb/tools/miniconda/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/data/msb/tools/miniconda/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 767, in parse_options
    self.infer(options)
  File "/data/msb/tools/miniconda/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/main.py", line 345, in infer
    fasttree.run(output_tree, tree_log, fasttree_log, options.prot_model,
  File "/data/msb/tools/miniconda/miniconda2/envs/gtdbtk-2.1.0/lib/python3.8/site-packages/gtdbtk/external/fasttree.py", line 136, in run
    raise FastTreeException('FastTree returned a non-zero exit code.')
gtdbtk.exceptions.FastTreeException: FastTree returned a non-zero exit code.
================================================================================

Could you help me fix it?

**Comment by pchaumeil** [comment]
Hi, 
Could you check the log files in the folder /work/hudi/lina/prok/gtdb-novo2/infer/intermediate_results/ to check if FastTree did not return any error?

Thanks

**Comment by diedie9** [comment]
Hi, 
I checked two files: gtdbtk.ar53.fasttree.log  gtdbtk.bac120.fasttree.log 
Error message 'Out of memory' is in gtdbtk.bac120.fasttree.log.

Do you know how I can ask more memory? Is it work by changing the --cpus 3 to --cpus 6?

Kind regards,
Die

**Comment by pchaumeil** [comment]
Hello,
Asking for more cpus will not change the amount of RAM available to run `de_novo_wf`. I would recommend running the command on a server with more memory if possible.
To check the current memory available on your server, you can type the following command:

`grep "^MemTotal" /proc/meminfo`

**Comment by pchaumeil** [comment]
Ticket closed due to inactivity.
