### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'index'

### ISSUE THREAD

**Issue by nick-youngblut** [Ecogenomics/GTDBTk#518]
This appears to be an issue with calculating RED values:

```
Command output:
  [2023-05-26 05:52:15] INFO: Using GTDB-Tk reference data version r207: R207_v2
  [2023-05-26 05:52:15] INFO: Identifying markers in 1 genomes with 8 threads.
  [2023-05-26 05:52:15] TASK: Running Prodigal V2.6.3 to identify genes.
  [2023-05-26 05:52:28] INFO: Completed 1 genome in 12.60 seconds (12.60 seconds/genome).
  [2023-05-26 05:52:28] TASK: Identifying TIGRFAM protein families.
  [2023-05-26 05:52:31] INFO: Completed 1 genome in 3.19 seconds (3.19 seconds/genome).
  [2023-05-26 05:52:31] TASK: Identifying Pfam protein families.
  [2023-05-26 05:52:32] INFO: Completed 1 genome in 0.32 seconds (3.08 genomes/second).
  [2023-05-26 05:52:32] INFO: Annotations done using HMMER 3.3.2 (Nov 2020).
  [2023-05-26 05:52:32] TASK: Summarising identified marker genes.
  [2023-05-26 05:52:32] INFO: Completed 1 genome in 0.02 seconds (52.14 genomes/second).
  [2023-05-26 05:52:32] INFO: Done.
  [2023-05-26 05:52:35] INFO: Aligning markers in 1 genomes with 8 CPUs.
  [2023-05-26 05:52:35] INFO: Processing 1 genomes identified as bacterial.
  [2023-05-26 05:52:42] INFO: Read concatenated alignment for 62,291 GTDB genomes.
  [2023-05-26 05:52:42] TASK: Generating concatenated alignment for each marker.
  [2023-05-26 05:52:42] INFO: Completed 1 genome in 0.07 seconds (14.27 genomes/second).
  [2023-05-26 05:52:43] TASK: Aligning 113 identified markers using hmmalign 3.3.2 (Nov 2020).
  [2023-05-26 05:52:45] INFO: Completed 113 markers in 1.77 seconds (63.86 markers/second).
  [2023-05-26 05:52:45] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
  [2023-05-26 05:54:36] INFO: Completed 62,292 sequences in 1.85 minutes (33,637.05 sequences/minute).
  [2023-05-26 05:54:36] INFO: Masked bacterial alignment from 41,084 to 5,036 AAs.
  [2023-05-26 05:54:36] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
  [2023-05-26 05:54:36] INFO: Creating concatenated alignment for 62,292 bacterial GTDB and user genomes.
  [2023-05-26 05:54:56] INFO: Creating concatenated alignment for 1 bacterial user genomes.
  [2023-05-26 05:54:56] INFO: Done.
  [2023-05-26 05:54:56] INFO: Using a scratch file for pplacer allocations. This decreases memory usage and performance.
  [2023-05-26 05:54:56] TASK: Placing 1 bacterial genomes into backbone reference tree with pplacer using 8 CPUs (be patient).
  [2023-05-26 05:54:56] INFO: pplacer version:[v1.1.al](https://urldefense.proofpoint.com/v2/url?u=http-3A__v1.1.al&d=DwQFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cLh6mm_hVoHpm1HpCH_8iAoX8Xt6V9KZnyyXTNNkAqE&m=sKnWzTYxMEX5AmySnANKh6GccKRjfHhE3qhLZA-9aLA&s=zc2KsN9ssxRONSljnurPw7Q6SCZTQZzyTRLXEOJV4-E&e=)pha19-0-g807f6f3
  [2023-05-26 05:57:12] INFO: Calculating RED values based on reference tree.
  [2023-05-26 05:57:12] ERROR: Uncontrolled exit resulting from an unexpected error.
  
  ================================================================================
  EXCEPTION: AttributeError
    MESSAGE: 'NoneType' object has no attribute 'index'
  ________________________________________________________________________________
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/gtdbtk/__main__.py", line 101, in main
      gt_parser.parse_options(args)
    File "/usr/local/lib/python3.8/site-packages/gtdbtk/main.py", line 1157, in parse_options
     [self.cl](https://urldefense.proofpoint.com/v2/url?u=http-3A__self.cl&d=DwQFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cLh6mm_hVoHpm1HpCH_8iAoX8Xt6V9KZnyyXTNNkAqE&m=sKnWzTYxMEX5AmySnANKh6GccKRjfHhE3qhLZA-9aLA&s=YlzQlCV-ZmSIfeEnbhL9XdI87-eaqrhudpkB-tEVnjE&e=)assify(options,all_classified_ani= all_classified_ani)
    File "/usr/local/lib/python3.8/site-packages/gtdbtk/main.py", line 587, in classify
      reports =[classify.ru](https://urldefense.proofpoint.com/v2/url?u=http-3A__classify.ru&d=DwQFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cLh6mm_hVoHpm1HpCH_8iAoX8Xt6V9KZnyyXTNNkAqE&m=sKnWzTYxMEX5AmySnANKh6GccKRjfHhE3qhLZA-9aLA&s=4qVmKoS2768jFlZ5JCAga-4fmfKCp-jDjSyDB5YMtaQ&e=)n(genomes=genomes,
    File "/usr/local/lib/python3.8/site-packages/gtdbtk/classify.py", line 551, in run
      high_classification =[splitter.ge](https://urldefense.proofpoint.com/v2/url?u=http-3A__splitter.ge&d=DwQFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=cLh6mm_hVoHpm1HpCH_8iAoX8Xt6V9KZnyyXTNNkAqE&m=sKnWzTYxMEX5AmySnANKh6GccKRjfHhE3qhLZA-9aLA&s=1yyOWrCqVDHykUIApkRKBXKG343ruywyPowOdz6oRSA&e=)t_high_pplacer_taxonomy(
    File "/usr/local/lib/python3.8/site-packages/gtdbtk/split.py", line 130, in get_high_pplacer_taxonomy
      tax_of_leaf = term_branch_taxonomy[term_branch_taxonomy.index(
  AttributeError: 'NoneType' object has no attribute 'index'
  ================================================================================
```

## Environment

Docker image:

```
quay.io/biocontainers/gtdbtk:2.2.4--pyhdfd78af_0
```

The GTDB-Tk Docker image works correctly with most input genomes. 

## Additional comments

seqkit stats for the input genome:

```
file          format  type  num_seqs    sum_len  min_len   avg_len  max_len
genome.fna  FASTA   DNA         32  2,460,266    1,061  76,883.3  573,877
```

...so it appears that the genome quality is OK.

**Comment by pchaumeil** [comment]
Hi, 
Could you please send me the genome and command line you are trying to run?
Which version of Tk are you running?

Thanks

**Comment by nick-youngblut** [comment]
> Could you please send me the genome and command line you are trying to run?

Sorry, but the genomes that I'm processing are proprietary. I'll try to find a published genome that is causing the error. I'm using `gtdbtk:2.2.4`. I'll try with `gtdbtk:2.3.0`

**Comment by nick-youngblut** [comment]
<img width="699" alt="Screen Shot 2023-05-29 at 6 47 19 PM" src="https://github.com/Ecogenomics/GTDBTk/assets/2468572/f4f0d1f2-77cd-4e27-b31c-4684d2f0529e">

I'm still getting the same error when using `gtdbtk:2.3.0`

**Comment by pchaumeil** [comment]
mmm interesting. if you can not provide the genome for proprietary reason, could you at least provide the ~5000 AA sequence for this genome used for the placement in pplacer (generated with the align step, and located in the user MSA file)? or can you provide the output tree from pplacer (it should be named `gtdbtk.backbone.bac120.classify.tree` and is located in the `<output_dir>/classify/ `directory.  

The first goal of the `classify_wf` command is to generate the summary.tsv files. All extra files ( including the newick trees) we are generating to create these summary files are here for extra informations. For historical reasons we represent our pplacer trees as newick trees. It shouldnt be difficult to convert these to a DAG but this hasn't been implemented yet.

**Comment by nick-youngblut** [comment]
When I run the job locally instead of on AWS Batch, I get the following error:

```
  [2023-06-01 00:43:16] INFO: Calculating RED values based on reference tree.
  [2023-06-01 00:43:18] TASK: Traversing tree to determine classification method.
  
  ==> Processed 0/3980 genomes (0%) |               | [?genome/s, ETA ?]
  ==> Processed 5/3980 genomes (0%) |               | [39.72genome/s, ETA 01:40]
                                                                                
  [2023-06-01 00:43:18] ERROR: There are no reference genomes under 'g__JG1575'
  [2023-06-01 00:43:18] ERROR: Controlled exit resulting from an unrecoverable error or warning.
```

the genus is found in the `taxonomy/bac120_taxonomy_r207_reps.tsv` file:

```
GB_GCA_002838815.1      d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Clostridiales;f__Clostridiaceae;g__JG1575;s__JG1575 sp002838815
```

...so I'm not sure what is causing the issue. 

Note: I'm using nextflow, which is staging the entire database (it takes a few hours to download from s3 when run locally). Maybe the database is corrupt? Does GTDB-Tk do any explicit checks for database corruption (e.g., an incomplete database or incomplete files within the database directory)?

**Comment by pchaumeil** [comment]
You can run `gtdbtk check_install` to check third party programs and GTDB reference package. you may need to use `--db-version` flag as the check is done for release 214 instead of 207

**Comment by nick-youngblut** [comment]
Thanks @pchaumeil for the suggestion! In regards to `--db-version`, it would be helpful to have a list of possible versions, and how the version string should be formatted:

```
usage: gtdbtk check_install [--db_version DB_VERSION] [--debug] [-h]

optional arguments:
  --db_version DB_VERSION
                        GTDB-Tk version package to test for compatibility.
  --debug               create intermediate files for debugging purposes (default: False)
  -h, --help            show help message
```


```
usage: gtdbtk check_install [--db_version DB_VERSION] [--debug] [-h]
gtdbtk check_install: error: argument --db_version: invalid int value: 'R207_v2'
```

It appears that the database was somehow corrupted:

```
gtdbtk check_install --db_version 207
[2023-06-01 16:13:34] INFO: GTDB-Tk v2.3.0
[2023-06-01 16:13:34] INFO: gtdbtk check_install --db_version 207
[2023-06-01 16:13:34] INFO: Using GTDB-Tk reference data version r207: R207_v2
[2023-06-01 16:13:34] INFO: Running install verification
[2023-06-01 16:13:34] INFO: Checking that all third-party software are on the system path:
[2023-06-01 16:13:34] INFO:          |-- FastTree         OK
[2023-06-01 16:13:34] INFO:          |-- FastTreeMP       OK
[2023-06-01 16:13:34] INFO:          |-- fastANI          OK
[2023-06-01 16:13:34] INFO:          |-- guppy            OK
[2023-06-01 16:13:34] INFO:          |-- hmmalign         OK
[2023-06-01 16:13:34] INFO:          |-- hmmsearch        OK
[2023-06-01 16:13:34] INFO:          |-- mash             OK
[2023-06-01 16:13:34] INFO:          |-- pplacer          OK
[2023-06-01 16:13:34] INFO:          |-- prodigal         OK
[2023-06-01 16:13:34] INFO: Checking integrity of reference package: R207_v2
[2023-06-01 16:13:34] INFO:          |-- pplacer          OK                                        
[2023-06-01 16:13:34] INFO:          |-- masks            OK                                        
[2023-06-01 16:13:34] INFO:          |-- markers          OK                                        
[2023-06-01 16:13:34] INFO:          |-- radii            OK                                        
[2023-06-01 16:13:37] INFO:          |-- msa              OK                                        
[2023-06-01 16:13:38] INFO:          |-- metadata         HASH MISMATCH bb6cd9849fc2e255fb806bf40fbb2c6f9667f0a4
[2023-06-01 16:13:38] INFO:          |-- taxonomy         HASH MISMATCH 3c97c3336c5973b44b2ae00106a38d2cc1fad767
[2023-06-01 16:19:36] INFO:          |-- fastani          OK                                        
[2023-06-01 16:19:36] INFO:          |-- mrca_red         OK                                        
[2023-06-01 16:19:36] ERROR: Unexpected files were seen, or the reference package is corrupt.
[2023-06-01 16:19:36] ERROR: Controlled exit resulting from an unrecoverable error or warning.
```

I'll re-download.

**Comment by nick-youngblut** [comment]
Updating the database fixed the issue. I wonder how the files became corrupted 🤔
