### ISSUE TITLE
error in the     EXCEPTION: ValidationError   MESSAGE: 6 validation errors for __StageLogger

### ISSUE THREAD

**Issue by YingyuanBrewmaster** [Ecogenomics/GTDBTk#543]
Hello,

I downloaded GTDB-Tk 2.3.0 using Bioconda.
I have a question regarding an error in the  MESSAGE: 6 validation errors for __StageLogger.
Could you please advise on how to resolve this? Can you provide me with some assistance? Thank you very much!

(gtdbtk-2.3.0) dyjiang@wenserver:~/workspace/teameta/23.binning/234.GTDBtk$ gtdbtk classify_wf --genome_dir ./DASZ_genomes/ --out_dir DASZ_out_genomes --skip_ani_screen --cpus 30 --extension fa --tmpdir ./
[2023-08-04 18:17:29] INFO: GTDB-Tk v2.3.0
[2023-08-04 18:17:29] INFO: gtdbtk classify_wf --genome_dir ./DASZ_genomes/ --out_dir DASZ_out_genomes --skip_ani_screen --cpus 30 --extension fa --tmpdir ./
[2023-08-04 18:17:29] INFO: Using GTDB-Tk reference data version r214: /home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db
[2023-08-04 18:17:29] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: ValidationError
  MESSAGE: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/__main__.py", line 100, in main
    gt_parser = OptionsParser(__version__,
  File "/home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/main.py", line 86, in __init__
    self.stage_logger = StageLogger()
  File "/home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/gtdbtk/files/stage_logger.py", line 172, in __new__
    StageLogger.instance = StageLogger.__StageLogger(steps=[])
  File "/home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/lib/python3.8/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 6 validation errors for __StageLogger
version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
command_line
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
database_version
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
database_path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
output_dir
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
path
  Field required [type=missing, input_value={'steps': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
================================================================================

I ran 'gtdbtk check_install', and it displayed the following:

(gtdbtk-2.3.0) dyjiang@wenserver:~/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db$ gtdbtk check_install
[2023-08-04 19:18:28] INFO: GTDB-Tk v2.3.0
[2023-08-04 19:18:28] INFO: gtdbtk check_install
[2023-08-04 19:18:28] INFO: Using GTDB-Tk reference data version r214: /home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db
[2023-08-04 19:18:28] INFO: Running install verification
[2023-08-04 19:18:28] INFO: Checking that all third-party software are on the system path:
[2023-08-04 19:18:28] INFO:          |-- FastTree         OK
[2023-08-04 19:18:28] INFO:          |-- FastTreeMP       OK
[2023-08-04 19:18:28] INFO:          |-- fastANI          OK
[2023-08-04 19:18:28] INFO:          |-- guppy            OK
[2023-08-04 19:18:28] INFO:          |-- hmmalign         OK
[2023-08-04 19:18:28] INFO:          |-- hmmsearch        OK
[2023-08-04 19:18:28] INFO:          |-- mash             OK
[2023-08-04 19:18:28] INFO:          |-- pplacer          OK
[2023-08-04 19:18:28] INFO:          |-- prodigal         OK
[2023-08-04 19:18:28] INFO: Checking integrity of reference package: /home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db
[2023-08-04 19:18:30] INFO:          |-- pplacer          OK                                        
[2023-08-04 19:18:30] INFO:          |-- masks            OK                                        
[2023-08-04 19:18:31] INFO:          |-- markers          OK                                        
[2023-08-04 19:18:31] INFO:          |-- radii            OK                                        
[2023-08-04 19:18:37] INFO:          |-- msa              OK                                        
[2023-08-04 19:18:37] INFO:          |-- metadata         OK                                        
[2023-08-04 19:18:37] INFO:          |-- taxonomy         OK                                        
[2023-08-04 19:21:51] INFO:          |-- fastani          OK                                        .0%)
[2023-08-04 19:21:51] INFO:          |-- mrca_red         OK                                        
[2023-08-04 19:21:51] INFO: Done.

Could you please provide me with some assistance? Thank you!

**Comment by YingyuanBrewmaster** [comment]
Could you please provide me with some assistance? Thank you!
I ran gtdbtk check_install and it displayed the following: 

(gtdbtk-2.3.0) dyjiang@wenserver:~/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db$ gtdbtk check_install
[2023-08-04 19:18:28] INFO: GTDB-Tk v2.3.0
[2023-08-04 19:18:28] INFO: gtdbtk check_install
[2023-08-04 19:18:28] INFO: Using GTDB-Tk reference data version r214: /home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db
[2023-08-04 19:18:28] INFO: Running install verification
[2023-08-04 19:18:28] INFO: Checking that all third-party software are on the system path:
[2023-08-04 19:18:28] INFO:          |-- FastTree         OK
[2023-08-04 19:18:28] INFO:          |-- FastTreeMP       OK
[2023-08-04 19:18:28] INFO:          |-- fastANI          OK
[2023-08-04 19:18:28] INFO:          |-- guppy            OK
[2023-08-04 19:18:28] INFO:          |-- hmmalign         OK
[2023-08-04 19:18:28] INFO:          |-- hmmsearch        OK
[2023-08-04 19:18:28] INFO:          |-- mash             OK
[2023-08-04 19:18:28] INFO:          |-- pplacer          OK
[2023-08-04 19:18:28] INFO:          |-- prodigal         OK
[2023-08-04 19:18:28] INFO: Checking integrity of reference package: /home/dyjiang/miniconda3/envs/gtdbtk-2.3.0/share/gtdbtk-2.3.0/db
[2023-08-04 19:18:30] INFO:          |-- pplacer          OK                                        
[2023-08-04 19:18:30] INFO:          |-- masks            OK                                        
[2023-08-04 19:18:31] INFO:          |-- markers          OK                                        
[2023-08-04 19:18:31] INFO:          |-- radii            OK                                        
[2023-08-04 19:18:37] INFO:          |-- msa              OK                                        
[2023-08-04 19:18:37] INFO:          |-- metadata         OK                                        
[2023-08-04 19:18:37] INFO:          |-- taxonomy         OK                                        
[2023-08-04 19:21:51] INFO:          |-- fastani          OK                                        .0%)
[2023-08-04 19:21:51] INFO:          |-- mrca_red         OK                                        
[2023-08-04 19:21:51] INFO: Done.

**Comment by YingyuanBrewmaster** [comment]
Hello, 
After redownloading version 2.3.2 of the software and creating a new environment, this issue has been resolved. 
Thank you for your attention.

**Comment by shibormi** [comment]
gtdbtk classify_wf --mash_db databases/gtdbtk/release220/mash --genome_di test --out_dir TEST_Run/GtdbTk -x fasta --cpus 32 --tmpdir ./tmp

 Using GTDB-Tk reference data version r220: databases/gtdbtk/release220
[2024-07-20 10:59:21] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: ValidationError
  MESSAGE: 6 validation errors for __StageLogger
  
  I also face the same issues but with new version 2.3.2 and 2.4.0. I have run gtdbtk check_install. but everything seems fine. But still got this error. Please let me know what might be the cause of the error. thankyou

**Comment by pchaumeil** [comment]
Hello, How did you update the GTDB-Tk software? Did you have 2.3.0 running first? It may be some legacy code from the original version that hasn't been overwritten

**Comment by shibormi** [comment]
Thanks for the response. Its actually the pydantic version is the issues while creating a singularity image. I install the pydantic version 1.9.2 and it works fine.
