### ISSUE TITLE
GTDB-Tk Infer: FastTree returned a non-zero exit code.

### ISSUE THREAD

**Issue by Helenapfingst** [Ecogenomics/GTDBTk#544]
Hi,
I am using gtdbtk v2.3.2. 
This is katana module based, with the following loaded modules:

module load python/3.10.8

module load py-gtdbtk/2.3.0

module load prodigal/2.6.3

module load hmmer/3.3.2

module load pplacer/1.1.alpha19

module load fastani/1.33

module load perl/5.36.0

module load fasttree/2.1.11-openmp

module load mash/2.3-gcc-8.5.0

 

export GTDBTK_DATA_PATH=/data/bio/gtdbtk/release214/
I am trying to run the infer step of the gtdbtk de_novo workflow with a user-defined msa, which consists of all "c__Dehalococcoidia" reference sequences from the gtdbtk.bac120.msa.fasta and the gtdbtk.bac120.user_msa.fasta. Both are output of the align-folder genereted by gtdbtk de_novo. 

I am using the command as follows:

gtdbtk infer --msa_file /srv/scratch/z5525249/Paratimea/ONT_reads/Paratimea_reassembly_Dehalococcoidia_1500bp_reads/Dehalococcoidia_GTDB_denovo_3/align/my_tree_msa_3.fasta --out_dir /srv/scratch/z5525249/Paratimea/ONT_reads/Paratimes_reassembly_Dehalococcoidia/Dehalococcoidia_GTDB_denovo_3/align/msa_infer.fasta

I do end up with the Error as mentioned above:

[2023-08-16 20:32:33] INFO: GTDB-Tk v2.3.0
[2023-08-16 20:32:33] INFO: gtdbtk infer --msa_file /srv/scratch/z5525249/Paratimea/ONT_reads/Paratimea_reassembly_Dehalococcoidia_1500bp_reads/Dehalococcoidia_GTDB_denovo_3/align/dehalo_user.fasta --out_dir /srv/scratch/z5525249/Paratimea/ONT_reads/Paratimes_reassembly_Dehalococcoidia/Dehalococcoidia_GTDB_denovo_3/align/eins.fasta
[2023-08-16 20:32:33] INFO: Using GTDB-Tk reference data version r214: /data/bio/gtdbtk/release214/
[2023-08-16 20:32:33] INFO: Inferring FastTree (WAG, SH support values) using a maximum of 1 CPUs.
[2023-08-16 20:32:33] ERROR: An error was encountered while running FastTree.
[2023-08-16 20:32:33] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: FastTreeException
  MESSAGE: FastTree returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-gtdbtk-2.3.0-no2arocxatckmw7paaznknrm7zkazhwj/venv/lib/python3.10/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-gtdbtk-2.3.0-no2arocxatckmw7paaznknrm7zkazhwj/venv/lib/python3.10/site-packages/gtdbtk/main.py", line 1196, in parse_options
    self.infer(options)
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-gtdbtk-2.3.0-no2arocxatckmw7paaznknrm7zkazhwj/venv/lib/python3.10/site-packages/gtdbtk/main.py", line 437, in infer
    fasttree.run(output_tree, tree_log, fasttree_log, options.prot_model,
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/py-gtdbtk-2.3.0-no2arocxatckmw7paaznknrm7zkazhwj/venv/lib/python3.10/site-packages/gtdbtk/external/fasttree.py", line 136, in run
    raise FastTreeException('FastTree returned a non-zero exit code.')
gtdbtk.exceptions.FastTreeException: FastTree returned a non-zero exit code.

**Comment by pchaumeil** [comment]
Hello,
Apologies for the late reply,
Do you still have this issue?
