### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by JiangweiPan1230** [Ecogenomics/GTDBTk#545]
Sorry to bother you, but the error has bothered me for a long time.
Here is the command:
gtdbtk classify_wf --genome_dir /media/pjw/PJW_2/PJW-EXPERIMENT/BIOINFO_PJW/NCBI_DATA_RefSeq_DOWNLOAD_FILTER1 --out_dir /media/pjw/PJW_2/PJW-EXPERIMENT/BIOINFO_PJW/GTDBTK_RESULTS_FILTERED/FILTER1 --skip_ani_screen --cpus 64

There are 600 sequences in file FILTER1. When I want to run for 3000 sequences, this error happened, that's why I divided the reference data into 5 packages. However, it seemed useless. 
When I run for 24 sequnces, however, it worked. 
Therefore, I wonder why this error  happened.

EXCEPTION: PermissionError
  MESSAGE: [Errno 1] Operation not permitted: 'classify/gtdbtk.bac120.summary.tsv' -> '/media/pjw/PJW_2/PJW-EXPERIMENT/BIOINFO_PJW/GTDBTK_RESULTS_FILTERED/FILTER1/gtdbtk.bac120.summary.tsv'

Traceback (most recent call last):
  File "/home/pjw/mambaforge/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/home/pjw/mambaforge/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 1186, in parse_options
    self.classify(options,all_classified_ani= all_classified_ani)
  File "/home/pjw/mambaforge/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 587, in classify
    reports = classify.run(genomes=genomes,
  File "/home/pjw/mambaforge/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/classify.py", line 659, in run
    symlink_f(PATH_BAC120_SUMMARY_OUT.format(prefix=prefix),
  File "/home/pjw/mambaforge/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/tools.py", line 269, in symlink_f
    os.symlink(src, dst)
PermissionError: [Errno 1] Operation not permitted: 'classify/gtdbtk.bac120.summary.tsv' -> '/media/pjw/PJW_2/PJW-EXPERIMENT/BIOINFO_PJW/GTDBTK_RESULTS_FILTERED/FILTER1/gtdbtk.bac120.summary.tsv'
================================================================================

**Comment by JiangweiPan1230** [comment]
Sorry to bother you, I have tried to change the output directory to local, then the error didn't happen.

**Comment by JiangweiPan1230** [comment]
You can close this issue. Thank you and sorry again.
