### ISSUE TITLE
gtdb_to_ncbi_majority_vote and Unclassified Bacteria

### ISSUE THREAD

**Issue by ttubb** [Ecogenomics/GTDBTk#561]
I ran into a problem using `gtdb_to_ncbi_majority_vote.py` (`stdout` provided below). The issue seems to be in line 519 when trying to access `gtdb_taxa[SPECIES_IDX]`.
`SPECIES_IDX` is set to 6 which makes sense for the regular classfications, but some of my MAGs in `gtdbtk.bac120.summary.tsv` are classified as `Unclassified Bacteria` or just as `Unclassified`. In those cases index 6 doesn't exist of course.

Easy to work around but it took me some time to figure out whats wrong. Thank you for the great tool!

## Environment
I cloned the github repo today to run `gtdb_to_ncbi_majority_vote.py` but `gtdbtk.bac120.summary.tsv` was created with version 2.1.1 - though after glancing at output of the current version I don't think it makes a difference.

## Server information
- CPU:  AMD EPYC Processor (with IBPB)
- RAM: 495120632 kB
- OS: Ubuntu 22.04.2 LTS

## Stdout
```
[2023-11-22 16:55:03] INFO: GTDB to NCBI majority vote v0.2.1
[2023-11-22 16:55:03] INFO: gtdb_to_ncbi_majority_vote.py --gtdbtk_output_dir /mnt/mega/ena_taxonomy/gtdb_output_dir --bac120_metadata_file /mnt/mega/ena_taxonomy/gtdb_metadata_files/bac120_metadata_r207.tsv --ar53_metadata_file /mnt/mega/ena_taxonomy/gtdb_metadata_files/ar53_metadata_r207.tsv --output_file /mnt/mega/ena_taxonomy/converted_to_ncbi.tsv
[2023-11-22 16:55:03] INFO: Parsing GTDB-Tk classifications:
[2023-11-22 16:55:03] INFO:  - identified 6 archaeal classifications
[2023-11-22 16:55:03] INFO:  - identified 294 bacterial classifications
[2023-11-22 16:55:03] INFO: Identifying GTDB-Tk classification trees:
[2023-11-22 16:55:03] INFO:  - identified archaeal backbone tree
[2023-11-22 16:55:03] INFO:  - identified 1 bacterial tree(s)
[2023-11-22 16:55:03] INFO: Parsing NCBI taxonomy from GTDB metadata files:
[2023-11-22 16:55:03] INFO: Processing archaeal metadata file.
[2023-11-22 16:55:03] INFO: Processing bacterial metadata file.
[2023-11-22 16:55:07] INFO:  - read NCBI taxonomy for 317,542 genomes
[2023-11-22 16:55:07] INFO:  - identified 65,703 GTDB species clusters
[2023-11-22 16:55:07] INFO:  - identified genomes in 4,107 GTDB families
[2023-11-22 16:55:07] INFO: Determining NCBI majority vote classifications for GTDB species clusters.
[2023-11-22 16:55:08] INFO:  - identified 65,701 GTDB species clusters with an NCBI classification
[2023-11-22 16:55:08] INFO: Determining NCBI majority vote classification for each genome:
[2023-11-22 16:55:08] INFO:  - parsing /mnt/mega/ena_taxonomy/gtdb_output_dir/classify/gtdbtk.ar53.classify.tree
[2023-11-22 16:55:09] INFO:  - parsing /mnt/mega/ena_taxonomy/gtdb_output_dir/classify/gtdbtk.bac120.classify.tree
[2023-11-22 16:55:14] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/mnt/eph/software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py", line 694, in <module>
    p.run(args.gtdbtk_output_dir,
  File "/mnt/eph/software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py", line 605, in run
    self.ncbi_majority_vote(
  File "/mnt/eph/software/GTDBTk/scripts/gtdb_to_ncbi_majority_vote.py", line 519, in ncbi_majority_vote
    gtdb_sp_rid = gtdb_sp_to_rid[gtdb_taxa[SPECIES_IDX]]
IndexError: list index out of range
================================================================================
```

**Comment by donovan-h-parks** [comment]
Hi Tom. Thank you for bringing this to my attention. Are you able to send me a genome that results in this issue? You can email it to donovan.parks [at] gmail.com.

**Comment by donovan-h-parks** [comment]
I have updated the `gtdb_to_ncbi_majority_vote.py` script. The fix is on the `master` branch.
