### ISSUE TITLE
Decorate command issue 

### ISSUE THREAD

**Issue by Nura7177** [Ecogenomics/GTDBTk#574]
Hello, I run decorate on my tree of 300+ genomes from NCBI and get this issue: how to resolve it?
[2024-03-12 15:35:05] INFO: GTDB-Tk v2.3.2
[2024-03-12 15:35:05] INFO: gtdbtk decorate --input_tree /nfs/ashilova/genomes/THR_out/gtdbtk.unrooted.tree --output_tree /nfs/ashilova/genomes/THR_out/decorated_tree
[2024-03-12 15:35:05] INFO: Using GTDB-Tk reference data version r214: /nfs/lisagrig/gtdb_toolkit
[2024-03-12 15:35:05] INFO: Reading GTDB taxonomy for representative genomes.
[2024-03-12 15:35:05] INFO: Read taxonomy for 85,205 genomes.
[2024-03-12 15:35:05] INFO: Reading tree.
[2024-03-12 15:35:05] INFO: Removing any previous internal node labels.
[2024-03-12 15:35:05] INFO: Calculating F-measure statistic for each taxa.
[2024-03-12 15:35:05] INFO: Calculating taxa within each lineage.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Domain rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Phylum rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Class rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Order rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Family rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Genus rank.
[2024-03-12 15:35:05] INFO: Processing 0 taxa at Species rank.
[2024-03-12 15:35:05] INFO: Placing labels on tree.
[2024-03-12 15:35:05] INFO: Writing out statistics for taxa.
[2024-03-12 15:35:05] INFO: Writing out inferred taxonomy for each genome.
[2024-03-12 15:35:05] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: IndexError
  MESSAGE: list index out of range
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 1209, in parse_options
    self.decorate(options)
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/main.py", line 815, in decorate
    reports = d.run(options.input_tree,
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/decorate.py", line 379, in run
    self._write_taxonomy(tree, out_taxonomy)
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/decorate.py", line 314, in _write_taxonomy
    taxa = self._leaf_taxa(leaf)
  File "/home/ashilova/anaconda3/envs/gtdbtk-2.3.2/lib/python3.8/site-packages/gtdbtk/decorate.py", line 295, in _leaf_taxa
    last_rank = ordered_taxa[-1][0:3]
IndexError: list index out of range
================================================================================
~

**Comment by Nura7177** [comment]
I have resolved this issue with  adding --gtdbtk_classification_file, which turned out to be a summary.tsv file ([[prefix].[domain].summary.tsv](https://ecogenomics.github.io/GTDBTk/files/summary.tsv.html#files-summary-tsv)  i.e. in my case - ./GTDB-tk_output/gtdbtk.bac120.summary.tsv
