### ISSUE TITLE
def TypedDict(typename, fields=_marker,/, *, total=True, closed=False, **kwargs):  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zhaoxuetong** [Ecogenomics/GTDBTk#583]
Hello,

I have some errors with gtdbtk v2.1.0.

$gtdbtk check_install
Traceback (most recent call last):
  File "/home/zhaoxt/.conda/envs/GTDB/bin/gtdbtk", line 6, in <module>
    from gtdbtk.__main__ import main
  File "/home/zhaoxt/.local/lib/python3.7/site-packages/gtdbtk-2.3.2-py3.7.egg/gtdbtk/__main__.py", line 27, in <module>
    from gtdbtk.files.stage_logger import StageLogger
  File "/home/zhaoxt/.local/lib/python3.7/site-packages/gtdbtk-2.3.2-py3.7.egg/gtdbtk/files/stage_logger.py", line 5, in <module>
    from pydantic import BaseModel
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 3, in init pydantic.dataclasses
    import copy
  File "pydantic/class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic/errors.py", line 5, in init pydantic.errors
  File "pydantic/typing.py", line 25, in init pydantic.typing
    import contextlib
  File "/home/zhaoxt/.local/lib/python3.7/site-packages/typing_extensions-4.11.0-py3.7.egg/typing_extensions.py", line 958
    def TypedDict(typename, fields=_marker,/, *, total=True, closed=False, **kwargs):
                                           ^
SyntaxError: invalid syntax

**Comment by pchaumeil** [comment]
Hi, 
I do recommend using the last version of GTDB-Tk. 

- If you would like to use `R214` of GTDB, please install `v2.3.2` of GTDB-Tk
- If you would like to use `R220` of GTDB, please install `v2.4.0` of GTDB-Tk

Regards,
Pierre

**Comment by zhaoxuetong** [comment]
Hi Pierre,

Thank you for your prompt reply.
I have a little question about environmental variables.
If my GTDB database R214 is downloaded to $(pwd)/GTDB_software/release214/, and my virtual environment name is gtdbtk-2.3.2, then which of the following is correct:
export GTDBTK_DATA_PATH=$(pwd)/GTDB_software/release214/
export GTDBTK_DATA_PATH=~/.conda/envs/gtdbtk-2.3.2/share/gtdbtk-2.3.2/db"

I'm a little confused now, I don't know if GTDB database R214 must be placed under ~/.conda/envs/gtdbtk-2.3.2/share/gtdbtk-2.3.2/db

Also I run gtdbtk check_install and wait for a long time in [$(pwd)/GTDB_software/release214/fastani/]

Thank you for your reply.
xuetong Zhao

**Comment by pchaumeil** [comment]
You don't have to place the GDTB-Tk database in the conda environment, you can store it anywhere you want on your server.

`gtdbtk check_install `will take a long time at the FastANI as it checks the checksum of all 85K representative genomes of R214.
