### ISSUE TITLE
Error from skani

### ISSUE THREAD

**Issue by jehaab** [Ecogenomics/GTDBTk#592]
Hi, 

I installed the latest versions of GTDB.tk and GTDB.
I also installed all dependencies.
However, I keep getting the following error from skani. Would you be able to help ?

[2024-05-21 11:11:25] INFO: Calculating Mash distances.

[2024-05-21 13:43:04] INFO: Calculating ANI with skani v0.1.0.
==> Processed 0/29540 comparisons (0%) |               | [?comparison/s, ETA ?][2024-05-21 13:43:06] ERROR: STDOUT:

[2024-05-21 13:43:06] ERROR: STDERR:
error: Found argument '--medium' which wasn't expected, or isn't valid in this context

	Did you mean '--median'?

	If you tried to supply `--medium` as a value rather than a flag, use `-- --medium`

USAGE:
    skani dist --median <query|-q <queries>...|--ql <query list file>>

For more information try --help

Process Process-2:
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages/gtdbtk/external/skani.py", line 157, in _worker
    result = self.run_proc(q, r, q_path, r_path, preset)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages/gtdbtk/external/skani.py", line 211, in
[gtdbtk.log](https://github.com/Ecogenomics/GTDBTk/files/15395817/gtdbtk.log)
 run_proc
    raise GTDBTkExit('skani returned a non-zero exit code.')
gtdbtk.exceptions.GTDBTkExit: skani returned a non-zero exit code.
[2024-05-21 13:43:06] ERROR: skani returned a non-zero exit code.
[2024-05-21 13:43:06] ERROR: Controlled exit resulting from an unrecoverable error or warning.

## Environment
-  Installed via pip in a python/3.11 virtual environment
Requirement already satisfied: gtdbtk in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (2.4.0)
Requirement already satisfied: dendropy~=4.1 in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from gtdbtk) (4.6.1+computecanada)
Requirement already satisfied: numpy~=1.9 in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from gtdbtk) (1.25.2+computecanada)
Requirement already satisfied: tqdm~=4.35 in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from gtdbtk) (4.66.2+computecanada)
Requirement already satisfied: pydantic~=1.9 in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from gtdbtk) (1.10.15)
Requirement already satisfied: setuptools in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from dendropy~=4.1->gtdbtk) (68.0.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /project/6087950/softwares/env_GTDB_220/lib/python3.11/site-packages (from pydantic~=1.9->gtdbtk) (4.11.0+computecanada)

## Server information
- CPU:  Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
- RAM: 131624540 kB
- OS: Linux 7

## Debugging information
- [ ] `gtdbtk.log` has been included

**Comment by pchaumeil** [comment]
Hello,
GTDB-Tk does require `skani` version `0.2.1+` and you are currently using `v0.1.0` ( which doesn't have the `--medium` flag).

Please try to update `skani` to the latest version. ([here](https://github.com/bluenote-1577/skani/releases/tag/v0.2.1))

**Comment by jehaab** [comment]
Hi,

Thank you. I feel like I should have caught this one. Thank you for your help it works. 

Jehane
