### ISSUE TITLE
FastTree returned a non-zero exit code

### ISSUE THREAD

**Issue by esraagithub** [Ecogenomics/GTDBTk#604]
Hello
please help me to solve this problem
I am not sure whether my small Ram is the reason behind this error or not   
-->

## Environment

- [ ] Using a Docker container (include the `IMAGE ID` of the container)
ecogenomic/gtdbtk    15bacfc59c95
_____________________________________________________________________________________
## Server information
- CPU: `AMD EPYC 7282 16-Core Processor
- RAM: `**65861996 kB**

- OS: `NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
_______________________________________`
here is my code: (i run this code on one genome)
docker run \
  -v ~/esraa/docker_gt:/input \
  -v ~/esraa/docker_gt:/output \
  -v ~/esraa/docker_gt/db:/refdata \
  ecogenomic/gtdbtk \
  de_novo_wf --outgroup_taxon s__Escherichia_coli --bacteria --genome_dir /input --out_dir /output --cpus 4 --extension fa
_____________________________________________________
## Debugging information

[2024-09-30 18:26:48] INFO: Completed 1 genome in 0.34 seconds (2.97 genomes/second).
[2024-09-30 18:26:48] INFO: Annotations done using HMMER 3.3.2 (Nov 2020).
[2024-09-30 18:26:48] TASK: Summarising identified marker genes.
[2024-09-30 18:26:48] INFO: Completed 1 genome in 0.08 seconds (13.08 genomes/second).
[2024-09-30 18:26:48] INFO: Done.
[2024-09-30 18:26:48] INFO: Aligning markers in 1 genomes with 4 CPUs.
[2024-09-30 18:26:48] INFO: Processing 1 genomes identified as bacterial.
[2024-09-30 18:27:11] INFO: Read concatenated alignment for 107,235 GTDB genomes.
[2024-09-30 18:27:11] TASK: Generating concatenated alignment for each marker.
[2024-09-30 18:27:11] INFO: Completed 1 genome in 0.05 seconds (19.69 genomes/second).
[2024-09-30 18:27:11] TASK: Aligning 86 identified markers using hmmalign 3.3.2 (Nov 2020).
[2024-09-30 18:27:16] INFO: Completed 86 markers in 4.67 seconds (18.43 markers/second).
[2024-09-30 18:27:16] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2024-09-30 18:32:56] INFO: Completed 107,236 sequences in 5.66 minutes (18,949.15 sequences/minute).
[2024-09-30 18:32:56] INFO: Masked bacterial alignment from 41,084 to 5,035 AAs.
[2024-09-30 18:32:56] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
[2024-09-30 18:32:56] INFO: Creating concatenated alignment for 107,236 bacterial GTDB and user genomes.
[2024-09-30 18:33:39] INFO: Creating concatenated alignment for 1 bacterial user genomes.
[2024-09-30 18:33:40] INFO: Done.
[2024-09-30 18:33:40] INFO: Inferring FastTree (WAG, SH support values) using a maximum of 4 CPUs.
[2024-10-01 01:09:08] **ERROR: An error was encountered while running FastTree.
[2024-10-01 01:09:08] ERROR: Controlled exit resulting from an unrecoverable error or warning.**

================================================================================
EXCEPTION: FastTreeException
  MESSAGE: FastTree returned a non-zero exit code.
________________________________________________________________________________

Traceback (most recent call last):
gtdbtk.log  File "/usr/local/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/usr/local/lib/python3.8/site-packages/gtdbtk/main.py", line 1047, in parse_options
    self.infer(options)
  File "/usr/local/lib/python3.8/site-packages/gtdbtk/main.py", line 437, in infer
    fasttree.run(output_tree, tree_log, fasttree_log, options.prot_model,
  File "/usr/local/lib/python3.8/site-packages/gtdbtk/external/fasttree.py", line 136, in run
    raise FastTreeException('FastTree returned a non-zero exit code.')
gtdbtk.exceptions.FastTreeException: FastTree returned a non-zero exit code.

## Additional comments
the same error appeared when i used Conda too
my hardware ram is 64g only but it is just one genome

thank you

**Comment by pchaumeil** [comment]
Hello,
In your case, FastTree will require ~ 100Gb of memory to run. You are placing one genome in the full bacterial MSA will all representatives so your tree is built with 107,236 genomes ( 107,235 reps + your genome). 
If you know the general classification of your genome, you can reduce the memory footprint by selecting clades relevant to your genome and generate a smaller de novo tree. 
As an example, if you know your genome is in the _p__Aquificota_ phylum , you can use the flag `--taxa_filter p__Aquificota,p__Thermosulfidibacterota` and `--outgroup_taxon p__Thermosulfidibacterota` ( _p__Thermosulfidibacterota_ is the sister lineage of _p__Aquificota_ and can be use as an outgroup. 

This will reduce the MSA from 107K genomes to ~ 150 genomes.
Hope that helps
Pierre
