### ISSUE TITLE
Skani external command error

### ISSUE THREAD

**Issue by magicprotoss** [Ecogenomics/GTDBTk#606]
## Issue: the command that runs skani subprocess not working properly
The command that runs skani subprocess sends the output to /dev/stdout, however on morden linux distributions this is not allowed.

I checked on both Ubuntu 22 and RockyOS 9, and go the same result:

$echo "ASDF" > /dev/stdout
**_bash: /dev/stdout: Permission denied_**

###OS Info
- Ubuntu: 
$cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- RockyOS 9:
$cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

## Debugging information
[2024-10-14 15:40:58] TASK: Calculating average nucleotide identity using skani (v0.2.2).
==> Processed 0/34 comparisons (0%) |               | [?comparison/s, ETA ?][2024-10-14 15:40:58] ERROR: STDOUT:

[2024-10-14 15:40:58] ERROR: STDERR:
[00:00:00.000] (73ee5ec73800) INFO   skani dist --medium -q query_genome/M23.fna -r /mnt/gtdbtk-db/skani/database/GCF/004/123/795/GCF_004123795.1_genomic.fna.gz _**-o /dev/stdout**_
[00:00:00.134] (73ee5ec73800) INFO   Learned ANI mode detected. ANI may be adjusted according to a regression model trained on MAGs.
[00:00:00.134] (73ee5ec73800) INFO   Generating sketch time: 0.13419788
thread 'main' panicked at src/file_io.rs:661:60:
_**/dev/stdout: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }**_
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Process Process-115:
Traceback (most recent call last):
  File "/home/navi/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/navi/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/navi/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/site-packages/gtdbtk/external/skani.py", line 157, in _worker
    result = self.run_proc(q, r, q_path, r_path, preset)
  File "/home/navi/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/site-packages/gtdbtk/external/skani.py", line 211, in run_proc
    raise GTDBTkExit('skani returned a non-zero exit code.')
gtdbtk.exceptions.GTDBTkExit: skani returned a non-zero exit code.
[2024-10-14 15:40:58] ERROR: skani returned a non-zero exit code.
[2024-10-14 15:40:58] ERROR: Controlled exit resulting from an unrecoverable error or warning.

**Comment by pchaumeil** [comment]
Hi, 
How are you running GTDB-Tk? are you using docker? if so , Are you starting the docker as root? Docker can block `/dev/stdout` to unprivileged user is the docker image was started as `su`

**Comment by magicprotoss** [comment]
> Hi, How are you running GTDB-Tk? are you using docker? if so , Are you starting the docker as root? Docker can block `/dev/stdout` to unprivileged user is the docker image was started as `su`

Hi, we are running gtdb-tk natively installed in linux enviroment via conda, we think the issue was that the system had some security hardening feautures  enbaled by default that blocks outputing to **_/dev/stdout_**. (both ubuntu22LTS and RockyOS9 exibit the same behavior)

I think changing that line of code to output to a temp file then read from it would be a better :)

**Comment by lingbozeng** [comment]
> > Hi, How are you running GTDB-Tk? are you using docker? if so , Are you starting the docker as root? Docker can block `/dev/stdout` to unprivileged user is the docker image was started as `su`
> 
> Hi, we are running gtdb-tk natively installed in linux enviroment via conda, we think the issue was that the system had some security hardening feautures enbaled by default that blocks outputing to **_/dev/stdout_**. (both ubuntu22LTS and RockyOS9 exibit the same behavior)
> 
> I think changing that line of code to output to a temp file then read from it would be a better :)

Hi，has your problem been resolved? If it has been resolved, could you please tell me which method was used?

**Comment by magicprotoss** [comment]
> > > Hi, How are you running GTDB-Tk? are you using docker? if so , Are you starting the docker as root? Docker can block `/dev/stdout` to unprivileged user is the docker image was started as `su`
> > 
> > 
> > Hi, we are running gtdb-tk natively installed in linux enviroment via conda, we think the issue was that the system had some security hardening feautures enbaled by default that blocks outputing to **_/dev/stdout_**. (both ubuntu22LTS and RockyOS9 exibit the same behavior)
> > I think changing that line of code to output to a temp file then read from it would be a better :)
> 
> Hi，has your problem been resolved? If it has been resolved, could you please tell me which method was used?

I'm running it in on a ubuntu22 vm, I think the issue got resolved after a certain ubuntu update, now I'm running the latest version just fine :)
