### ISSUE TITLE
Hello, what is the reason for this problem? runing: gtdbtk classify_wf --genome_dir new_genome_data/  --skip_ani_screen --out_dir classify_wf_out --cpus 16

### ISSUE THREAD

**Issue by huzongde** [Ecogenomics/GTDBTk#610]
[2024-10-28 04:01:14] INFO: GTDB-Tk v2.4.0
[2024-10-28 04:01:14] INFO: gtdbtk classify_wf --genome_dir new_genome_data/ --skip_ani_screen --out_dir classify_wf_out --cpus 16
[2024-10-28 04:01:14] INFO: Using GTDB-Tk reference data version r220: /data/huzhongde/new_data_project/GTDB-Tk_03/release220/
[2024-10-28 04:01:14] INFO: Identifying markers in 62 genomes with 16 threads.
[2024-10-28 04:01:14] TASK: Running Prodigal V2.6.3 to identify genes.
[2024-10-28 04:06:07] INFO: Completed 62 genomes in 4.87 minutes (12.72 genomes/minute).
[2024-10-28 04:06:07] TASK: Identifying TIGRFAM protein families.
[2024-10-28 04:07:04] INFO: Completed 62 genomes in 57.73 seconds (1.07 genomes/second).
[2024-10-28 04:07:04] TASK: Identifying Pfam protein families.
[2024-10-28 04:07:07] INFO: Completed 62 genomes in 2.52 seconds (24.59 genomes/second).
[2024-10-28 04:07:07] INFO: Annotations done using HMMER 3.3.2 (Nov 2020).
[2024-10-28 04:07:07] TASK: Summarising identified marker genes.
[2024-10-28 04:07:10] INFO: Completed 62 genomes in 2.84 seconds (21.87 genomes/second).
[2024-10-28 04:07:10] INFO: Done.
[2024-10-28 04:07:14] INFO: Aligning markers in 62 genomes with 16 CPUs.
[2024-10-28 04:07:14] INFO: Processing 62 genomes identified as bacterial.
[2024-10-28 04:07:38] INFO: Read concatenated alignment for 107,235 GTDB genomes.
[2024-10-28 04:07:38] TASK: Generating concatenated alignment for each marker.
[2024-10-28 04:07:40] INFO: Completed 62 genomes in 0.21 seconds (292.58 genomes/second).
[2024-10-28 04:07:41] TASK: Aligning 120 identified markers using hmmalign 3.3.2 (Nov 2020).
[2024-10-28 04:07:50] INFO: Completed 120 markers in 7.70 seconds (15.57 markers/second).
[2024-10-28 04:07:51] TASK: Masking columns of bacterial multiple sequence alignment using canonical mask.
[2024-10-28 04:11:01] INFO: Completed 107,297 sequences in 3.16 minutes (33,966.06 sequences/minute).
[2024-10-28 04:11:01] INFO: Masked bacterial alignment from 41,084 to 5,035 AAs.
[2024-10-28 04:11:01] INFO: 0 bacterial user genomes have amino acids in <10.0% of columns in filtered MSA.
[2024-10-28 04:11:02] INFO: Creating concatenated alignment for 107,297 bacterial GTDB and user genomes.
[2024-10-28 04:11:44] INFO: Creating concatenated alignment for 62 bacterial user genomes.
[2024-10-28 04:11:45] INFO: Done.
[2024-10-28 04:11:46] TASK: Placing 62 bacterial genomes into backbone reference tree with pplacer using 16 CPUs (be patient).
[2024-10-28 04:11:46] INFO: pplacer version: v1.1.alpha13-0-g1ec7786
[2024-10-28 04:11:47] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: An error was encountered while running pplacer.
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/__main__.py", line 102, in main
    gt_parser.parse_options(args)
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/main.py", line 1182, in parse_options
    self.classify(options,all_classified_ani= all_classified_ani,all_failed_prodigal=all_failed_prodigal)
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/main.py", line 587, in classify
    reports = classify.run(genomes=genomes,
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/classify.py", line 580, in run
    high_classify_tree = self.place_genomes(user_msa_file,
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/classify.py", line 270, in place_genomes
    pplacer.run(self.pplacer_cpus, 'wag', pplacer_ref_pkg, pplacer_json_out,
  File "/home/huzhongde/.local/lib/python3.8/site-packages/gtdbtk/external/pplacer.py", line 95, in run
    raise PplacerException(
gtdbtk.exceptions.PplacerException: An error was encountered while running pplacer.
================================================================================

**Comment by pchaumeil** [comment]
Hello,
The issue is likely related to pplacer's memory usage; you may need more resources to run the program.
Please have a look at the hardware requirement of v2.4.0 [here](https://ecogenomics.github.io/GTDBTk/installing/index.html#hardware-requirements)
