### ISSUE TITLE
ERROR: An error was encountered while running hmmsearch.

### ISSUE THREAD

**Issue by J-Weijie98** [Ecogenomics/GTDBTk#612]
[2024-11-18 09:40:19] TASK: Identifying TIGRFAM protein families.

==> Processed 0/79 genomes (0%) |               | [?genome/s, ETA ?]Process Process-4:
Traceback (most recent call last):
  File "/media/desk16/tly2105/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/media/desk16/tly2105/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/desk16/tly2105/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/site-packages/gtdbtk/external/tigrfam_search.py", line 154, in _workerThread
    self._topHit(output_hit_file)
  File "/media/desk16/tly2105/miniconda3/envs/gtdbtk-2.4.0/lib/python3.8/site-packages/gtdbtk/external/tigrfam_search.py", line 94, in _topHit
    hmm_id = line_split[3]
IndexError: list index out of range                                                             
[2024-11-18 09:40:27] ERROR: An error was encountered while running hmmsearch.
[2024-11-18 09:40:27] ERROR: Controlled exit resulting from an unrecoverable error or warning.
[2024-11-18 09:40:27] INFO: GTDB-Tk v2.4.0
[2024-11-18 09:40:27] INFO: gtdbtk align --identify_dir /media/desk16/tly2105/Bin_all/gtdbtk_identify
 --out_dir /media/desk16/tly2105/Bin_all/gtdbtk_align
[2024-11-18 09:40:27] INFO: Using GTDB-Tk reference data version r220: /media/desk16/tly2105/miniconda3/envs/gtdbtk-2.4.0/share/gtdbtk-2.4.0/db
[2024-11-18 09:40:27] ERROR: Uncontrolled exit resulting from an unexpected error.
[GATBDK.zip](https://github.com/user-attachments/files/17793968/GATBDK.zip)

**Comment by pchaumeil** [comment]
Hello,

I am unable to reproduce this error with the 2 genomes you have provided, the process is running without problem.
![image](https://github.com/user-attachments/assets/c9371d91-2079-4feb-82f7-bc2999ce9716)

What are the completeness and contamination of the 79 genomes you are trying to analyse? Can you try to rerun the identify step to another directory (/media/desk16/tly2105/Bin_all/gtdbtk_identify_2 for example)
