### ISSUE TITLE
pplacer error using classify step

### ISSUE THREAD

**Issue by snayfach** [Ecogenomics/GTDBTk#78]
I just updated the database to release 86 and the software to v0.1.6. I am now getting the following error; 
 previous steps ran to completion without error:

```
[2019-01-19 11:02:11] INFO: GTDB-Tk v0.1.6
[2019-01-19 11:02:11] INFO: gtdbtk classify --batchfile /global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/genome_lists/1.tsv --align_dir /global/projectb/
scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/align --out_dir /global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify --cpus 16
[2019-01-19 11:02:11] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2019-01-19 11:02:11] INFO: Placing 227 bacterial genomes into reference tree with pplacer (be patient).
sh: line 1:  1242 Killed                  pplacer -j 16 -c /global/projectb/scratch/snayfach/databases/GTDB/pplacer/gtdb_r86_bac120.refpkg -o /global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/pplacer/pplacer.bac120.json /global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/align/gtdbtk.bac120.user_msa.fasta > /global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/pplacer/pplacer.bac120.out
Uncaught exception: Sys_error("/global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/pplacer/pplacer.bac120.json: No such file or directory")
Fatal error: exception Sys_error("/global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/pplacer/pplacer.bac120.json: No such file or directory")
GTDB-Tk has stopped before finishing
[Errno 2] No such file or directory: '/global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/gtdbtk.bac120.classify.tree'
('Unexpected error:', <type 'exceptions.IOError'>)
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.local/bin/gtdbtk", line 388, in <module>
    gt_parser.parse_options(args)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 376, in parse_options
    self.classify(options)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 263, in classify
    options.debug)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/classify.py", line 196, in run
    preserve_underscores=True)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 215, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 60, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/global/projectb/scratch/snayfach/projects/img_mags/4_taxonomy/gtdbtk_out/1/classify/gtdbtk.bac120.classify.tree'
```

Any ideas what might be the issue?

**Comment by snayfach** [comment]
Hmmm, I think I might have run out of RAM. I requested 100GB. Let me try with more RAM and see if the error goes away

**Comment by snayfach** [comment]
Increasing the RAM to 200 GB solved this issue
