### ISSUE TITLE
GTDBTk fails to run for certain genomes

### ISSUE THREAD

**Issue by snayfach** [Ecogenomics/GTDBTk#89]
I'm getting an error for GTDB-Tk v0.1.6 and release 86 with the following:
```
gtdbtk identify --batchfile genome_list --out_dir out/identify 
gtdbtk align --identify_dir out/identify --out_dir out/align 
gtdbtk classify --batchfile genome_list --align_dir out/align --out_dir out/classify 
```

After the last command I get this error:
```
IOError: [Errno 2] No such file or directory: 'out/classify/gtdbtk.bac120.classify.tree'
```

The genome causing problems is attached and is estimated by CheckM to be nearly 100% complete with no contamination.
[3300012847_7.fna 2.zip](https://github.com/Ecogenomics/GTDBTk/files/2862213/3300012847_7.fna.2.zip)

**Comment by dparks1134** [comment]
Hello Stephen,

We've been unable to reproduce the issue on our end. We have successfully run this genome through GTDB-Tk on a number of different servers. Best guess is that pplacer is running out of memory. pplacer requires <128 GB, but seems to have an odd way of allocating memory that is problematic for some Linux flavors and batch systems (e.g. SGE). Best I can tell, the end result is that pplacer appears to request upwards of 128 GB and the amount of memory the batch system expects pplacer to require depends on the number of threads. This can cause batch systems to determinate pplacer since the memory requirements exceed what was allocated for the process.

Cheers,
Donovan

**Comment by snayfach** [comment]
I'll give it another go and provide more details if I can't get it to work. Thanks!

**Comment by snayfach** [comment]
After adding more RAM, I've successfully run the tool on several thousand genomes, but ~60 are throwing errors during the classify stage. Here is one example:

```
[2019-03-11 22:09:43] INFO: GTDB-Tk v0.1.6
[2019-03-11 22:09:43] INFO: gtdbtk classify --batchfile /global/projectb/scratch/snayfach/projects/img_mags/5_taxonomy/genome_lists/63.tsv --align_dir /global/projectb/scratch/snayfach/projects/img_mags/5_taxonomy/out/24286311_63/align --out_dir /global/projectb/scratch/snayfach/projects/img_mags/5_taxonomy/out/24286311_63/classify --cpus 1
[2019-03-11 22:09:43] WARNING: Results are still being validated and taxonomic assignments may be incorrect! Use at your own risk!
[2019-03-11 22:09:43] INFO: Placing 1 bacterial genomes into reference tree with pplacer (be patient).
[2019-03-11 22:23:59] INFO: Calculating Average Nucleotide Identity using FastANI.
GTDB-Tk has stopped before finishing
local variable 'pplacer_leafnode' referenced before assignment
('Unexpected error:', <type 'exceptions.UnboundLocalError'>)
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.local/bin/gtdbtk", line 388, in <module>
    gt_parser.parse_options(args)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 376, in parse_options
    self.classify(options)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 263, in classify
    options.debug)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/classify.py", line 311, in run
    fastani_verification, all_fastani_dict, summaryfout)
  File "/global/homes/s/snayfach/.local/lib/python2.7/site-packages/gtdbtk/classify.py", line 678, in _sort_fastani_results
    sorted_dict, [fastani_matching_reference, pplacer_leafnode]))
UnboundLocalError: local variable 'pplacer_leafnode' referenced before assignment
```

Here is my command:
`gtdbtk classify --batchfile $GENOME_LIST --align_dir $OUT_DIR/align --out_dir $OUT_DIR/classify --cpus 1`

And I've attached an example genome causing the problem. Any ideas what's wrong?
[2651869520.fna.zip](https://github.com/Ecogenomics/GTDBTk/files/2957330/2651869520.fna.zip)

**Comment by pchaumeil** [comment]
Hello Stephen,
in v 0.1.6 , there is a bug in the classify.py file and , in some cases, it will cause the software to crash. 

You can either edit the classify.py file
line 675:
```
                else:
                    if len(sorted_dict) > 0:
                        summary_list[12] = '; '.join(self._formatnote(
                            sorted_dict, [fastani_matching_reference, pplacer_leafnode]))
                    unclassified_user_genomes[userleaf.taxon.label] = summary_list
        return classified_user_genomes, unclassified_user_genomes
```

should be changed to:
```
                else:
                    if len(sorted_dict) > 0:
                        summary_list[12] = '; '.join(self._formatnote(
                            sorted_dict, [fastani_matching_reference]))
                    unclassified_user_genomes[userleaf.taxon.label] = summary_list
        return classified_user_genomes, unclassified_user_genomes
```


Or update GTDB-Tk to the latest version ( 0.2.1 ) to automatically fix this bug.

Thanks,
Pierre

**Comment by snayfach** [comment]
Thanks - I've updated the code

**Comment by improudofmyself** [comment]
I got the following error while running classify_wf
[2022-09-11 16:57:34] TASK: Placing 4 archaeal genomes into reference tree with pplacer using 46 CPUs (be patient).
[2022-09-11 16:57:34] INFO: pplacer version: v1.1.alpha19-0-g807f6f3
[2022-09-11 17:01:07] INFO: Calculating RED values based on reference tree.                                    
[2022-09-11 17:01:08] TASK: Traversing tree to determine classification method.
[2022-09-11 17:01:08] INFO: Completed 4 genomes in 0.00 seconds (7,087.97 genomes/second).
[2022-09-11 17:01:08] TASK: Calculating average nucleotide identity using FastANI (v1.33).
[2022-09-11 17:01:10] INFO: Completed 48 comparisons in 2.18 seconds (22.06 comparisons/second).
[2022-09-11 17:01:10] INFO: 0 genome(s) have been classified using FastANI and pplacer.
[2022-09-11 17:01:10] ERROR: Uncontrolled exit resulting from an unexpected error.

================================================================================
EXCEPTION: PermissionError
  MESSAGE: [Errno 1] Operation not permitted: 'classify/gtdbtk.ar53.summary.tsv' -> 'classify_wf_out/gtdbtk.ar53.summary.tsv'
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/__main__.py", line 98, in main
    gt_parser.parse_options(args)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/main.py", line 834, in parse_options
    self.classify(options)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/main.py", line 464, in classify
    fulltreeopt=options.full_tree)
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/classify.py", line 531, in run
    os.path.join(out_dir, os.path.basename(PATH_AR53_SUMMARY_OUT.format(prefix=prefix))))
  File "/home/scaria/anaconda3/lib/python3.7/site-packages/gtdbtk/tools.py", line 245, in symlink_f
    os.symlink(src, dst)
PermissionError: [Errno 1] Operation not permitted: 'classify/gtdbtk.ar53.summary.tsv' -> 'classify_wf_out/gtdbtk.ar53.summary.tsv'

**Comment by aaronmussig** [comment]
Hi @improudofmyself I've moved this to a new issue as it's unrelated to the existing one: https://github.com/Ecogenomics/GTDBTk/issues/431
